# Minimal in-memory Vivado flow for the Nexys 4 DDR SD-FAT test (same pattern as
# ../mem-test/build.tcl). Synthesize, implement, write bitstream, JTAG-program
# (volatile).
#   vivado -mode batch -source build.tcl
# Skip programming (build only):
#   vivado -mode batch -source build.tcl -tclargs -noburn

set part xc7a100tcsg324-1
set srcdir [file dirname [file normalize [info script]]]
set vroot  [file normalize [file join $srcdir .. .. ..]]  ;# Verilog/

set sdfat  [file join $vroot SD-FAT circuit]
set tsrc   [file join $vroot fpga tang-nano-20k sd-fat-test src]

create_project -in_memory -part $part

# The test design + its UART/menu helpers live in the (board-independent)
# Tang sd-fat-test src dir - reused, not copied. Only the top wrapper and
# pins are Nexys 4 DDR-specific.
read_verilog [list \
    [file join $srcdir nexys4ddr_sd_fat_top.v] \
    [file join $srcdir nd_memtest_mux.v] \
    [file join $srcdir nd_memtest_bram.v] \
    [file join $srcdir nd_memtest_ddr2.v] \
    [file join $vroot fpga nexys4ddr ddr2 nd_ddr2_port.v] \
    [file join $vroot CPU-BOARD-3202 circuit MEM_RAM_49.v] \
    [file join $vroot Shared support SIP1M9.v] \
    [file join $tsrc sd_fat_test_top.v] \
    [file join $tsrc uart_tx.v] \
    [file join $tsrc uart_rx.v] \
    [file join $tsrc buf_text_printer.v] \
    [file join $sdfat sd_file_reader.v] \
    [file join $sdfat sd_writer.v] \
    [file join $sdfat sd_fat_rewrite.v] \
    [file join $sdfat sd_fat_check.v] \
    [file join $sdfat sd_fat_freescan.v] ]

# status_printer.v and hex_dumper.v use $bits, which Vivado rejects in plain
# Verilog-2001 mode (Synth 8-11198). Read just those two as SystemVerilog -
# the shared source belongs to the SD workstream and is not edited here.
read_verilog -sv [list \
    [file join $tsrc status_printer.v] \
    [file join $tsrc hex_dumper.v] ]

# The DDR2 controller, generated by ../ddr2-test/gen_mig.tcl from Digilent's
# own MIG project file. read_ip brings in the core AND its constraints - the
# DDR2 pin locations, I/O standards and timing all come from there, which is
# why none of them are hand-written in the XDC below.
set migxci [file join $vroot fpga nexys4ddr ddr2-test ip ddr ddr.xci]
if {![file exists $migxci]} {
    puts "ERROR: MIG core not generated: $migxci"
    puts "Run: vivado -mode batch -source ../ddr2-test/gen_mig.tcl"
    exit 1
}
read_ip $migxci

read_xdc [file join $srcdir nexys4ddr_sd_fat.xdc]

# sd_fat_test_top does `include "sd_fat_features.vh" (lives in SD-FAT/circuit)
# SDFAT_BUF_BLOCKRAM  force the 64 KB file buffer into block RAM (Vivado maps
#                     it to distributed RAM otherwise and placement fails)
# SDFAT_EXT_TEST      add the memory-test menu commands: B = ND-120 memory
#                     path, M = DDR2 (the DDR2 half is not in this bitstream
#                     yet - see ../ddr2-test/ - and answers "DDR2 NOT IN BUILD")
synth_design -top nexys4ddr_sd_fat_top -part $part -include_dirs $sdfat \
    -verilog_define SDFAT_BUF_BLOCKRAM \
    -verilog_define SDFAT_EXT_TEST \
    -verilog_define NEXYS_DDR2_TEST
# The console (27.027 MHz, clk27_pre) and the DDR2 controller's user clock
# (75 MHz, clk_pll_i, created inside the MIG core) are UNRELATED. Vivado
# otherwise times the crossings between them as related clocks and demands
# 0.333 ns, which no crossing can meet - measured 20-AUG-2026: ack_tgl -> a1
# at -2.359 ns and ui_busy -> b1 at -3.304 ns. Those two registers are the
# two-flop synchronisers that exist to absorb exactly this, and every data
# byte crossing is held stable by the request/acknowledge toggle in
# nd_memtest_ddr2.v until the far side has taken it.
#
# Applied HERE, after synth_design, because clk_pll_i does not exist until
# the MIG core has been elaborated - a get_clocks for it in the XDC would
# match nothing and the constraint would silently do nothing.
set _c27 [get_clocks -quiet clk27_pre]
set _cui [get_clocks -quiet clk_pll_i]
if {[llength $_c27] == 0 || [llength $_cui] == 0} {
    puts "ERROR: expected clocks not found (clk27_pre / clk_pll_i)."
    puts "  clocks present: [get_clocks]"
    exit 1
}
set_clock_groups -asynchronous -group $_c27 -group $_cui
puts "Declared clk27_pre and clk_pll_i asynchronous."

# Bound the crossing anyway rather than leaving it completely unconstrained:
# no crossing path may take longer than one period of the slower clock.
set_max_delay -datapath_only -from $_c27 -to $_cui 37.000
set_max_delay -datapath_only -from $_cui -to $_c27 37.000

opt_design
place_design
route_design

report_utilization    -file [file join $srcdir util.rpt]
report_timing_summary -file [file join $srcdir timing.rpt]

# Fail loudly on negative slack. The DDR2 controller adds a 200 MHz input
# clock and a 75 MHz ui_clk domain, and the console crossings between them
# are hand-synchronised - a timing miss here must not be flashed silently.
set wns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
puts "WNS: $wns ns"
if {$wns < 0} {
    puts "ERROR: timing NOT met (WNS $wns ns). See timing.rpt."
    exit 1
}

set bit [file join $srcdir nexys4ddr_sd_fat.bit]
write_bitstream -force $bit
puts "BITSTREAM: $bit"

if {[lsearch $argv "-noburn"] >= 0} {
    puts "=== SD-FAT BUILD COMPLETE (not programmed) ==="
    return
}

# ---- program over JTAG (volatile; power-cycle wipes it) ----
open_hw_manager
connect_hw_server
open_hw_target
set dev [lindex [get_hw_devices xc7a100t*] 0]
current_hw_device $dev
set_property PROGRAM.FILE $bit $dev
program_hw_devices $dev
puts "PROGRAMMED (JTAG)"
close_hw_manager

puts "=== SD-FAT BUILD COMPLETE ==="
