#!/usr/bin/env python3
"""Pull the TDV2200 character set 2 glyphs out of RetroCore's ROM font dump.

    python3 tdv2200_set2_from_retrocore.py \
        E:/Dev/Repos/Ronny/RetroCore/Nuget/HackerCorpLabs.Emulation.Chips.Terminal/src/FontBitmaps/FontTDV2200.cs \
        tdv2200_set2.py

Character set 2 is what the TDV2200 shows for SS2 (ESC N) and for a locking
shift to G2 (see Terminals/docs/SPEC-tdv2200.md). It is NOT the VT100 DEC
Special Graphics alphabet and it is NOT the ESC 6 (NDSS6) Box set either:
measured on the Nexys 4 DDR on 01-SEP-2026, PED drew its frames as diamonds
when the board rendered SS2 through the DEC page, because in set 2 code 0x60
is the HORIZONTAL LINE (DEC draws a diamond there) and the corners and tees
sit at 0x61-0x6A.

RetroCore (and RetroTerm, which carries the same table) render PED correctly
by indexing the dump of the
real TDV2200 character ROM (FontTDV2200.cs) with the character code plus 128
for SS2 - no Unicode table in between. RetroCore's ROM dump is therefore the
reference, and this script copies it rather than re-typing it.

FontTDV2200.cs carries every glyph twice: as the ushort bitmap the renderer
uses, and as an ASCII-art comment above it ("// Character 0x0E0" followed by
sixteen rows, each "//", one space, then eight columns of ' ' or 'X'). The
comment is what we parse - it is self-describing and immune to the C# array's
own layout quirks - and its eight columns are our eight pixels, leftmost
first. The vertical stroke of the box glyphs lands on column 4, the same
column make_font.py's synthesized strokes use, so the ROM's own glyphs and
the synthesized ones line up.

The output is a Python module holding SET2, a list of 128 sixteen-byte
glyphs indexed by character code, MSB = leftmost pixel - the layout
make_font.py wants for a font page. Re-run this only when RetroCore's ROM
dump changes; the generated module is committed so make_font.py does not
depend on the RetroCore checkout being present.
"""

import re
import sys

ART_COLS = 8      # columns in the ASCII art = pixels per row
ART_ROWS = 16     # rows per glyph in the art
SET2_BASE = 0x80  # RetroCore's FontNumOffset[2] - set 2 starts at ROM glyph 128
SET2_SIZE = 128

HEADER = re.compile(r"^// Character 0x([0-9A-Fa-f]+)\s*$")


def parse_art(text):
    """Return {glyph_index: [16 art rows]} for every glyph in the C# file."""
    glyphs = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        m = HEADER.match(lines[i])
        if not m:
            i += 1
            continue
        index = int(m.group(1), 16)
        rows = []
        j = i + 1
        while j < len(lines) and len(rows) < ART_ROWS:
            line = lines[j]
            if not line.startswith("//"):
                break
            body = line[2:]
            # A row is "//", one space, then exactly ART_COLS of ' ' or 'X'.
            # Anything else ends the block early.
            if not re.fullmatch(r" [ X]{%d}" % ART_COLS, body):
                break
            rows.append(body[1:])
            j += 1
        if len(rows) == ART_ROWS:
            glyphs[index] = rows
        i = j if j > i else i + 1
    return glyphs


def rows_to_bytes(rows):
    """Sixteen art rows -> sixteen bytes, MSB = leftmost column."""
    out = []
    for row in rows:
        value = 0
        for c in range(ART_COLS):
            value = (value << 1) | (1 if row[c] == "X" else 0)
        out.append(value)
    return bytes(out)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8") as handle:
        glyphs = parse_art(handle.read())

    missing = [SET2_BASE + c for c in range(SET2_SIZE) if SET2_BASE + c not in glyphs]
    if missing:
        raise SystemExit("no art for ROM glyphs: %s"
                         % ", ".join("0x%03X" % g for g in missing))

    set2 = [rows_to_bytes(glyphs[SET2_BASE + c]) for c in range(SET2_SIZE)]

    with open(dst, "w", encoding="ascii", newline="\n") as out:
        out.write("# TDV2200 character set 2 (SS2 / G2) - GENERATED by\n")
        out.write("# tdv2200_set2_from_retrocore.py from RetroCore's FontTDV2200.cs.\n")
        out.write("# Do not hand-edit; re-run the script. See its docstring for why\n")
        out.write("# this set, and why RetroCore's ROM dump is the reference.\n")
        out.write("#\n")
        out.write("# 128 glyphs indexed by character code, 16 bytes each, one pixel\n")
        out.write("# row per byte, MSB = leftmost pixel.\n")
        out.write("\n")
        out.write("SET2 = [\n")
        for code, glyph in enumerate(set2):
            # Keep the art next to the bytes so a reader can see the glyph
            # without decoding hex in their head.
            art = ["".join("X" if (b >> (7 - x)) & 1 else "." for x in range(8))
                   for b in glyph]
            out.write("    # 0x%02X %s\n" % (code, "  ".join(art[2:11])))
            out.write("    bytes([%s]),\n" % ", ".join("0x%02X" % b for b in glyph))
        out.write("]\n")
        out.write("assert len(SET2) == 128\n")
    print("wrote %s: %d glyphs" % (dst, len(set2)))


if __name__ == "__main__":
    main()
