remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Norsk Data ND-120 CPU Board
description: Contains original ND-120 design documents, Logisim drawings of the design. Verilog code that behaves like the original ND-120 3202D CPU Board
