#!/usr/bin/env python3
"""
vcd2png.py - render a testbench's VCD as a committed waveform PNG.

WHY THIS EXISTS
    A testbench that prints "TB_RESULT: PASS" tells you it passed. It does not
    tell you WHAT it looked at, or let anyone check the claim without
    re-running the simulation. A committed waveform is documentation that
    cannot drift from the test: it is generated by the same run that produced
    the verdict.

WHAT IT DOES
    Reads a VCD, picks the signals asked for (or all of them, capped), and
    draws them as a classic digital timing diagram - single bits as a
    high/low trace, buses as the usual hex-labelled "stretched hexagon".
    Output is a PNG next to the testbench, meant to be committed.

USAGE
    tests/vcd2png.py WAVE.vcd -o waves/my_tb.png
    tests/vcd2png.py WAVE.vcd -o out.png --signals clk rst_n D Q --title "F595 latch"
    tests/vcd2png.py WAVE.vcd -o out.png --start 0 --end 2000

DETERMINISM MATTERS
    These files get committed, so the same VCD must always produce a
    byte-identical PNG or every test run shows up as a spurious diff. Hence:
    no timestamps in the image, fixed font, fixed layout, signals in the order
    given (or VCD declaration order), and PNG written with a fixed encoder
    setting. Do not add anything time-varying to the drawing.

Last reviewed: 20-AUG-2026
Ronny Hansen
"""

import argparse
import io
import os
import sys

try:
    from vcdvcd import VCDVCD
except ImportError:
    sys.exit("vcd2png: needs 'vcdvcd' (pip install vcdvcd)")

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("vcd2png: needs 'pillow' (pip install pillow)")


# ---- fixed layout, so output is reproducible -------------------------------
LEFT_W = 210          # label gutter
ROW_H = 34            # per-signal row height
ROW_GAP = 10
TOP_H = 46            # title strip
BOT_H = 26            # time axis
RIGHT_PAD = 24
WIDTH = 1600
# Palette: Verilog/docs/COLOR-STANDARDS.md - WCAG 2.1 AA, all entries >= 4.5:1
# against their background, in BOTH modes. Direction is ALSO printed as an
# IN/OUT/CLK tag on every row, because input-blue and output-green measure
# only 1.68:1 apart and colour alone cannot separate them for a red-green
# colourblind reader or in greyscale (WCAG 1.4.1).
LIGHT = dict(BG=(255, 255, 255), FG=(24, 24, 24), GRID=(222, 222, 222),
             TXT=(33, 33, 33), MUTED=(84, 110, 122),
             IN=(13, 71, 161), OUT=(46, 125, 50), BIDIR=(154, 52, 18),
             CLK=(106, 27, 154), ERR=(183, 28, 28),
             BUSFILL=(227, 242, 253))
DARK  = dict(BG=(30, 30, 30), FG=(240, 240, 240), GRID=(60, 60, 60),
             TXT=(235, 235, 235), MUTED=(176, 190, 197),
             IN=(144, 202, 249), OUT=(102, 187, 106), BIDIR=(255, 183, 77),
             CLK=(206, 147, 216), ERR=(239, 154, 154),
             BUSFILL=(38, 50, 56))
C = LIGHT                  # swapped to DARK by --dark


def _font(size):
    """A font that exists on this machine, tried in a fixed order so the
    rendering is reproducible rather than whatever fontconfig feels like."""
    for path in (
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    ):
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


CLOCK_NAMES = ("clk", "sysclk", "clock", "sys_clk", "ui_clk", "clk_cpu",
               "clk_stor", "clk2x", "mclk", "aluclk", "maclk", "uclk", "osc")


def is_clock(n):
    b = n.lower().rstrip("_n")
    return (b in CLOCK_NAMES or b.endswith("clk") or b.endswith("clock")
            or b.startswith("clk"))


def port_dirs(rtl_path):
    """Map leaf signal name -> 'input'/'output'/'inout', read from the RTL.

    Derived from the source rather than typed on the command line: a waveform
    that colours a signal as an output when the module declares it an input is
    worse than no colour at all.
    """
    import re
    dirs = {}
    try:
        txt = io.open(rtl_path, encoding="utf-8", errors="replace").read()
    except OSError as e:
        print(f"vcd2png: WARNING cannot read {rtl_path}: {e}", file=sys.stderr)
        return dirs
    txt = re.sub(r"//[^\n]*", "", txt)
    txt = re.sub(r"/\*.*?\*/", "", txt, flags=re.S)
    for m in re.finditer(r"\b(input|output|inout)\b((?:\s+(?:wire|reg|logic|signed))*)"
                         r"(\s*\[[^\]]*\])?\s*([A-Za-z_][A-Za-z0-9_$]*)", txt):
        dirs[m.group(4)] = m.group(1)
    return dirs


def role_of(nm, dirs):
    if is_clock(nm):
        return "CLK"
    d = dirs.get(nm)
    if d == "output":
        return "OUT"
    if d == "inout":
        return "I/O"
    if d == "input":
        return "IN"
    return ""


def leaf(ref):
    """'tb.DUT.A[7:0]' -> 'A'.  VCD references carry both the scope path and,
    for vectors, a [msb:lsb] suffix; a user asking for 'A' means either."""
    base = ref.split(".")[-1]
    return base.split("[")[0]


def collect(vcd, wanted):
    """Return [(display_name, [(time, value), ...]), ...] in a stable order.

    Signals are matched on their LEAF name so the caller can write 'A' rather
    than 'vcdgen_tb.DUT.A[7:0]'. When a name appears at several scope levels
    (the testbench's copy and the DUT's), the SHALLOWEST is taken - that is
    the testbench-visible one, which is what a reader of the picture expects.
    """
    names = list(vcd.references_to_ids.keys())
    if wanted:
        chosen = []
        for w in wanted:
            want = w.split("[")[0]
            hits = [n for n in names if leaf(n) == want or n == w]
            if not hits:
                print(f"vcd2png: WARNING no signal matches '{w}'", file=sys.stderr)
                continue
            hits.sort(key=lambda n: n.count("."))   # shallowest scope first
            chosen.append(hits[0])
    else:
        chosen = names
    out = []
    for n in chosen:
        sig = vcd[n]
        tv = [(int(t), v) for t, v in sig.tv]
        if tv:
            out.append((leaf(n), tv))
    return out


def value_at(tv, t):
    v = None
    for tt, vv in tv:
        if tt <= t:
            v = vv
        else:
            break
    return v


def is_bus(tv):
    return any(len(str(v)) > 1 for _, v in tv)


def draw(sigs, t0, t1, title, outfile, dirs=None):
    n = len(sigs)
    height = TOP_H + n * (ROW_H + ROW_GAP) + BOT_H
    dirs = dirs or {}
    img = Image.new("RGB", (WIDTH, height), C["BG"])
    d = ImageDraw.Draw(img)
    f_title = _font(17)
    f_lab = _font(13)
    f_val = _font(11)

    plot_w = WIDTH - LEFT_W - RIGHT_PAD
    span = max(1, t1 - t0)

    def x_of(t):
        return LEFT_W + int((t - t0) * plot_w / span)

    if title:
        d.text((14, 14), title, font=f_title, fill=C["FG"])

    # vertical grid, 10 divisions
    for i in range(11):
        x = LEFT_W + int(i * plot_w / 10)
        d.line([(x, TOP_H - 6), (x, height - BOT_H)], fill=C["GRID"])

    for row, (name, tv) in enumerate(sigs):
        top = TOP_H + row * (ROW_H + ROW_GAP)
        mid = top + ROW_H // 2
        lo = top + ROW_H - 6
        hi = top + 6

        role = role_of(name, dirs)
        col  = {"IN": C["IN"], "OUT": C["OUT"], "I/O": C["BIDIR"],
                "CLK": C["CLK"]}.get(role, C["TXT"])
        if role:
            d.text((14, mid - 7), f"{role:<4}", font=f_val, fill=col)
        d.text((52, mid - 7), name[:22], font=f_lab, fill=col)

        edges = sorted({t for t, _ in tv if t0 <= t <= t1} | {t0, t1})
        bus = is_bus(tv)

        for i in range(len(edges) - 1):
            ta, tb = edges[i], edges[i + 1]
            xa, xb = x_of(ta), x_of(tb)
            if xb <= xa:
                continue
            v = value_at(tv, ta)
            if v is None:
                continue
            s = str(v)

            if bus:
                # hexagon body with the value written in it
                k = min(6, max(2, (xb - xa) // 6))
                d.polygon(
                    [(xa + k, hi), (xb - k, hi), (xb, mid),
                     (xb - k, lo), (xa + k, lo), (xa, mid)],
                    fill=C["BUSFILL"], outline=col)
                try:
                    lab = f"{int(s, 2):X}" if set(s) <= set("01") else s
                except ValueError:
                    lab = s
                tw = d.textlength(lab, font=f_val)
                if tw < (xb - xa) - 8:
                    d.text(((xa + xb) / 2 - tw / 2, mid - 6), lab,
                           font=f_val, fill=C["TXT"])
            else:
                if s in ("1", "b1", "h1"):
                    y = hi
                elif s in ("0", "b0", "h0"):
                    y = lo
                else:                      # x / z - draw a muted mid band
                    # X / Z: a MID-HEIGHT BAND in the error colour, never a
                    # level - the shape is the cue, not just the colour
                    d.line([(xa, mid), (xb, mid)], fill=C["ERR"], width=3)
                    continue
                d.line([(xa, y), (xb, y)], fill=col, width=2)
                nv = value_at(tv, tb)
                if nv is not None and str(nv) != s and tb <= t1:
                    d.line([(xb, hi), (xb, lo)], fill=col, width=2)

    # time axis
    ay = height - BOT_H + 6
    d.line([(LEFT_W, ay), (WIDTH - RIGHT_PAD, ay)], fill=C["MUTED"])
    for i in range(11):
        x = LEFT_W + int(i * plot_w / 10)
        t = t0 + i * span // 10
        d.line([(x, ay), (x, ay + 4)], fill=C["MUTED"])
        lab = str(t)
        d.text((x - d.textlength(lab, font=f_val) / 2, ay + 6), lab,
               font=f_val, fill=C["MUTED"])

    os.makedirs(os.path.dirname(os.path.abspath(outfile)) or ".", exist_ok=True)
    # optimize=True keeps the encoder deterministic for a given input
    img.save(outfile, "PNG", optimize=True)
    return outfile


def main():
    ap = argparse.ArgumentParser(description="Render a VCD as a committed waveform PNG")
    ap.add_argument("vcd")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--signals", nargs="*", default=None,
                    help="signal names (leaf name is enough); default = all, capped")
    ap.add_argument("--title", default=None)
    ap.add_argument("--start", type=int, default=None)
    ap.add_argument("--end", type=int, default=None)
    ap.add_argument("--max-signals", type=int, default=16)
    ap.add_argument("--rtl", default=None,
                    help="module source; port directions drive the colours")
    ap.add_argument("--dark", action="store_true", help="dark-mode palette")
    args = ap.parse_args()

    global C
    if args.dark:
        C = DARK
    dirs = port_dirs(args.rtl) if args.rtl else {}
    vcd = VCDVCD(args.vcd)
    sigs = collect(vcd, args.signals)
    if not sigs:
        sys.exit("vcd2png: no signals found")
    if len(sigs) > args.max_signals:
        print(f"vcd2png: {len(sigs)} signals, showing first {args.max_signals}",
              file=sys.stderr)
        sigs = sigs[:args.max_signals]

    all_t = [t for _, tv in sigs for t, _ in tv]
    t0 = args.start if args.start is not None else min(all_t)
    t1 = args.end if args.end is not None else max(all_t)
    if t1 <= t0:
        t1 = t0 + 1

    # clock first - everything else is read relative to it
    sigs.sort(key=lambda kv: 0 if is_clock(kv[0]) else 1)
    out = draw(sigs, t0, t1, args.title or os.path.basename(args.vcd),
               args.out, dirs)
    print(f"vcd2png: wrote {out}  ({len(sigs)} signals, t={t0}..{t1})")


if __name__ == "__main__":
    main()
