/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MAC_SEGPT_SEG testbench                                           **
**                                                                       **
** Exhaustive verification of the segment register (/CGA/MAC/SEGPT/SEG,  **
** page 36). Netlist read-out (BubblesMask decoded):                     **
**   L8 SEG_L : A..H = FIDBO[0..7] -> SEG[0..7] (+ inverted rail),       **
**              latch enable L = GATES_2                                 **
**   GATES_2 AND  mask 00 : L = MCLKN & LLDSEG                           **
**   GATES_1 NAND8 mask 00: SEGZN = ~(&seg_n) = (SEG != 0)               **
**                                                                       **
** Checks (input space = 8 data + 2 enables -> fully covered):           **
**  1. Transparent exhaustive sweep: latch held open (MCLKN=1 LLDSEG=1), **
**     all 256 FIDBO values; SEG must follow combinationally and SEGZN   **
**     must match a 256-entry golden table generated by an independent   **
**     Python gate model (gen_segpt_golden.py, scratchpad only).         **
**  2. Latched load + hold: 14 directed patterns (zero, ones, alternat-  **
**     ing, walking-one) loaded with a latch pulse, then the data bus    **
**     driven to the complement with the latch closed - SEG and SEGZN    **
**     must hold.                                                        **
**  3. Enable gating: MCLKN=1&LLDSEG=0, MCLKN=0&LLDSEG=1, 0&0 - new data **
**     plus sysclk edges must NOT load.                                  **
**                                                                       **
** The load pulse is valid in BOTH latch builds: plain / -DFPGA_FF_MODE  **
** (L8 = mux + posedge-sysclk FF, transparent while L=1) and             **
** -DUSE_TRANSPARENT_LATCHES (true level latch): data is held stable     **
** across a posedge sysclk while L=1, then L falls before data moves.    **
** The Makefile target runs all three builds.                            **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MAC_SEGPT_SEG_tb;

  reg        sysclk = 0;
  reg  [7:0] FIDBO = 0;
  reg        LLDSEG = 0;
  reg        MCLKN = 0;

  wire       SEGZN;
  wire [7:0] SEG;

  integer errors = 0;
  integer checks = 0;
  integer i;

  localparam integer EXPECTED_CHECKS = 543;

  // Directed load patterns for the latched-path test
  reg [7:0] pat[0:13];

  CGA_MAC_SEGPT_SEG dut (
      .sysclk   (sysclk),
      .sys_rst_n(1'b1),
      .FIDBO_7_0(FIDBO),
      .LLDSEG   (LLDSEG),
      .MCLKN    (MCLKN),
      .SEGZN    (SEGZN),
      .SEG_7_0  (SEG)
  );

  always #5 sysclk = ~sysclk;

  // One latch-load event, valid in BOTH latch builds: data stable, L
  // raised, a posedge sysclk passes (FF-mode capture), then L falls
  // (transparent-mode capture at the falling edge of L).
  task load_byte(input [7:0] v);
    begin
      @(negedge sysclk);
      FIDBO  = v;
      LLDSEG = 1;
      MCLKN  = 1;
      @(posedge sysclk);
      #1 MCLKN = 0;
      LLDSEG = 0;
      #1;
    end
  endtask

  task check_seg(input [7:0] exp_seg, input [127:0] name);
    begin
      checks = checks + 1;
      if (SEG !== exp_seg) begin
        errors = errors + 1;
        $display("FAIL %0s: SEG=%02x expected %02x", name, SEG, exp_seg);
      end
    end
  endtask

  task check_zn(input exp_zn, input [127:0] name);
    begin
      checks = checks + 1;
      if (SEGZN !== exp_zn) begin
        errors = errors + 1;
        $display("FAIL %0s: SEGZN=%b expected %b", name, SEGZN, exp_zn);
      end
    end
  endtask

  // Golden SEGZN table generated by the independent Python gate model
  // (gen_segpt_golden.py): NAND8(mask 0) of the eight inverted latch rails.
  function seg_zn_golden(input [7:0] v);
    begin
      case (v)
      8'h00: seg_zn_golden = 1'b0;
      8'h01: seg_zn_golden = 1'b1;
      8'h02: seg_zn_golden = 1'b1;
      8'h03: seg_zn_golden = 1'b1;
      8'h04: seg_zn_golden = 1'b1;
      8'h05: seg_zn_golden = 1'b1;
      8'h06: seg_zn_golden = 1'b1;
      8'h07: seg_zn_golden = 1'b1;
      8'h08: seg_zn_golden = 1'b1;
      8'h09: seg_zn_golden = 1'b1;
      8'h0a: seg_zn_golden = 1'b1;
      8'h0b: seg_zn_golden = 1'b1;
      8'h0c: seg_zn_golden = 1'b1;
      8'h0d: seg_zn_golden = 1'b1;
      8'h0e: seg_zn_golden = 1'b1;
      8'h0f: seg_zn_golden = 1'b1;
      8'h10: seg_zn_golden = 1'b1;
      8'h11: seg_zn_golden = 1'b1;
      8'h12: seg_zn_golden = 1'b1;
      8'h13: seg_zn_golden = 1'b1;
      8'h14: seg_zn_golden = 1'b1;
      8'h15: seg_zn_golden = 1'b1;
      8'h16: seg_zn_golden = 1'b1;
      8'h17: seg_zn_golden = 1'b1;
      8'h18: seg_zn_golden = 1'b1;
      8'h19: seg_zn_golden = 1'b1;
      8'h1a: seg_zn_golden = 1'b1;
      8'h1b: seg_zn_golden = 1'b1;
      8'h1c: seg_zn_golden = 1'b1;
      8'h1d: seg_zn_golden = 1'b1;
      8'h1e: seg_zn_golden = 1'b1;
      8'h1f: seg_zn_golden = 1'b1;
      8'h20: seg_zn_golden = 1'b1;
      8'h21: seg_zn_golden = 1'b1;
      8'h22: seg_zn_golden = 1'b1;
      8'h23: seg_zn_golden = 1'b1;
      8'h24: seg_zn_golden = 1'b1;
      8'h25: seg_zn_golden = 1'b1;
      8'h26: seg_zn_golden = 1'b1;
      8'h27: seg_zn_golden = 1'b1;
      8'h28: seg_zn_golden = 1'b1;
      8'h29: seg_zn_golden = 1'b1;
      8'h2a: seg_zn_golden = 1'b1;
      8'h2b: seg_zn_golden = 1'b1;
      8'h2c: seg_zn_golden = 1'b1;
      8'h2d: seg_zn_golden = 1'b1;
      8'h2e: seg_zn_golden = 1'b1;
      8'h2f: seg_zn_golden = 1'b1;
      8'h30: seg_zn_golden = 1'b1;
      8'h31: seg_zn_golden = 1'b1;
      8'h32: seg_zn_golden = 1'b1;
      8'h33: seg_zn_golden = 1'b1;
      8'h34: seg_zn_golden = 1'b1;
      8'h35: seg_zn_golden = 1'b1;
      8'h36: seg_zn_golden = 1'b1;
      8'h37: seg_zn_golden = 1'b1;
      8'h38: seg_zn_golden = 1'b1;
      8'h39: seg_zn_golden = 1'b1;
      8'h3a: seg_zn_golden = 1'b1;
      8'h3b: seg_zn_golden = 1'b1;
      8'h3c: seg_zn_golden = 1'b1;
      8'h3d: seg_zn_golden = 1'b1;
      8'h3e: seg_zn_golden = 1'b1;
      8'h3f: seg_zn_golden = 1'b1;
      8'h40: seg_zn_golden = 1'b1;
      8'h41: seg_zn_golden = 1'b1;
      8'h42: seg_zn_golden = 1'b1;
      8'h43: seg_zn_golden = 1'b1;
      8'h44: seg_zn_golden = 1'b1;
      8'h45: seg_zn_golden = 1'b1;
      8'h46: seg_zn_golden = 1'b1;
      8'h47: seg_zn_golden = 1'b1;
      8'h48: seg_zn_golden = 1'b1;
      8'h49: seg_zn_golden = 1'b1;
      8'h4a: seg_zn_golden = 1'b1;
      8'h4b: seg_zn_golden = 1'b1;
      8'h4c: seg_zn_golden = 1'b1;
      8'h4d: seg_zn_golden = 1'b1;
      8'h4e: seg_zn_golden = 1'b1;
      8'h4f: seg_zn_golden = 1'b1;
      8'h50: seg_zn_golden = 1'b1;
      8'h51: seg_zn_golden = 1'b1;
      8'h52: seg_zn_golden = 1'b1;
      8'h53: seg_zn_golden = 1'b1;
      8'h54: seg_zn_golden = 1'b1;
      8'h55: seg_zn_golden = 1'b1;
      8'h56: seg_zn_golden = 1'b1;
      8'h57: seg_zn_golden = 1'b1;
      8'h58: seg_zn_golden = 1'b1;
      8'h59: seg_zn_golden = 1'b1;
      8'h5a: seg_zn_golden = 1'b1;
      8'h5b: seg_zn_golden = 1'b1;
      8'h5c: seg_zn_golden = 1'b1;
      8'h5d: seg_zn_golden = 1'b1;
      8'h5e: seg_zn_golden = 1'b1;
      8'h5f: seg_zn_golden = 1'b1;
      8'h60: seg_zn_golden = 1'b1;
      8'h61: seg_zn_golden = 1'b1;
      8'h62: seg_zn_golden = 1'b1;
      8'h63: seg_zn_golden = 1'b1;
      8'h64: seg_zn_golden = 1'b1;
      8'h65: seg_zn_golden = 1'b1;
      8'h66: seg_zn_golden = 1'b1;
      8'h67: seg_zn_golden = 1'b1;
      8'h68: seg_zn_golden = 1'b1;
      8'h69: seg_zn_golden = 1'b1;
      8'h6a: seg_zn_golden = 1'b1;
      8'h6b: seg_zn_golden = 1'b1;
      8'h6c: seg_zn_golden = 1'b1;
      8'h6d: seg_zn_golden = 1'b1;
      8'h6e: seg_zn_golden = 1'b1;
      8'h6f: seg_zn_golden = 1'b1;
      8'h70: seg_zn_golden = 1'b1;
      8'h71: seg_zn_golden = 1'b1;
      8'h72: seg_zn_golden = 1'b1;
      8'h73: seg_zn_golden = 1'b1;
      8'h74: seg_zn_golden = 1'b1;
      8'h75: seg_zn_golden = 1'b1;
      8'h76: seg_zn_golden = 1'b1;
      8'h77: seg_zn_golden = 1'b1;
      8'h78: seg_zn_golden = 1'b1;
      8'h79: seg_zn_golden = 1'b1;
      8'h7a: seg_zn_golden = 1'b1;
      8'h7b: seg_zn_golden = 1'b1;
      8'h7c: seg_zn_golden = 1'b1;
      8'h7d: seg_zn_golden = 1'b1;
      8'h7e: seg_zn_golden = 1'b1;
      8'h7f: seg_zn_golden = 1'b1;
      8'h80: seg_zn_golden = 1'b1;
      8'h81: seg_zn_golden = 1'b1;
      8'h82: seg_zn_golden = 1'b1;
      8'h83: seg_zn_golden = 1'b1;
      8'h84: seg_zn_golden = 1'b1;
      8'h85: seg_zn_golden = 1'b1;
      8'h86: seg_zn_golden = 1'b1;
      8'h87: seg_zn_golden = 1'b1;
      8'h88: seg_zn_golden = 1'b1;
      8'h89: seg_zn_golden = 1'b1;
      8'h8a: seg_zn_golden = 1'b1;
      8'h8b: seg_zn_golden = 1'b1;
      8'h8c: seg_zn_golden = 1'b1;
      8'h8d: seg_zn_golden = 1'b1;
      8'h8e: seg_zn_golden = 1'b1;
      8'h8f: seg_zn_golden = 1'b1;
      8'h90: seg_zn_golden = 1'b1;
      8'h91: seg_zn_golden = 1'b1;
      8'h92: seg_zn_golden = 1'b1;
      8'h93: seg_zn_golden = 1'b1;
      8'h94: seg_zn_golden = 1'b1;
      8'h95: seg_zn_golden = 1'b1;
      8'h96: seg_zn_golden = 1'b1;
      8'h97: seg_zn_golden = 1'b1;
      8'h98: seg_zn_golden = 1'b1;
      8'h99: seg_zn_golden = 1'b1;
      8'h9a: seg_zn_golden = 1'b1;
      8'h9b: seg_zn_golden = 1'b1;
      8'h9c: seg_zn_golden = 1'b1;
      8'h9d: seg_zn_golden = 1'b1;
      8'h9e: seg_zn_golden = 1'b1;
      8'h9f: seg_zn_golden = 1'b1;
      8'ha0: seg_zn_golden = 1'b1;
      8'ha1: seg_zn_golden = 1'b1;
      8'ha2: seg_zn_golden = 1'b1;
      8'ha3: seg_zn_golden = 1'b1;
      8'ha4: seg_zn_golden = 1'b1;
      8'ha5: seg_zn_golden = 1'b1;
      8'ha6: seg_zn_golden = 1'b1;
      8'ha7: seg_zn_golden = 1'b1;
      8'ha8: seg_zn_golden = 1'b1;
      8'ha9: seg_zn_golden = 1'b1;
      8'haa: seg_zn_golden = 1'b1;
      8'hab: seg_zn_golden = 1'b1;
      8'hac: seg_zn_golden = 1'b1;
      8'had: seg_zn_golden = 1'b1;
      8'hae: seg_zn_golden = 1'b1;
      8'haf: seg_zn_golden = 1'b1;
      8'hb0: seg_zn_golden = 1'b1;
      8'hb1: seg_zn_golden = 1'b1;
      8'hb2: seg_zn_golden = 1'b1;
      8'hb3: seg_zn_golden = 1'b1;
      8'hb4: seg_zn_golden = 1'b1;
      8'hb5: seg_zn_golden = 1'b1;
      8'hb6: seg_zn_golden = 1'b1;
      8'hb7: seg_zn_golden = 1'b1;
      8'hb8: seg_zn_golden = 1'b1;
      8'hb9: seg_zn_golden = 1'b1;
      8'hba: seg_zn_golden = 1'b1;
      8'hbb: seg_zn_golden = 1'b1;
      8'hbc: seg_zn_golden = 1'b1;
      8'hbd: seg_zn_golden = 1'b1;
      8'hbe: seg_zn_golden = 1'b1;
      8'hbf: seg_zn_golden = 1'b1;
      8'hc0: seg_zn_golden = 1'b1;
      8'hc1: seg_zn_golden = 1'b1;
      8'hc2: seg_zn_golden = 1'b1;
      8'hc3: seg_zn_golden = 1'b1;
      8'hc4: seg_zn_golden = 1'b1;
      8'hc5: seg_zn_golden = 1'b1;
      8'hc6: seg_zn_golden = 1'b1;
      8'hc7: seg_zn_golden = 1'b1;
      8'hc8: seg_zn_golden = 1'b1;
      8'hc9: seg_zn_golden = 1'b1;
      8'hca: seg_zn_golden = 1'b1;
      8'hcb: seg_zn_golden = 1'b1;
      8'hcc: seg_zn_golden = 1'b1;
      8'hcd: seg_zn_golden = 1'b1;
      8'hce: seg_zn_golden = 1'b1;
      8'hcf: seg_zn_golden = 1'b1;
      8'hd0: seg_zn_golden = 1'b1;
      8'hd1: seg_zn_golden = 1'b1;
      8'hd2: seg_zn_golden = 1'b1;
      8'hd3: seg_zn_golden = 1'b1;
      8'hd4: seg_zn_golden = 1'b1;
      8'hd5: seg_zn_golden = 1'b1;
      8'hd6: seg_zn_golden = 1'b1;
      8'hd7: seg_zn_golden = 1'b1;
      8'hd8: seg_zn_golden = 1'b1;
      8'hd9: seg_zn_golden = 1'b1;
      8'hda: seg_zn_golden = 1'b1;
      8'hdb: seg_zn_golden = 1'b1;
      8'hdc: seg_zn_golden = 1'b1;
      8'hdd: seg_zn_golden = 1'b1;
      8'hde: seg_zn_golden = 1'b1;
      8'hdf: seg_zn_golden = 1'b1;
      8'he0: seg_zn_golden = 1'b1;
      8'he1: seg_zn_golden = 1'b1;
      8'he2: seg_zn_golden = 1'b1;
      8'he3: seg_zn_golden = 1'b1;
      8'he4: seg_zn_golden = 1'b1;
      8'he5: seg_zn_golden = 1'b1;
      8'he6: seg_zn_golden = 1'b1;
      8'he7: seg_zn_golden = 1'b1;
      8'he8: seg_zn_golden = 1'b1;
      8'he9: seg_zn_golden = 1'b1;
      8'hea: seg_zn_golden = 1'b1;
      8'heb: seg_zn_golden = 1'b1;
      8'hec: seg_zn_golden = 1'b1;
      8'hed: seg_zn_golden = 1'b1;
      8'hee: seg_zn_golden = 1'b1;
      8'hef: seg_zn_golden = 1'b1;
      8'hf0: seg_zn_golden = 1'b1;
      8'hf1: seg_zn_golden = 1'b1;
      8'hf2: seg_zn_golden = 1'b1;
      8'hf3: seg_zn_golden = 1'b1;
      8'hf4: seg_zn_golden = 1'b1;
      8'hf5: seg_zn_golden = 1'b1;
      8'hf6: seg_zn_golden = 1'b1;
      8'hf7: seg_zn_golden = 1'b1;
      8'hf8: seg_zn_golden = 1'b1;
      8'hf9: seg_zn_golden = 1'b1;
      8'hfa: seg_zn_golden = 1'b1;
      8'hfb: seg_zn_golden = 1'b1;
      8'hfc: seg_zn_golden = 1'b1;
      8'hfd: seg_zn_golden = 1'b1;
      8'hfe: seg_zn_golden = 1'b1;
      8'hff: seg_zn_golden = 1'b1;
      default: seg_zn_golden = 1'bx;
      endcase
    end
  endfunction

  initial begin
`ifdef USE_TRANSPARENT_LATCHES
    $display("CGA_MAC_SEGPT_SEG_tb: USE_TRANSPARENT_LATCHES (level latch)");
`elsif FPGA_FF_MODE
    $display("CGA_MAC_SEGPT_SEG_tb: FPGA_FF_MODE (mux + sysclk FF latch)");
`else
    $display("CGA_MAC_SEGPT_SEG_tb: plain build (mux + sysclk FF latch)");
`endif

    // ------------------------------------------------------------------
    // 1. Transparent exhaustive sweep: 256 values x (SEG + SEGZN)
    //    = 512 checks. Latch held open; output must follow.
    // ------------------------------------------------------------------
    @(negedge sysclk);
    MCLKN  = 1;
    LLDSEG = 1;
    for (i = 0; i < 256; i = i + 1) begin
      FIDBO = i[7:0];
      #2;
      check_seg(i[7:0], "transparent sweep SEG");
      check_zn(seg_zn_golden(i[7:0]), "transparent sweep SEGZN");
    end
    MCLKN  = 0;
    LLDSEG = 0;

    // ------------------------------------------------------------------
    // 2. Latched load + hold: 14 patterns x (hold SEG + hold SEGZN)
    //    = 28 checks. After each load the bus is driven to the
    //    complement with the latch closed; the register must hold.
    // ------------------------------------------------------------------
    pat[0]  = 8'h00; pat[1]  = 8'hFF; pat[2]  = 8'h55; pat[3]  = 8'hAA;
    pat[4]  = 8'h01; pat[5]  = 8'h02; pat[6]  = 8'h04; pat[7]  = 8'h08;
    pat[8]  = 8'h10; pat[9]  = 8'h20; pat[10] = 8'h40; pat[11] = 8'h80;
    pat[12] = 8'hFE; pat[13] = 8'h5A;
    for (i = 0; i < 14; i = i + 1) begin
      load_byte(pat[i]);
      FIDBO = ~pat[i];          // latch closed - must not propagate
      #22;                      // spans two sysclk edges
      check_seg(pat[i], "latched hold SEG");
      check_zn(seg_zn_golden(pat[i]), "latched hold SEGZN");
    end

    // ------------------------------------------------------------------
    // 3. Enable gating: 3 checks. State entering here: SEG = 5A.
    //    Each disabled enable combination gets new data + clock edges;
    //    the register must not load.
    // ------------------------------------------------------------------
    @(negedge sysclk);
    MCLKN = 1; LLDSEG = 0; FIDBO = 8'hA5;
    #22;
    check_seg(8'h5A, "gating MCLKN=1 LLDSEG=0");

    @(negedge sysclk);
    MCLKN = 0; LLDSEG = 1; FIDBO = 8'hC3;
    #22;
    check_seg(8'h5A, "gating MCLKN=0 LLDSEG=1");

    @(negedge sysclk);
    MCLKN = 0; LLDSEG = 0; FIDBO = 8'h3C;
    #22;
    check_seg(8'h5A, "gating MCLKN=0 LLDSEG=0");

    // ------------------------------------------------------------------
    // Verdict. Expected: 512 sweep + 28 latched + 3 gating = 543.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == EXPECTED_CHECKS)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of %0d checks)",
               errors, checks, EXPECTED_CHECKS);
    $finish;
  end

endmodule
