/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MAC_PTSEL testbench                                               **
**                                                                       **
** Exhaustive verification of the page-table select block                **
** (/CGA/MAC/PTSEL, page 34). Netlist read-out (BubblesMask decoded):    **
**   GATES_1 NOR  mask 11 : PTM & PONI; inverted -> JK preset =          **
**                          ~(PTM & PONI)  (preset unless protection on) **
**   GATES_2 OR   mask 11 : ~SPTN | ~qBar = SPT | q                      **
**   GATES_3 OR3  mask 111: ~(SAPT & PONI & PTM)                         **
**   GATES_4 NAND mask 00 : SELPTN = ~(g2 & g3)                          **
**   MEMORY_5 JK, posedge MCLK: j = SPT (=~SPTN), k = SAPT,              **
**            preset = ~(PTM & PONI) (sync, priority), reset=0, tick=1   **
**                                                                       **
** Checks:                                                               **
**  1. Combinational SELPTN: all 32 combinations of                      **
**     {q, SPTN, SAPT, PONI, PTM} vs a golden table generated by an      **
**     independent Python model (gen_golden.py). q is steered to 0 and   **
**     then 1 via clocked sequences; the 16 input combos are swept       **
**     without clocking (JK holds), q observed through the read window   **
**     SPTN=1 SAPT=0 PONI=1 PTM=1 where SELPTN = ~q.                     **
**  2. Directed JK sequences (PTM=PONI=1 so preset is off):              **
**       J=1,K=0 (SPT sel)   SETS   q (from 0 and from 1)                **
**       J=0,K=1 (SAPT sel)  CLEARS q (from 1 and from 0)                **
**       J=0,K=0             HOLDS  q (both states)                      **
**       J=K=1               TOGGLES q - real JK behavior. This is the   **
**         Issue-C hazard: if the DECODE stage ever asserted SPT and     **
**         SAPT together (pre-fix GATES_5 bug) this flop toggled every   **
**         MCLK instead of selecting APT. The RTL fix in                 **
**         CGA_MAC_DECODE.v guarantees J and K are never both 1 in       **
**         practice (mutual-exclusion invariant in CGA_MAC_DECODE_tb);   **
**         the toggle is still verified here as the correct JK function. **
**  3. Preset dominance: with PONI/PTM in 01,10,00 a clock forces q=1    **
**     even with J=0,K=1 applied.                                        **
**  4. Hold without clock: clear-combination inputs applied with no      **
**     MCLK event must not change q.                                     **
**                                                                       **
** Compile once plain (latch/CP mode, posedge MCLK) and once with        **
** -DFPGA_FF_MODE (sysclk+MCLK_EN capture) - the Makefile runs both.     **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MAC_PTSEL_tb;

  reg sysclk = 0;
  reg MCLK_EN = 0;
  reg MCLK = 0;
  reg PONI = 1;
  reg PTM = 1;
  reg SAPT = 0;
  reg SPTN = 1;
  wire SELPTN;

  integer errors = 0;
  integer checks = 0;
  integer i;
  reg exp_selptn;

  localparam integer EXPECTED_CHECKS = 51;

  CGA_MAC_PTSEL dut (
      .sysclk (sysclk),
      .MCLK_EN(MCLK_EN),
      .MCLK   (MCLK),
      .PONI   (PONI),
      .PTM    (PTM),
      .SAPT   (SAPT),
      .SPTN   (SPTN),
      .SELPTN (SELPTN)
  );

  always #5 sysclk = ~sysclk;

  // One MCLK event, valid in BOTH build modes: the EN-mode register captures
  // at posedge sysclk while MCLK_EN=1; the CP-mode register captures at the
  // posedge of MCLK raised just after the same sysclk edge (inputs stable).
  task pulse_mclk;
    begin
      @(negedge sysclk);
      MCLK_EN = 1;
      @(posedge sysclk);
      #1 MCLK = 1;
      @(negedge sysclk);
      MCLK   = 0;
      MCLK_EN = 0;
    end
  endtask

  // Read window: SPTN=1 SAPT=0 PONI=1 PTM=1 -> g2=q, g3=1, SELPTN=~q.
  // (J=0,K=0 in this window, so even a stray clock would only hold.)
  task check_q(input exp, input [127:0] name);
    begin
      SPTN = 1; SAPT = 0; PONI = 1; PTM = 1;
      #2;
      checks = checks + 1;
      if (SELPTN !== ~exp) begin
        errors = errors + 1;
        $display("FAIL %0s: q reads %b expected %b (SELPTN=%b)",
                 name, ~SELPTN, exp, SELPTN);
      end
    end
  endtask

  // Golden table generated by the independent Python model (gen_golden.py).
  // Index = {q, SPTN, SAPT, PONI, PTM}.
  function golden(input [4:0] idx);
    begin
      case (idx)
      5'b00000: golden = 1'b0;
      5'b00001: golden = 1'b0;
      5'b00010: golden = 1'b0;
      5'b00011: golden = 1'b0;
      5'b00100: golden = 1'b0;
      5'b00101: golden = 1'b0;
      5'b00110: golden = 1'b0;
      5'b00111: golden = 1'b1;
      5'b01000: golden = 1'b1;
      5'b01001: golden = 1'b1;
      5'b01010: golden = 1'b1;
      5'b01011: golden = 1'b1;
      5'b01100: golden = 1'b1;
      5'b01101: golden = 1'b1;
      5'b01110: golden = 1'b1;
      5'b01111: golden = 1'b1;
      5'b10000: golden = 1'b0;
      5'b10001: golden = 1'b0;
      5'b10010: golden = 1'b0;
      5'b10011: golden = 1'b0;
      5'b10100: golden = 1'b0;
      5'b10101: golden = 1'b0;
      5'b10110: golden = 1'b0;
      5'b10111: golden = 1'b1;
      5'b11000: golden = 1'b0;
      5'b11001: golden = 1'b0;
      5'b11010: golden = 1'b0;
      5'b11011: golden = 1'b0;
      5'b11100: golden = 1'b0;
      5'b11101: golden = 1'b0;
      5'b11110: golden = 1'b0;
      5'b11111: golden = 1'b1;
      default:  golden = 1'bx;
      endcase
    end
  endfunction

  // Sweep the 16 input combos with q known and constant (no clocking).
  task sweep_comb(input q_val);
    begin
      for (i = 0; i < 16; i = i + 1) begin
        {SPTN, SAPT, PONI, PTM} = i[3:0];
        #2;
        exp_selptn = golden({q_val, i[3:0]});
        checks = checks + 1;
        if (SELPTN !== exp_selptn) begin
          errors = errors + 1;
          $display("FAIL comb q=%b SPTN=%b SAPT=%b PONI=%b PTM=%b: SELPTN=%b expected %b",
                   q_val, SPTN, SAPT, PONI, PTM, SELPTN, exp_selptn);
        end
      end
    end
  endtask

  // Apply a JK combo (preset off: PTM=PONI=1) and clock once.
  task jk_pulse(input j, input k);
    begin
      PONI = 1; PTM = 1;
      SPTN = ~j;  // j = SPT = ~SPTN
      SAPT = k;
      #2;
      pulse_mclk;
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_MAC_PTSEL_tb: FPGA_FF_MODE (sysclk+MCLK_EN capture)");
`else
    $display("CGA_MAC_PTSEL_tb: latch/CP mode (posedge MCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Combinational SELPTN sweep, q=0 then q=1 (32 checks + 2
    //    steering verifications).
    // ------------------------------------------------------------------
    jk_pulse(0, 1);              // J=0 K=1: force q=0 (do not rely on init)
    check_q(1'b0, "steer q=0");
    sweep_comb(1'b0);

    jk_pulse(1, 0);              // J=1 K=0: set q=1
    check_q(1'b1, "steer q=1");
    sweep_comb(1'b1);

    // ------------------------------------------------------------------
    // 2. Directed JK sequences (9 checks). State entering here: q=1.
    // ------------------------------------------------------------------
    jk_pulse(0, 0); check_q(1'b1, "J0K0 hold from 1");
    jk_pulse(0, 1); check_q(1'b0, "J0K1 clear from 1");
    jk_pulse(0, 1); check_q(1'b0, "J0K1 clear from 0 (stays 0)");
    jk_pulse(0, 0); check_q(1'b0, "J0K0 hold from 0");
    jk_pulse(1, 0); check_q(1'b1, "J1K0 set from 0");
    jk_pulse(1, 0); check_q(1'b1, "J1K0 set from 1 (stays 1)");
    // J=K=1 is the real JK TOGGLE. Upstream (CGA_MAC_DECODE, post
    // Issue-C fix) never drives SPT and SAPT together, but the flop
    // itself must toggle - that IS the 74-series JK function.
    jk_pulse(1, 1); check_q(1'b0, "J1K1 toggle 1->0");
    jk_pulse(1, 1); check_q(1'b1, "J1K1 toggle 0->1");
    jk_pulse(1, 1); check_q(1'b0, "J1K1 toggle 1->0 again");

    // ------------------------------------------------------------------
    // 3. Preset dominance (6 checks). preset = ~(PTM & PONI); with the
    //    clear combo J=0,K=1 applied, a clock must still force q=1
    //    whenever protection is not fully on.
    // ------------------------------------------------------------------
    // PONI=0 PTM=1
    SPTN = 1; SAPT = 1; PONI = 0; PTM = 1; #2; pulse_mclk;
    check_q(1'b1, "preset PONI=0 PTM=1");
    jk_pulse(0, 1); check_q(1'b0, "re-clear after preset (a)");
    // PONI=1 PTM=0
    SPTN = 1; SAPT = 1; PONI = 1; PTM = 0; #2; pulse_mclk;
    check_q(1'b1, "preset PONI=1 PTM=0");
    jk_pulse(0, 1); check_q(1'b0, "re-clear after preset (b)");
    // PONI=0 PTM=0
    SPTN = 1; SAPT = 1; PONI = 0; PTM = 0; #2; pulse_mclk;
    check_q(1'b1, "preset PONI=0 PTM=0");
    jk_pulse(0, 1); check_q(1'b0, "re-clear after preset (c)");

    // ------------------------------------------------------------------
    // 4. Hold without clock (2 checks): set q=1, then park on the clear
    //    combination with NO MCLK event - q must not move.
    // ------------------------------------------------------------------
    jk_pulse(1, 0); check_q(1'b1, "set before no-clock hold");
    SPTN = 1; SAPT = 1; PONI = 1; PTM = 1;   // clear combo, no clock
    #40;
    check_q(1'b1, "hold without clock");

    // ------------------------------------------------------------------
    // Verdict. Expected: 2 steer + 32 sweep + 9 JK + 6 preset + 2 hold
    // = 51. A short count means part of the tb silently did not run.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == EXPECTED_CHECKS)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of %0d checks)",
               errors, checks, EXPECTED_CHECKS);
    $finish;
  end

endmodule
