/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MAC_SEGPT_XPT testbench                                           **
**                                                                       **
** Exhaustive verification of the XPT block (/CGA/MAC/SEGPT/XPT,         **
** page 38). Netlist read-out (BubblesMask decoded):                     **
**   L4 XPT_L : A=FIDBO[0]->XPT[0], B=FIDBO[1]->XPT[1],                  **
**              C=FIDBO[2]->qc/qc_n, D=0 (unused), enable L = GATES_1    **
**   GATES_1 AND mask 00 : L   = MCLKN & LLDEXM                          **
**   s_exm (inline NOT)   : exm = ~EXMN                                  **
**   GATES_2 AND mask 00 : VEX = exm & qc                                **
**   GATES_3 AND mask 00 : PEX = qc_n & exm                              **
**                                                                       **
** Checks (input space = 3 data + EXMN + 2 enables -> fully covered):    **
**  1. Exhaustive latched sweep: all 8 FIDBO[2:0] values loaded, each    **
**     read under both EXMN values; {XPT,VEX,PEX} vs a 16-entry golden   **
**     table generated by an independent Python gate model               **
**     (gen_segpt_golden.py, scratchpad only). 48 checks.                **
**  2. Transparency: latch held open, outputs follow FIDBO comb.         **
**  3. Hold: latch closed, FIDBO driven to the complement - no change.   **
**  4. Enable gating: MCLKN=1&LLDEXM=0, 0&1, 0&0 must not load.          **
**                                                                       **
** The load pulse is valid in BOTH latch builds: plain / -DFPGA_FF_MODE  **
** (L4 = mux + posedge-sysclk FF, transparent while L=1) and             **
** -DUSE_TRANSPARENT_LATCHES (true level latch). The Makefile target     **
** runs all three builds.                                                **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MAC_SEGPT_XPT_tb;

  reg        sysclk = 0;
  reg        EXMN = 1;
  reg  [2:0] FIDBO = 0;
  reg        LLDEXM = 0;
  reg        MCLKN = 0;

  wire       PEX;
  wire       VEX;
  wire [1:0] XPT;

  integer errors = 0;
  integer checks = 0;
  integer f, e;
  reg [3:0] exp4;

  localparam integer EXPECTED_CHECKS = 66;

  CGA_MAC_SEGPT_XPT dut (
      .sysclk   (sysclk),
      .sys_rst_n(1'b1),
      .EXMN     (EXMN),
      .FIDBO_2_0(FIDBO),
      .LLDEXM   (LLDEXM),
      .MCLKN    (MCLKN),
      .PEX      (PEX),
      .VEX      (VEX),
      .XPT_1_0  (XPT)
  );

  always #5 sysclk = ~sysclk;

  // One latch-load event, valid in BOTH latch builds: data stable, L
  // raised, a posedge sysclk passes (FF-mode capture), then L falls
  // (transparent-mode capture at the falling edge of L).
  task load_f(input [2:0] v);
    begin
      @(negedge sysclk);
      FIDBO  = v;
      LLDEXM = 1;
      MCLKN  = 1;
      @(posedge sysclk);
      #1 MCLKN = 0;
      LLDEXM = 0;
      #1;
    end
  endtask

  // Check all three output groups against a {XPT[1:0],VEX,PEX} nibble.
  task check_out(input [3:0] exp, input [127:0] name);
    begin
      checks = checks + 1;
      if (XPT !== exp[3:2]) begin
        errors = errors + 1;
        $display("FAIL %0s: XPT=%b expected %b", name, XPT, exp[3:2]);
      end
      checks = checks + 1;
      if (VEX !== exp[1]) begin
        errors = errors + 1;
        $display("FAIL %0s: VEX=%b expected %b", name, VEX, exp[1]);
      end
      checks = checks + 1;
      if (PEX !== exp[0]) begin
        errors = errors + 1;
        $display("FAIL %0s: PEX=%b expected %b", name, PEX, exp[0]);
      end
    end
  endtask

  // Golden table generated by the independent Python gate model
  // (gen_segpt_golden.py). Index = {EXMN, f[2:0]}, value = {XPT,VEX,PEX}.
  function [3:0] xpt_golden(input [3:0] idx);
    begin
      case (idx)
      4'b0000: xpt_golden = 4'b0001;
      4'b0001: xpt_golden = 4'b0101;
      4'b0010: xpt_golden = 4'b1001;
      4'b0011: xpt_golden = 4'b1101;
      4'b0100: xpt_golden = 4'b0010;
      4'b0101: xpt_golden = 4'b0110;
      4'b0110: xpt_golden = 4'b1010;
      4'b0111: xpt_golden = 4'b1110;
      4'b1000: xpt_golden = 4'b0000;
      4'b1001: xpt_golden = 4'b0100;
      4'b1010: xpt_golden = 4'b1000;
      4'b1011: xpt_golden = 4'b1100;
      4'b1100: xpt_golden = 4'b0000;
      4'b1101: xpt_golden = 4'b0100;
      4'b1110: xpt_golden = 4'b1000;
      4'b1111: xpt_golden = 4'b1100;
      default: xpt_golden = 4'bxxxx;
      endcase
    end
  endfunction

  initial begin
`ifdef USE_TRANSPARENT_LATCHES
    $display("CGA_MAC_SEGPT_XPT_tb: USE_TRANSPARENT_LATCHES (level latch)");
`elsif FPGA_FF_MODE
    $display("CGA_MAC_SEGPT_XPT_tb: FPGA_FF_MODE (mux + sysclk FF latch)");
`else
    $display("CGA_MAC_SEGPT_XPT_tb: plain build (mux + sysclk FF latch)");
`endif

    // ------------------------------------------------------------------
    // 1. Exhaustive latched sweep: 8 loads x 2 EXMN x 3 outputs = 48.
    // ------------------------------------------------------------------
    for (f = 0; f < 8; f = f + 1) begin
      load_f(f[2:0]);
      for (e = 0; e < 2; e = e + 1) begin
        EXMN = e[0];
        #2;
        exp4 = xpt_golden({e[0], f[2:0]});
        check_out(exp4, "latched sweep");
      end
    end

    // ------------------------------------------------------------------
    // 2. Transparency: latch open, outputs follow comb. 6 checks.
    // ------------------------------------------------------------------
    @(negedge sysclk);
    MCLKN = 1; LLDEXM = 1; EXMN = 0;
    FIDBO = 3'b111;
    #2;
    check_out(xpt_golden(4'b0111), "transparent 111");
    FIDBO = 3'b000;
    #2;
    check_out(xpt_golden(4'b0000), "transparent 000");
    MCLKN = 0; LLDEXM = 0;

    // ------------------------------------------------------------------
    // 3. Hold: load 101, drive complement with latch closed. 3 checks.
    // ------------------------------------------------------------------
    load_f(3'b101);
    FIDBO = 3'b010;
    EXMN  = 0;
    #22;
    check_out(xpt_golden(4'b0101), "hold after load 101");

    // ------------------------------------------------------------------
    // 4. Enable gating: 3 combos x 3 outputs = 9 checks.
    //    State entering here: latched value 101, EXMN=0.
    // ------------------------------------------------------------------
    @(negedge sysclk);
    MCLKN = 1; LLDEXM = 0; FIDBO = 3'b010;
    #22;
    check_out(xpt_golden(4'b0101), "gating MCLKN=1 LLDEXM=0");

    @(negedge sysclk);
    MCLKN = 0; LLDEXM = 1; FIDBO = 3'b110;
    #22;
    check_out(xpt_golden(4'b0101), "gating MCLKN=0 LLDEXM=1");

    @(negedge sysclk);
    MCLKN = 0; LLDEXM = 0; FIDBO = 3'b011;
    #22;
    check_out(xpt_golden(4'b0101), "gating MCLKN=0 LLDEXM=0");

    // ------------------------------------------------------------------
    // Verdict. Expected: 48 sweep + 6 transparent + 3 hold + 9 gating
    // = 66.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == EXPECTED_CHECKS)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of %0d checks)",
               errors, checks, EXPECTED_CHECKS);
    $finish;
  end

endmodule
