/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MAC_FASTADD testbench                                             **
**                                                                       **
** Exhaustive verification of the MAC fast address adder                 **
** (/CGA/MAC/ADD/FASTADD, page 30): two chained 8-bit Adder blocks,      **
** ARITH_1 = CD_7_0 + PRP[7:0] (carryIn=0), ARITH_2 = CDE_15_8 +         **
** PRP[15:8] + carry(ARITH_1). Independent golden model:                 **
** ADD = ({CDE_15_8,CD_7_0} + PRP_15_0) mod 65536.                       **
**                                                                       **
** The full input space is 2^32, so "exhaustive" is applied per adder    **
** stage (each stage's complete input space is covered):                 **
**  1. 24 directed edge vectors (table generated by an independent       **
**     Python model, gen_golden.py - carry chains, wraps, patterns).     **
**  2. Low stage exhaustive: all 65536 (CD_7_0 x PRP[7:0]) with          **
**     CDE=0, PRP[15:8]=0 - also proves the low carry reaches ADD[8].    **
**  3. High stage exhaustive, carry-in=0: all 65536 (CDE x PRP[15:8])    **
**     with CD=0, PRP[7:0]=0.                                            **
**  4. High stage exhaustive, carry-in=1: all 65536 (CDE x PRP[15:8])    **
**     with CD=FF, PRP[7:0]=FF (low sum 1FE -> carry=1, ADD[7:0]=FE).    **
**  5. 4096 pseudo-random full-width vectors (17-bit LFSR x 2, fixed     **
**     seeds - deterministic run).                                       **
**                                                                       **
** The module is pure combinational (no clock); the Makefile still       **
** compiles/runs it in both build modes (plain and -DFPGA_FF_MODE) for   **
** campaign uniformity.                                                  **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MAC_FASTADD_tb;

  reg [ 7:0] CDE_15_8 = 0;
  reg [ 7:0] CD_7_0 = 0;
  reg [15:0] PRP_15_0 = 0;
  wire [15:0] ADD_15_0;

  integer errors = 0;
  integer checks = 0;
  integer a, b;
  reg [16:0] lfsr_a, lfsr_b;
  integer n;
  reg [15:0] expected;

  localparam integer EXPECTED_CHECKS = 24 + 3 * 65536 + 4096;  // 200728

  CGA_MAC_FASTADD dut (
      .CDE_15_8(CDE_15_8),
      .CD_7_0  (CD_7_0),
      .PRP_15_0(PRP_15_0),
      .ADD_15_0(ADD_15_0)
  );

  // Independent model: plain 16-bit truncated addition of the concatenated
  // CDE/CD word and PRP (the DUT computes it as two chained 8-bit adders).
  function [15:0] model(input [7:0] cde, input [7:0] cd, input [15:0] prp);
    begin
      model = ({cde, cd} + prp) & 16'hFFFF;
    end
  endfunction

  task check_vec(input [7:0] cde, input [7:0] cd, input [15:0] prp,
                 input [15:0] exp);
    begin
      CDE_15_8 = cde;
      CD_7_0   = cd;
      PRP_15_0 = prp;
      #1;
      checks = checks + 1;
      if (ADD_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL: CDE=%02h CD=%02h PRP=%04h -> ADD=%04h expected %04h",
                 cde, cd, prp, ADD_15_0, exp);
      end
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_MAC_FASTADD_tb: FPGA_FF_MODE build (module is pure comb)");
`else
    $display("CGA_MAC_FASTADD_tb: plain build");
`endif

    // ------------------------------------------------------------------
    // 1. Directed edge vectors, expected values precomputed by the
    //    independent Python model (gen_golden.py).
    // ------------------------------------------------------------------
    check_vec(8'h00, 8'h00, 16'h0000, 16'h0000);
    check_vec(8'h00, 8'h01, 16'h0000, 16'h0001);
    check_vec(8'h00, 8'h00, 16'h0001, 16'h0001);
    check_vec(8'h00, 8'hFF, 16'h0001, 16'h0100);
    check_vec(8'h00, 8'h01, 16'h00FF, 16'h0100);
    check_vec(8'h00, 8'hFF, 16'h00FF, 16'h01FE);
    check_vec(8'hFF, 8'hFF, 16'h0001, 16'h0000);
    check_vec(8'hFF, 8'hFF, 16'hFFFF, 16'hFFFE);
    check_vec(8'h7F, 8'hFF, 16'h0001, 16'h8000);
    check_vec(8'h80, 8'h00, 16'h8000, 16'h0000);
    check_vec(8'hAA, 8'h55, 16'h55AA, 16'hFFFF);
    check_vec(8'h55, 8'hAA, 16'hAA55, 16'hFFFF);
    check_vec(8'h01, 8'h00, 16'hFF00, 16'h0000);
    check_vec(8'hFF, 8'h00, 16'h0100, 16'h0000);
    check_vec(8'h12, 8'h34, 16'h5678, 16'h68AC);
    check_vec(8'hDE, 8'hAD, 16'hBEEF, 16'h9D9C);
    check_vec(8'hCA, 8'hFE, 16'h0BAD, 16'hD6AB);
    check_vec(8'h00, 8'h80, 16'h0080, 16'h0100);
    check_vec(8'h80, 8'h80, 16'h8080, 16'h0100);
    check_vec(8'h3F, 8'hC0, 16'h0040, 16'h4000);
    check_vec(8'hFE, 8'h01, 16'h01FF, 16'h0000);
    check_vec(8'h0F, 8'hF0, 16'hF00F, 16'hFFFF);
    check_vec(8'hF0, 8'h0F, 16'h0FF0, 16'hFFFF);
    check_vec(8'h01, 8'hFF, 16'h00FF, 16'h02FE);

    // ------------------------------------------------------------------
    // 2. Low stage exhaustive: CD_7_0 x PRP[7:0], high inputs zero.
    // ------------------------------------------------------------------
    for (a = 0; a < 256; a = a + 1)
      for (b = 0; b < 256; b = b + 1)
        check_vec(8'h00, a[7:0], {8'h00, b[7:0]},
                  model(8'h00, a[7:0], {8'h00, b[7:0]}));

    // ------------------------------------------------------------------
    // 3. High stage exhaustive, carry-in = 0 (CD=00, PRP low=00).
    // ------------------------------------------------------------------
    for (a = 0; a < 256; a = a + 1)
      for (b = 0; b < 256; b = b + 1)
        check_vec(a[7:0], 8'h00, {b[7:0], 8'h00},
                  model(a[7:0], 8'h00, {b[7:0], 8'h00}));

    // ------------------------------------------------------------------
    // 4. High stage exhaustive, carry-in = 1 (CD=FF, PRP low=FF:
    //    low sum = 1FE, so ADD[7:0] must be FE and carry=1 into ARITH_2).
    // ------------------------------------------------------------------
    for (a = 0; a < 256; a = a + 1)
      for (b = 0; b < 256; b = b + 1)
        check_vec(a[7:0], 8'hFF, {b[7:0], 8'hFF},
                  model(a[7:0], 8'hFF, {b[7:0], 8'hFF}));

    // ------------------------------------------------------------------
    // 5. Pseudo-random full-width vectors (two fixed-seed 17-bit LFSRs,
    //    taps 17,14 - maximal length; deterministic).
    // ------------------------------------------------------------------
    lfsr_a = 17'h1ACE5;
    lfsr_b = 17'h0BEEF;
    for (n = 0; n < 4096; n = n + 1) begin
      lfsr_a = ((lfsr_a << 1) | (((lfsr_a >> 16) ^ (lfsr_a >> 13)) & 1)) & 17'h1FFFF;
      lfsr_b = ((lfsr_b << 1) | (((lfsr_b >> 16) ^ (lfsr_b >> 13)) & 1)) & 17'h1FFFF;
      check_vec(lfsr_a[7:0], lfsr_a[15:8], lfsr_b[15:0],
                model(lfsr_a[7:0], lfsr_a[15:8], lfsr_b[15:0]));
    end

    // ------------------------------------------------------------------
    // Verdict. A short count means part of the tb silently did not run.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == EXPECTED_CHECKS)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of %0d checks)",
               errors, checks, EXPECTED_CHECKS);
    $finish;
  end

endmodule
