/****************************************************************************
** Unit testbench for hex_dumper (iverilog)                                **
**                                                                         **
** Feeds a 40-byte known pattern through hex_dumper + uart_tx at a fast    **
** simulation baud rate, captures the UART output, and compares it         **
** byte-for-byte against a golden stream generated by the same format      **
** rules in behavioral code (offset lines, extra space after byte 8,       **
** octal words line, 12-digit decimal LENGTH, DONE).                       **
**                                                                         **
** Verdict: TB_RESULT: PASS / TB_RESULT: FAIL <reason>                     **
**                                                                         **
** Last reviewed: 10-JUL-2026                                              **
** Ronny Hansen                                                            **
*****************************************************************************/
`timescale 1ns / 1ps

module hex_dumper_tb;

  localparam CLK_HALF = 18.5;  // ~27 MHz
  localparam DELAY_FRAMES = 27;  // fast sim baud: 1 Mbaud at 27 MHz
  localparam ADDR_W = 16;
  localparam LEN = 40;

  reg clk = 0;
  always #CLK_HALF clk = ~clk;

  reg rst_n = 0;

  // ------------------------------------------------------- test memory
  reg [7:0] tmem[0:(1 << ADDR_W)-1];
  integer i;
  initial begin
    for (i = 0; i < LEN; i = i + 1) tmem[i] = (i * 37 + 11) & 8'hFF;
  end

  wire [ADDR_W-1:0] mem_addr;
  reg [7:0] mem_data;
  always @(posedge clk) mem_data <= tmem[mem_addr];

  // ------------------------------------------------------- DUT + UART
  reg start = 0;
  wire busy;
  wire [7:0] tx_data;
  wire tx_valid;
  wire tx_busy;
  wire txd;

  hex_dumper #(
      .ADDR_W(ADDR_W)
  ) dut (
      .clk(clk),
      .rst_n(rst_n),
      .start(start),
      .length(LEN[ADDR_W:0]),
      .busy(busy),
      .mem_addr(mem_addr),
      .mem_data(mem_data),
      .tx_data(tx_data),
      .tx_valid(tx_valid),
      .tx_busy(tx_busy)
  );

  uart_tx #(
      .DELAY_FRAMES(DELAY_FRAMES)
  ) u_tx (
      .clk(clk),
      .rst_n(rst_n),
      .tx_data(tx_data),
      .tx_valid(tx_valid),
      .tx_busy(tx_busy),
      .txd(txd)
  );

  wire [7:0] rx_data;
  wire rx_valid;
  uart_rx #(
      .DELAY_FRAMES(DELAY_FRAMES)
  ) u_rx (
      .clk(clk),
      .rst_n(rst_n),
      .rxd(txd),
      .rx_data(rx_data),
      .rx_valid(rx_valid)
  );

  // ------------------------------------------------------- capture
  reg [7:0] cap[0:8191];
  integer cap_len = 0;
  always @(posedge clk)
    if (rx_valid) begin
      cap[cap_len] = rx_data;
      cap_len = cap_len + 1;
    end

  // ------------------------------------------------------- golden stream
  reg [7:0] gold[0:8191];
  integer gold_len;

  function [7:0] hexd(input [3:0] n);
    hexd = (n < 4'd10) ? (8'h30 + {4'b0, n}) : (8'h37 + {4'b0, n});
  endfunction

  task gput(input [7:0] c);
    begin
      gold[gold_len] = c;
      gold_len = gold_len + 1;
    end
  endtask

  task gput_str(input [8*24-1:0] s, input integer len);
    integer k;
    begin
      for (k = 0; k < len; k = k + 1) gput(s[8*(len-1-k)+:8]);
    end
  endtask

  integer offs, b, w, wn, d;
  reg [23:0] o24;
  reg [15:0] word;
  reg [39:0] dv;
  integer dig;
  reg [39:0] p10[0:11];

  task build_golden;
    begin
      gold_len = 0;
      p10[0] = 1;
      for (d = 1; d < 12; d = d + 1) p10[d] = p10[d-1] * 10;

      // hex dump lines
      for (offs = 0; offs < LEN; offs = offs + 16) begin
        o24 = offs[23:0];
        for (d = 5; d >= 0; d = d - 1) gput(hexd(o24[4*d+:4]));
        gput_str(": ", 2);
        for (b = 0; b < 16 && offs + b < LEN; b = b + 1) begin
          gput(hexd(tmem[offs+b][7:4]));
          gput(hexd(tmem[offs+b][3:0]));
          gput(" ");
          if (b == 7 && offs + b + 1 < LEN) gput(" ");  // extra space mid-line
        end
        gput(8'h0D);
        gput(8'h0A);
      end

      // octal words line
      gput_str("OCTAL WORDS (FIRST 8): ", 23);
      wn = (LEN >= 16) ? 8 : LEN / 2;
      for (w = 0; w < wn; w = w + 1) begin
        word = {tmem[2*w], tmem[2*w+1]};
        gput(8'h30 + {7'b0, word[15]});
        gput(8'h30 + {5'b0, word[14:12]});
        gput(8'h30 + {5'b0, word[11:9]});
        gput(8'h30 + {5'b0, word[8:6]});
        gput(8'h30 + {5'b0, word[5:3]});
        gput(8'h30 + {5'b0, word[2:0]});
        gput(" ");
      end
      gput(8'h0D);
      gput(8'h0A);

      // LENGTH line, 12 decimal digits
      gput_str("LENGTH: ", 8);
      dv = LEN;
      for (d = 11; d >= 0; d = d - 1) begin
        dig = 0;
        while (dv >= p10[d]) begin
          dv  = dv - p10[d];
          dig = dig + 1;
        end
        gput(8'h30 + dig[7:0]);
      end
      gput_str(" BYTES", 6);
      gput(8'h0D);
      gput(8'h0A);

      gput_str("DONE", 4);
      gput(8'h0D);
      gput(8'h0A);
    end
  endtask

  // ------------------------------------------------------- run
  integer errors;
  initial begin
    build_golden;

    repeat (10) @(posedge clk);
    rst_n = 1;
    repeat (10) @(posedge clk);

    start <= 1;
    @(posedge clk);
    start <= 0;

    // wait for completion: all golden bytes received (or timeout)
    begin : wait_done
      integer guard;
      guard = 0;
      while (cap_len < gold_len && guard < 20_000_000) begin
        @(posedge clk);
        guard = guard + 1;
      end
    end
    // let any excess bytes trickle in
    repeat (200 * DELAY_FRAMES) @(posedge clk);

    errors = 0;
    if (cap_len != gold_len) begin
      $display("length mismatch: captured %0d, golden %0d", cap_len, gold_len);
      errors = errors + 1;
    end
    for (i = 0; i < gold_len && i < cap_len; i = i + 1) begin
      if (cap[i] !== gold[i]) begin
        if (errors < 10)
          $display("byte %0d: got %02x ('%c'), want %02x ('%c')", i, cap[i], cap[i], gold[i],
                   gold[i]);
        errors = errors + 1;
      end
    end

    if (errors == 0) $display("TB_RESULT: PASS");
    else $display("TB_RESULT: FAIL %0d mismatches", errors);
    $finish;
  end

endmodule
