# ---------------------------------------------------------------------------
# Nexys 4 DDR - pins for the console on the board's own screen and keyboard
#
# Read ONLY when build.tcl is given -tclargs vgaconsole, together with the
# ND120_CONSOLE_VGA define. Without it these ports do not exist on the top
# level and the default bitstream is unchanged.
#
# Every pin below was taken from this board's own master constraints file,
# Nexys-4-DDR-Master.xdc, not from a datasheet or from memory:
#   VGA connector    lines 156-172
#   USB HID (PS/2)   lines 226-227, in the section headed "##USB HID (PS/2)"
#
# The VGA output is a 4-bit-per-colour resistor ladder, so 12-bit colour. A
# text terminal uses two of those 4096 colours.
#
# The PS/2 pair comes from the on-board microcontroller acting as the USB
# host - a USB keyboard therefore costs a PS/2 receiver, not a USB stack.
# We only ever read it, so both are inputs with pull-ups; the keyboard is an
# open-collector device and needs them.
#
# Plan: PLAN-vga-console.md
# Written 27-AUG-2026
# ---------------------------------------------------------------------------

## VGA connector - red
set_property -dict { PACKAGE_PIN A3  IOSTANDARD LVCMOS33 } [get_ports { vga_r[0] }]
set_property -dict { PACKAGE_PIN B4  IOSTANDARD LVCMOS33 } [get_ports { vga_r[1] }]
set_property -dict { PACKAGE_PIN C5  IOSTANDARD LVCMOS33 } [get_ports { vga_r[2] }]
set_property -dict { PACKAGE_PIN A4  IOSTANDARD LVCMOS33 } [get_ports { vga_r[3] }]

## VGA connector - green
set_property -dict { PACKAGE_PIN C6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[0] }]
set_property -dict { PACKAGE_PIN A5  IOSTANDARD LVCMOS33 } [get_ports { vga_g[1] }]
set_property -dict { PACKAGE_PIN B6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[2] }]
set_property -dict { PACKAGE_PIN A6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[3] }]

## VGA connector - blue
set_property -dict { PACKAGE_PIN B7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[0] }]
set_property -dict { PACKAGE_PIN C7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[1] }]
set_property -dict { PACKAGE_PIN D7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[2] }]
set_property -dict { PACKAGE_PIN D8  IOSTANDARD LVCMOS33 } [get_ports { vga_b[3] }]

## VGA sync
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports { vga_hs }]
set_property -dict { PACKAGE_PIN B12 IOSTANDARD LVCMOS33 } [get_ports { vga_vs }]

## USB HID (PS/2) - keyboard, receive only
set_property -dict { PACKAGE_PIN F4  IOSTANDARD LVCMOS33 PULLUP true } [get_ports { ps2_clk }]
set_property -dict { PACKAGE_PIN B2  IOSTANDARD LVCMOS33 PULLUP true } [get_ports { ps2_data }]

# ---------------------------------------------------------------------------
# Timing
#
# The pixel domain is generated by the same MMCM as the CPU and storage
# clocks, so Vivado already knows it. It is asynchronous to all of them: the
# only paths that cross are the console byte (a toggle handshake inside
# cdc_byte.v) and the serial lines, which are asynchronous by nature.
#
# THE POINT OF THIS: this board's 45.45 MHz was hard-won and the critical
# path is the CPU microcycle. Declaring the groups asynchronous keeps the
# timer from trying to close a path that does not need closing - and keeps
# the terminal from appearing in, or damaging, the CPU's timing report.
# Re-read the post-route report after building this anyway. Do not assume a
# "small" block is free on a board with this little margin.
# ---------------------------------------------------------------------------

# THE TWO PIXEL CLOCKS ARE MUTUALLY EXCLUSIVE (28-AUG-2026).
#
# sw[2] selects between them through a BUFGMUX_CTRL, so only one ever reaches
# the console. Without saying so, the timer sees the same registers reachable
# from both clocks and analyses crossings BETWEEN them - and with no sensible
# phase relationship between the two it invents brutal requirements:
#
#   Source: TERMINAL/.../s_vcount_reg[3]  (clk_pix_pre,  25.000 ns)
#   Dest:   TERMINAL/.../PANELFONT        (clk_pix2_pre,  6.737 ns)
#   Requirement: 0.053ns   Slack: -10.103ns
#
# A 53-picosecond requirement is not a real constraint, it is the timer being
# asked an impossible question. -physically_exclusive is the documented answer
# for a clock mux: those paths exist in no configuration of the hardware.
set_clock_groups -physically_exclusive \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT3]] \
    -group [get_clocks -of_objects [get_pins mmcm_video/CLKOUT0]]

# The video clocks are asynchronous to the CPU and storage domains. The 148 MHz
# clock was missing from this list entirely, which produced the worst path of
# the first panel build:
#
#   Source: CORE/.../WCS/CHIP_22C  (clk_cpu_pre,  60.000 ns)
#   Dest:   TERMINAL/.../PANELFONT (clk_pix2_pre,  6.737 ns)
#   Requirement: 0.211ns   Slack: -14.762ns
#
# The only real crossings are the console byte - a toggle handshake in
# cdc_byte.v - and the serial lines, which are asynchronous by nature.
#
# NO BRACES around a -group list. TCL braces prevent command substitution, so
# `-group {[get_clocks ...] [get_clocks ...]}` passes the text literally and
# Vivado goes looking for a clock actually named "[get_clocks". It does not
# error - it WARNS, and carries on with the constraint doing nothing:
#
#   WARNING: [Vivado 12-646] clock '[get_clocks' not found.
#   WARNING: [Vivado 12-646] clock 'mmcm/CLKOUT3]]' not found.
#
# The build then completes and reports a timing number that means nothing.
# Each clock gets its own -group instead, which needs no grouping syntax at
# all. If this file is ever edited, grep the build log for "12-646" - a
# constraint that silently does nothing is worse than one that fails loudly.
set_clock_groups -asynchronous \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT3]] \
    -group [get_clocks -of_objects [get_pins mmcm_video/CLKOUT0]] \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT0]] \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT1]]

# The PS/2 lines are asynchronous and slow (10-16.7 kHz); the receiver
# synchronizes and filters them. Nothing to time.
set_false_path -from [get_ports { ps2_clk ps2_data }]

# The VGA outputs drive a resistor ladder into a monitor. There is no setup
# relationship to constrain - the monitor recovers its own timing from the
# sync pulses.
set_false_path -to [get_ports { vga_r[*] vga_g[*] vga_b[*] vga_hs vga_vs }]
