# ---------------------------------------------------------------------------
# Nexys 4 DDR - pins for the console on the board's own screen and keyboard
#
# Read ONLY when build.tcl is given -tclargs vgaconsole, together with the
# ND120_CONSOLE_VGA define. Without it these ports do not exist on the top
# level and the default bitstream is unchanged.
#
# Every pin below was taken from this board's own master constraints file,
# Nexys-4-DDR-Master.xdc, not from a datasheet or from memory:
#   VGA connector    lines 156-172
#   USB HID (PS/2)   lines 226-227, in the section headed "##USB HID (PS/2)"
#
# The VGA output is a 4-bit-per-colour resistor ladder, so 12-bit colour. A
# text terminal uses two of those 4096 colours.
#
# The PS/2 pair comes from the on-board microcontroller acting as the USB
# host - a USB keyboard therefore costs a PS/2 receiver, not a USB stack.
# We only ever read it, so both are inputs with pull-ups; the keyboard is an
# open-collector device and needs them.
#
# Plan: PLAN-vga-console.md
# Written 27-AUG-2026
# ---------------------------------------------------------------------------

## VGA connector - red
set_property -dict { PACKAGE_PIN A3  IOSTANDARD LVCMOS33 } [get_ports { vga_r[0] }]
set_property -dict { PACKAGE_PIN B4  IOSTANDARD LVCMOS33 } [get_ports { vga_r[1] }]
set_property -dict { PACKAGE_PIN C5  IOSTANDARD LVCMOS33 } [get_ports { vga_r[2] }]
set_property -dict { PACKAGE_PIN A4  IOSTANDARD LVCMOS33 } [get_ports { vga_r[3] }]

## VGA connector - green
set_property -dict { PACKAGE_PIN C6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[0] }]
set_property -dict { PACKAGE_PIN A5  IOSTANDARD LVCMOS33 } [get_ports { vga_g[1] }]
set_property -dict { PACKAGE_PIN B6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[2] }]
set_property -dict { PACKAGE_PIN A6  IOSTANDARD LVCMOS33 } [get_ports { vga_g[3] }]

## VGA connector - blue
set_property -dict { PACKAGE_PIN B7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[0] }]
set_property -dict { PACKAGE_PIN C7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[1] }]
set_property -dict { PACKAGE_PIN D7  IOSTANDARD LVCMOS33 } [get_ports { vga_b[2] }]
set_property -dict { PACKAGE_PIN D8  IOSTANDARD LVCMOS33 } [get_ports { vga_b[3] }]

## VGA sync
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports { vga_hs }]
set_property -dict { PACKAGE_PIN B12 IOSTANDARD LVCMOS33 } [get_ports { vga_vs }]

## USB HID (PS/2) - keyboard, receive only
set_property -dict { PACKAGE_PIN F4  IOSTANDARD LVCMOS33 PULLUP true } [get_ports { ps2_clk }]
set_property -dict { PACKAGE_PIN B2  IOSTANDARD LVCMOS33 PULLUP true } [get_ports { ps2_data }]

# ---------------------------------------------------------------------------
# Timing
#
# The pixel domain is generated by the same MMCM as the CPU and storage
# clocks, so Vivado already knows it. It is asynchronous to all of them: the
# only paths that cross are the console byte (a toggle handshake inside
# cdc_byte.v) and the serial lines, which are asynchronous by nature.
#
# THE POINT OF THIS: this board's 45.45 MHz was hard-won and the critical
# path is the CPU microcycle. Declaring the groups asynchronous keeps the
# timer from trying to close a path that does not need closing - and keeps
# the terminal from appearing in, or damaging, the CPU's timing report.
# Re-read the post-route report after building this anyway. Do not assume a
# "small" block is free on a board with this little margin.
# ---------------------------------------------------------------------------

set_clock_groups -asynchronous \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT3]] \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT0]] \
    -group [get_clocks -of_objects [get_pins mmcm/CLKOUT1]]

# The PS/2 lines are asynchronous and slow (10-16.7 kHz); the receiver
# synchronizes and filters them. Nothing to time.
set_false_path -from [get_ports { ps2_clk ps2_data }]

# The VGA outputs drive a resistor ladder into a monitor. There is no setup
# relationship to constrain - the monitor recovers its own timing from the
# sync pulses.
set_false_path -to [get_ports { vga_r[*] vga_g[*] vga_b[*] vga_hs vga_vs }]
