## ND-120 for MEGA65 (nd-120, Verilog/fpga/mega65)
##
## Core specific constraints
##
## Powered by MiSTer2MEGA65 (GPL v3, the m2m/ submodule). This file started as
## the framework's CORE/CORE.xdc template.


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
# ND-120 (02-SEP-2026): the machine's other two clocks from the same MMCM
# (CORE/vhdl/clk.vhd): the CPU at 20 MHz and the SDRAM chip clock at 40 MHz,
# 180 degrees. build.tcl bounds the crossings from cpu_clk to the framework's
# qnice_clk and hr_clk after synthesis (set_max_delay -datapath_only).
create_generated_clock -name cpu_clk       [get_pins CORE/clk_gen/i_clk_main/CLKOUT1]
create_generated_clock -name sdram_clk     [get_pins CORE/clk_gen/i_clk_main/CLKOUT2]


## ---------------------------------------------------------------------------
## Vivado 2026.1 repair for the framework's ascal reset false path
## ---------------------------------------------------------------------------
## m2m/M2M/common.xdc:122 says
##     set_false_path -through [get_pins .../i_ascal/reset_na]
## - every path through the scaler's reset input is asynchronous by design
## (ascal.vhd re-synchronises reset_na inside each of its three clock domains).
## Under Vivado 2026.1 that hierarchical pin no longer exists after synthesis
## (WHY it is gone is not verified; the timed path shows one LUT2 between the
## synchroniser output and the register), so the framework's line matches
## nothing ("[Vivado 12-4739] No valid object(s)") and the same paths
## get timed as recovery checks: 8 endpoints, WNS -6.370 ns, from the outputs
## of the two xpm_cdc_async_rst synchronisers (hr and main) into the three
## per-domain reset registers of the ascal. Measured 02-SEP-2026, B0 run 4.
## This says the same thing against the objects 2026.1 keeps: the async
## CLR/PRE pins of those three registers.
set_false_path -to [get_pins -hierarchical -regexp {.*/i_ascal/(i|o|avl)_reset_na_reg/(CLR|PRE)}]

## ---------------------------------------------------------------------------
## Hold analysis artefact on the framework's video clock divider
## ---------------------------------------------------------------------------
## m2m/M2M/common.xdc defines div_clk as a generated clock ON THE Q PIN of
## i_framework/i_video_out_clock/clki_div_reg (a divide-by-2 toggle flop).
## That flop's own Q -> D feedback is then timed as a div_clk -> clk path,
## with the clock network delay to the flop counted once as "skew" (0.87 ns
## measured 02-SEP-2026), and the router cannot pad a path that short enough
## (WHS -0.675 ns, 2 endpoints, both this feedback). Physically launch and
## capture happen on the same clock pin of the same flop: skew is zero and
## 0.4 ns of data delay meets hold. Hold-only, this one feedback only.
## The path STARTS at the Q pin (div_clk is defined there), so -from names Q,
## not C - a -from on C matched a real pin and silently covered nothing.
set_false_path -hold -from [get_pins -hierarchical -filter {NAME =~ *i_video_out_clock/clki_div_reg/Q}] \
                     -to   [get_pins -hierarchical -filter {NAME =~ *i_video_out_clock/clki_div_reg/D}]

## Router-vs-sign-off hold gap on the framework's 100 MHz clk. Measured twice
## on 02-SEP-2026 (R6 full builds): route_design's own hold summary said
## +0.053 / +0.050 ns where the sign-off report said -0.491 / -0.021 ns, on
## paths inside i_video_out_clock (its MMCM DRP registers). The router pads
## hold to ITS estimate, so a sign-off miss of tens of ps survives every
## hold-fix pass. 100 ps of hold uncertainty on clk makes the router aim past
## the gap; setup analysis is untouched (-hold only).
set_clock_uncertainty -hold 0.100 [get_clocks clk]
