/**************************************************************************
** ND120 CPU - unit test                                                 **
** MEM_RAMC_50: local RAM control sheet (sheet 50) - PAL_44803A RAM      **
** arbiter (5F) cross-coupled with the PAL_44902A RAM-control state      **
** machine (6F), both clocked by OSC.                                    **
**                                                                       **
** Golden behavior comes from the INDEPENDENT Python model               **
** gen_ramc_golden.py (scratchpad, not in repo), which re-transcribes    **
** the two PALs' registered equations plus the sheet cross-wiring        **
** (44803A.LOEN_n <- 44902A LOEN_n pin, 44902A.RGNT_n <- 44803A RGNT_n   **
** pin) and emits the embedded tables/constants below.                   **
**                                                                       **
**  1. Directed phase (75 cycles, per-cycle full 11-output compare):     **
**     reset, CPU grant walk, bus grant walk, refresh priority, the      **
**     LDR "CPU after last-done-refresh" path, and the CSEM semaphore    **
**     hold. CGNT25_n/BGNT25_n are driven as 1-OSC-delayed copies of     **
**     the DUT's own CGNT_n/BGNT_n (board behavior on sheet 48).         **
**  2. LFSR phase (2000 cycles, fixed seed ACE1ACE1): random inputs      **
**     (MR_n low 1/8 of the time); per cycle the one-hot grant           **
**     invariant is asserted and all 11 outputs are folded into a        **
**     running checksum acc = acc*31 + out, compared at the end.         **
**  3. PD comb checks: PD1=1 forces the 44803A grant pins to 0, PD3=1    **
**     forces the 44902A strobe pins to 0 (FPGA no-Z convention).        **
**                                                                       **
** The PAL registers have no initializer, so the tb DEPOSITS 0 into all  **
** 16 state registers at t0 (hierarchical refs, sim-only); the Python    **
** model starts from the same all-zero state.                            **
**                                                                       **
** No ifdef build split applies (no VERILATOR_SIM / FPGA_FF_MODE /       **
** USE_TRANSPARENT_LATCHES branch in the DUT or in these two PALs) -     **
** single iverilog build, posedge-CK PAL semantics as on the FPGA and    **
** in Verilator.                                                         **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** Run: make test-ramc   (CPU-BOARD-3202/circuit/sim)                    **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module MEM_RAMC_50_tb;

  // osc starts HIGH so the first posedge comes only after the first
  // do_cycle input setup (no stray clock before the directed phase).
  reg osc = 1;

  reg bdap50_n = 1;
  reg bdry50_n = 1;
  reg bgnt25_n = 1;
  reg blrq50_n = 1;
  reg cgnt25_n = 1;
  reg clrq_n = 1;
  reg mr_n = 1;
  reg pd1 = 0;
  reg pd3 = 0;
  reg rlrq_n = 1;
  reg semrq50_n = 1;
  reg ssema_n = 1;

  wire bcgnt25, bgnt_n, ras, cas, cgnt_n, hien_n, loen_n, qd_n, rgnt_n;
  wire led_cpu_gi, led_bus_gi;

  MEM_RAMC_50 dut (
      .BDAP50_n (bdap50_n),
      .BDRY50_n (bdry50_n),
      .BGNT25_n (bgnt25_n),
      .BLRQ50_n (blrq50_n),
      .CGNT25_n (cgnt25_n),
      .CLRQ_n   (clrq_n),
      .MR_n     (mr_n),
      .OSC      (osc),
      .PD1      (pd1),
      .PD3      (pd3),
      .RLRQ_n   (rlrq_n),
      .SEMRQ50_n(semrq50_n),
      .SSEMA_n  (ssema_n),
      .MEM_HOLD (1'b0),

      .BCGNT25   (bcgnt25),
      .BGNT_n    (bgnt_n),
      .RAS       (ras),
      .CAS       (cas),
      .CGNT_n    (cgnt_n),
      .HIEN_n    (hien_n),
      .LOEN_n    (loen_n),
      .QD_n      (qd_n),
      .RGNT_n    (rgnt_n),
      .LED_CPU_GI(led_cpu_gi),
      .LED_BUS_GI(led_bus_gi)
  );

  // packed 11-bit output word, LSB first - must match gen_ramc_golden.py
  wire [10:0] outword = {led_bus_gi, led_cpu_gi, rgnt_n, qd_n, loen_n,
                         hien_n, cgnt_n, cas, ras, bgnt_n, bcgnt25};

  integer errors = 0;
  integer checks = 0;
  integer k;
  reg [31:0] acc = 0;
  reg [31:0] lfsr = 32'hACE1ACE1;
  reg [9:0]  dir_in [0:74];
  reg [10:0] dir_out[0:74];
  reg [9:0]  iw;
  reg [31:0] b;
  integer grants;

  // Directed tables generated by gen_ramc_golden.py.
  initial begin
    dir_in[  0] = 10'h3DF; dir_out[  0] = 11'h7BE;
    dir_in[  1] = 10'h3DF; dir_out[  1] = 11'h7FA;
    dir_in[  2] = 10'h3DF; dir_out[  2] = 11'h7DA;
    dir_in[  3] = 10'h3FF; dir_out[  3] = 11'h752;
    dir_in[  4] = 10'h3FF; dir_out[  4] = 11'h752;
    dir_in[  5] = 10'h3FD; dir_out[  5] = 11'h542;
    dir_in[  6] = 10'h3FD; dir_out[  6] = 11'h543;
    dir_in[  7] = 10'h1FD; dir_out[  7] = 11'h543;
    dir_in[  8] = 10'h1FD; dir_out[  8] = 11'h547;
    dir_in[  9] = 10'h1FD; dir_out[  9] = 11'h527;
    dir_in[ 10] = 10'h1FD; dir_out[ 10] = 11'h52F;
    dir_in[ 11] = 10'h1FD; dir_out[ 11] = 11'h5AF;
    dir_in[ 12] = 10'h1FD; dir_out[ 12] = 11'h5AF;
    dir_in[ 13] = 10'h1FD; dir_out[ 13] = 11'h5EB;
    dir_in[ 14] = 10'h1FD; dir_out[ 14] = 11'h7DB;
    dir_in[ 15] = 10'h1FF; dir_out[ 15] = 11'h752;
    dir_in[ 16] = 10'h3FF; dir_out[ 16] = 11'h752;
    dir_in[ 17] = 10'h3FF; dir_out[ 17] = 11'h752;
    dir_in[ 18] = 10'h3FB; dir_out[ 18] = 11'h350;
    dir_in[ 19] = 10'h3FB; dir_out[ 19] = 11'h351;
    dir_in[ 20] = 10'h2FB; dir_out[ 20] = 11'h351;
    dir_in[ 21] = 10'h2FB; dir_out[ 21] = 11'h355;
    dir_in[ 22] = 10'h2FB; dir_out[ 22] = 11'h335;
    dir_in[ 23] = 10'h2FB; dir_out[ 23] = 11'h335;
    dir_in[ 24] = 10'h2FB; dir_out[ 24] = 11'h335;
    dir_in[ 25] = 10'h2FB; dir_out[ 25] = 11'h335;
    dir_in[ 26] = 10'h2FB; dir_out[ 26] = 11'h335;
    dir_in[ 27] = 10'h2FB; dir_out[ 27] = 11'h335;
    dir_in[ 28] = 10'h2FF; dir_out[ 28] = 11'h335;
    dir_in[ 29] = 10'h2FF; dir_out[ 29] = 11'h335;
    dir_in[ 30] = 10'h2FF; dir_out[ 30] = 11'h335;
    dir_in[ 31] = 10'h2FE; dir_out[ 31] = 11'h335;
    dir_in[ 32] = 10'h2FE; dir_out[ 32] = 11'h335;
    dir_in[ 33] = 10'h2FE; dir_out[ 33] = 11'h335;
    dir_in[ 34] = 10'h2FE; dir_out[ 34] = 11'h335;
    dir_in[ 35] = 10'h2FE; dir_out[ 35] = 11'h335;
    dir_in[ 36] = 10'h2FE; dir_out[ 36] = 11'h335;
    dir_in[ 37] = 10'h2FE; dir_out[ 37] = 11'h335;
    dir_in[ 38] = 10'h2FE; dir_out[ 38] = 11'h335;
    dir_in[ 39] = 10'h2FF; dir_out[ 39] = 11'h335;
    dir_in[ 40] = 10'h2FF; dir_out[ 40] = 11'h335;
    dir_in[ 41] = 10'h2FF; dir_out[ 41] = 11'h335;
    dir_in[ 42] = 10'h2FE; dir_out[ 42] = 11'h335;
    dir_in[ 43] = 10'h2FC; dir_out[ 43] = 11'h335;
    dir_in[ 44] = 10'h2FC; dir_out[ 44] = 11'h335;
    dir_in[ 45] = 10'h2FC; dir_out[ 45] = 11'h335;
    dir_in[ 46] = 10'h2FC; dir_out[ 46] = 11'h335;
    dir_in[ 47] = 10'h2FC; dir_out[ 47] = 11'h335;
    dir_in[ 48] = 10'h2FC; dir_out[ 48] = 11'h335;
    dir_in[ 49] = 10'h2FD; dir_out[ 49] = 11'h335;
    dir_in[ 50] = 10'h2FD; dir_out[ 50] = 11'h335;
    dir_in[ 51] = 10'h2FD; dir_out[ 51] = 11'h335;
    dir_in[ 52] = 10'h2FD; dir_out[ 52] = 11'h335;
    dir_in[ 53] = 10'h2FD; dir_out[ 53] = 11'h335;
    dir_in[ 54] = 10'h2FD; dir_out[ 54] = 11'h335;
    dir_in[ 55] = 10'h2FD; dir_out[ 55] = 11'h335;
    dir_in[ 56] = 10'h2FD; dir_out[ 56] = 11'h335;
    dir_in[ 57] = 10'h2FF; dir_out[ 57] = 11'h335;
    dir_in[ 58] = 10'h2FF; dir_out[ 58] = 11'h335;
    dir_in[ 59] = 10'h2FF; dir_out[ 59] = 11'h335;
    dir_in[ 60] = 10'h2FF; dir_out[ 60] = 11'h335;
    dir_in[ 61] = 10'h2F5; dir_out[ 61] = 11'h335;
    dir_in[ 62] = 10'h2F5; dir_out[ 62] = 11'h335;
    dir_in[ 63] = 10'h2F5; dir_out[ 63] = 11'h335;
    dir_in[ 64] = 10'h2F5; dir_out[ 64] = 11'h335;
    dir_in[ 65] = 10'h2F5; dir_out[ 65] = 11'h335;
    dir_in[ 66] = 10'h2F5; dir_out[ 66] = 11'h335;
    dir_in[ 67] = 10'h2F5; dir_out[ 67] = 11'h335;
    dir_in[ 68] = 10'h2F5; dir_out[ 68] = 11'h335;
    dir_in[ 69] = 10'h2F5; dir_out[ 69] = 11'h335;
    dir_in[ 70] = 10'h2F5; dir_out[ 70] = 11'h335;
    dir_in[ 71] = 10'h2FF; dir_out[ 71] = 11'h335;
    dir_in[ 72] = 10'h2FF; dir_out[ 72] = 11'h335;
    dir_in[ 73] = 10'h2FF; dir_out[ 73] = 11'h335;
    dir_in[ 74] = 10'h2FF; dir_out[ 74] = 11'h335;
  end

  // one OSC cycle: inputs set at negedge, PALs clock at posedge, sample #1
  task do_cycle;
    begin
      @(negedge osc);
      rlrq_n    = iw[0];
      clrq_n    = iw[1];
      blrq50_n  = iw[2];
      ssema_n   = iw[3];
      semrq50_n = iw[4];
      mr_n      = iw[5];
      bdap50_n  = iw[6];
      bdry50_n  = iw[7];
      bgnt25_n  = iw[8];
      cgnt25_n  = iw[9];
      @(posedge osc);
      #1;
    end
  endtask

  always #5 osc = ~osc;

  initial begin
    // Deposit all-zero PAL state (registers have no initializer; the
    // Python model starts from the same all-zero state).
    dut.PAL_44803_URAMA.RGNT_reg = 0;
    dut.PAL_44803_URAMA.CGNT_reg = 0;
    dut.PAL_44803_URAMA.BGNT_reg = 0;
    dut.PAL_44803_URAMA.LDR_reg = 0;
    dut.PAL_44803_URAMA.CSEM_reg = 0;
    dut.PAL_44803_URAMA.BSEM_reg = 0;
    dut.PAL_44803_URAMA.LOEN25_reg = 0;
    dut.PAL_44803_URAMA.BCGNT25_n_reg = 0;
    dut.PAL_44902_URAMC.QA_reg = 0;
    dut.PAL_44902_URAMC.QB_reg = 0;
    dut.PAL_44902_URAMC.QC_reg = 0;
    dut.PAL_44902_URAMC.QD_reg = 0;
    dut.PAL_44902_URAMC.RAS_n_reg = 0;
    dut.PAL_44902_URAMC.CAS_n_reg = 0;
    dut.PAL_44902_URAMC.LOEN_reg = 0;
    dut.PAL_44902_URAMC.HIEN_reg = 0;

    // ---- 1. directed phase ----
    for (k = 0; k < 75; k = k + 1) begin
      iw = dir_in[k];
      do_cycle;
      checks = checks + 1;
      if (outword !== dir_out[k]) begin
        errors = errors + 1;
        $display("FAIL dir[%0d]: in=%03h got out=%03h expected %03h",
                 k, iw, outword, dir_out[k]);
      end
    end

    // ---- 2. LFSR phase ----
    for (k = 0; k < 2000; k = k + 1) begin
      lfsr = (lfsr >> 1) ^ (lfsr[0] ? 32'hEDB88320 : 32'h0);
      b = lfsr;
      iw = {b[8], b[7], b[6], b[5],
            (b[11:9] == 3'b000) ? 1'b0 : 1'b1,
            b[4], b[3], b[2], b[1], b[0]};
      do_cycle;
      // one-hot grant invariant
      grants = (rgnt_n ? 0 : 1) + (cgnt_n ? 0 : 1) + (bgnt_n ? 0 : 1);
      checks = checks + 1;
      if (grants > 1) begin
        errors = errors + 1;
        $display("FAIL invariant cycle %0d: %0d grants asserted", k, grants);
      end
      acc = (acc << 5) - acc + {21'b0, outword};
    end

    checks = checks + 1;
    if (acc !== 32'h1CE85BBA) begin
      errors = errors + 1;
      $display("FAIL checksum: got %08h expected 1CE85BBA", acc);
    end

    // ---- 3. PD tri-state comb checks (no clock) ----
    pd1 = 1;
    #2;
    checks = checks + 1;
    if ({rgnt_n, cgnt_n, bgnt_n, bcgnt25} !== 4'b0000) begin
      errors = errors + 1;
      $display("FAIL PD1: grant pins not forced 0: %b",
               {rgnt_n, cgnt_n, bgnt_n, bcgnt25});
    end
    pd3 = 1;
    #2;
    checks = checks + 1;
    if ({qd_n, ras, cas, loen_n, hien_n} !== 5'b00000) begin
      errors = errors + 1;
      $display("FAIL PD3: strobe pins not forced 0: %b",
               {qd_n, ras, cas, loen_n, hien_n});
    end

    // Verdict. Expected: 75 + 2000 + 1 + 2 = 2078.
    if (errors == 0 && checks == 2078)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 2078 checks)",
               errors, checks);
    $finish;
  end

endmodule
