/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_RALU_MUX216L testbench                                        **
**                                                                       **
** Verification of the 16-bit inverting 2:1 mux. Full input space is     **
** 2^33 (F,T,S) - too large to sweep, so the coverage is split:          **
**                                                                       **
**  1. Directed golden vectors (8, generated by the independent Python   **
**     model gen_alu_golden.py) with explicit expected constants.        **
**  2. Per-slice exhaustive: the module is 16 identical MUX21LP slices   **
**     sharing only s_s_n. For each slice i, all 8 {S,F[i],T[i]} combos  **
**     are applied on an all-zeros background AND on an all-ones         **
**     background, checking the FULL 16-bit output each time (proves     **
**     slice equivalence and catches cross-slice wiring swaps).          **
**     16 slices x 8 combos x 2 backgrounds = 256 checks.                **
**  3. Full-width fixed-seed LFSR vectors: 4096 random {F,T} pairs       **
**     (32-bit Fibonacci LFSR, taps 32/22/2/1, seed ACE12026, identical  **
**     code in gen_alu_golden.py) with S alternating, checked against    **
**     the independent model O = S ? ~F : ~T. Model derivation, read     **
**     gate-by-gate: MUX21LP ZN = ~(sel ? B : A) with sel = s_s_n = ~S,  **
**     A = F[i], B = T[i], so O[i] = ~(~S ? T[i] : F[i]) = S?~F[i]:~T[i].**
**                                                                       **
** Pure combinational module (MUX21LP/Multiplexer_2 are assign-only, no  **
** FF/latch primitives) - a single build mode covers it.                 **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_RALU_MUX216L_tb;

  reg  [15:0] F_15_0 = 0;
  reg         S = 0;
  reg  [15:0] T_15_0 = 0;
  wire [15:0] O_15_0;

  integer errors = 0;
  integer checks = 0;
  integer i, c, k;
  reg [31:0] lfsr;
  reg        fb;
  reg [15:0] exp;

  CGA_ALU_RALU_MUX216L dut (
      .F_15_0(F_15_0),
      .S     (S),
      .T_15_0(T_15_0),
      .O_15_0(O_15_0)
  );

  // Independent model: O = S ? ~F : ~T (derived from the gate netlist).
  function [15:0] model(input s_in, input [15:0] f_in, input [15:0] t_in);
    begin
      model = s_in ? ~f_in : ~t_in;
    end
  endfunction

  task check(input [255:0] name);
    begin
      #1;
      checks = checks + 1;
      exp = model(S, F_15_0, T_15_0);
      if (O_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: S=%b F=%04h T=%04h got O=%04h expected %04h",
                 name, S, F_15_0, T_15_0, O_15_0, exp);
      end
    end
  endtask

  task dir_vec(input s_in, input [15:0] f_in, input [15:0] t_in,
               input [15:0] e_in);
    begin
      S = s_in; F_15_0 = f_in; T_15_0 = t_in;
      #1;
      checks = checks + 1;
      if (O_15_0 !== e_in) begin
        errors = errors + 1;
        $display("FAIL dir: S=%b F=%04h T=%04h got O=%04h expected %04h",
                 s_in, f_in, t_in, O_15_0, e_in);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_golden.py.
    // ------------------------------------------------------------------
      dir_vec(1'b0, 16'h0000, 16'h0000, 16'hFFFF);
      dir_vec(1'b0, 16'hFFFF, 16'h0000, 16'hFFFF);
      dir_vec(1'b0, 16'h0000, 16'hFFFF, 16'h0000);
      dir_vec(1'b1, 16'h0000, 16'h0000, 16'hFFFF);
      dir_vec(1'b1, 16'hFFFF, 16'h0000, 16'h0000);
      dir_vec(1'b1, 16'h0000, 16'hFFFF, 16'hFFFF);
      dir_vec(1'b0, 16'h1234, 16'hA5C3, 16'h5A3C);
      dir_vec(1'b1, 16'h1234, 16'hA5C3, 16'hEDCB);

    // ------------------------------------------------------------------
    // 2. Per-slice exhaustive, both backgrounds, full-width check.
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      for (c = 0; c < 8; c = c + 1) begin
        // background all zeros
        S = c[2];
        F_15_0 = {15'h0000, c[1]} << i;
        T_15_0 = {15'h0000, c[0]} << i;
        check("slice-bg0");
        // background all ones
        S = c[2];
        F_15_0 = ~(({15'h0000, ~c[1]}) << i);
        T_15_0 = ~(({15'h0000, ~c[0]}) << i);
        check("slice-bg1");
      end
    end

    // ------------------------------------------------------------------
    // 3. 4096 fixed-seed LFSR full-width vectors.
    // ------------------------------------------------------------------
    lfsr = 32'hACE12026;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      S      = k[0];
      F_15_0 = lfsr[31:16];
      T_15_0 = lfsr[15:0];
      check("lfsr");
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 8 directed + 256 slice + 4096 LFSR = 4360.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4360)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4360 checks)",
               errors, checks);
    $finish;
  end

endmodule
