/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_CPU_ALU_OUTMUX_SEL7 testbench                                     **
**                                                                       **
** Exhaustive verification of the 7-way select/detect tree:              **
** all 16384 {SI[6:0],E[6:0]} combinations checked against a packed      **
** golden table generated by an independent Python model                 **
** (gen_alu_golden.py, kept with the commit). Golden derivation, read    **
** gate-by-gate from the netlist: each NAND_GATE (BubblesMask=00) forms  **
** ~(SI[i]&E[i]); the OR_GATE_7_INPUTS BubblesMask is 7'b1111111, so     **
** every OR input is re-inverted: D = |(SI[i]&E[i]) for i=0..6.          **
**                                                                       **
** Pure combinational module (logisim gates only, no ndlib FF/latch      **
** primitives) - a single build mode covers it.                          **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_CPU_ALU_OUTMUX_SEL7_tb;

  reg [6:0] E_6_0 = 0;
  reg [6:0] SI_6_0 = 0;
  wire D;

  integer errors = 0;
  integer checks = 0;
  integer idx;

  CGA_CPU_ALU_OUTMUX_SEL7 dut (
      .E_6_0 (E_6_0),
      .SI_6_0(SI_6_0),
      .D     (D)
  );

  // Golden table: bit index = {SI[6:0],E[6:0]}, generated independently.
  // GOLD7: 16384 bits, MSB-first concatenation
  wire [16383:0] GOLD7 = {
    256'hfffffffffffffffffffffffffffffffefffffffffffffffffffffffffffffffc,
    256'hfffffffffffffffffffffffffffffffafffffffffffffffffffffffffffffff0,
    256'hffffffffffffffffffffffffffffffeeffffffffffffffffffffffffffffffcc,
    256'hffffffffffffffffffffffffffffffaaffffffffffffffffffffffffffffff00,
    256'hfffffffffffffffffffffffffffffefefffffffffffffffffffffffffffffcfc,
    256'hfffffffffffffffffffffffffffffafafffffffffffffffffffffffffffff0f0,
    256'hffffffffffffffffffffffffffffeeeeffffffffffffffffffffffffffffcccc,
    256'hffffffffffffffffffffffffffffaaaaffffffffffffffffffffffffffff0000,
    256'hfffffffffffffffffffffffffffefffefffffffffffffffffffffffffffcfffc,
    256'hfffffffffffffffffffffffffffafffafffffffffffffffffffffffffff0fff0,
    256'hffffffffffffffffffffffffffeeffeeffffffffffffffffffffffffffccffcc,
    256'hffffffffffffffffffffffffffaaffaaffffffffffffffffffffffffff00ff00,
    256'hfffffffffffffffffffffffffefefefefffffffffffffffffffffffffcfcfcfc,
    256'hfffffffffffffffffffffffffafafafafffffffffffffffffffffffff0f0f0f0,
    256'hffffffffffffffffffffffffeeeeeeeeffffffffffffffffffffffffcccccccc,
    256'hffffffffffffffffffffffffaaaaaaaaffffffffffffffffffffffff00000000,
    256'hfffffffffffffffffffffffefffffffefffffffffffffffffffffffcfffffffc,
    256'hfffffffffffffffffffffffafffffffafffffffffffffffffffffff0fffffff0,
    256'hffffffffffffffffffffffeeffffffeeffffffffffffffffffffffccffffffcc,
    256'hffffffffffffffffffffffaaffffffaaffffffffffffffffffffff00ffffff00,
    256'hfffffffffffffffffffffefefffffefefffffffffffffffffffffcfcfffffcfc,
    256'hfffffffffffffffffffffafafffffafafffffffffffffffffffff0f0fffff0f0,
    256'hffffffffffffffffffffeeeeffffeeeeffffffffffffffffffffccccffffcccc,
    256'hffffffffffffffffffffaaaaffffaaaaffffffffffffffffffff0000ffff0000,
    256'hfffffffffffffffffffefffefffefffefffffffffffffffffffcfffcfffcfffc,
    256'hfffffffffffffffffffafffafffafffafffffffffffffffffff0fff0fff0fff0,
    256'hffffffffffffffffffeeffeeffeeffeeffffffffffffffffffccffccffccffcc,
    256'hffffffffffffffffffaaffaaffaaffaaffffffffffffffffff00ff00ff00ff00,
    256'hfffffffffffffffffefefefefefefefefffffffffffffffffcfcfcfcfcfcfcfc,
    256'hfffffffffffffffffafafafafafafafafffffffffffffffff0f0f0f0f0f0f0f0,
    256'hffffffffffffffffeeeeeeeeeeeeeeeeffffffffffffffffcccccccccccccccc,
    256'hffffffffffffffffaaaaaaaaaaaaaaaaffffffffffffffff0000000000000000,
    256'hfffffffffffffffefffffffffffffffefffffffffffffffcfffffffffffffffc,
    256'hfffffffffffffffafffffffffffffffafffffffffffffff0fffffffffffffff0,
    256'hffffffffffffffeeffffffffffffffeeffffffffffffffccffffffffffffffcc,
    256'hffffffffffffffaaffffffffffffffaaffffffffffffff00ffffffffffffff00,
    256'hfffffffffffffefefffffffffffffefefffffffffffffcfcfffffffffffffcfc,
    256'hfffffffffffffafafffffffffffffafafffffffffffff0f0fffffffffffff0f0,
    256'hffffffffffffeeeeffffffffffffeeeeffffffffffffccccffffffffffffcccc,
    256'hffffffffffffaaaaffffffffffffaaaaffffffffffff0000ffffffffffff0000,
    256'hfffffffffffefffefffffffffffefffefffffffffffcfffcfffffffffffcfffc,
    256'hfffffffffffafffafffffffffffafffafffffffffff0fff0fffffffffff0fff0,
    256'hffffffffffeeffeeffffffffffeeffeeffffffffffccffccffffffffffccffcc,
    256'hffffffffffaaffaaffffffffffaaffaaffffffffff00ff00ffffffffff00ff00,
    256'hfffffffffefefefefffffffffefefefefffffffffcfcfcfcfffffffffcfcfcfc,
    256'hfffffffffafafafafffffffffafafafafffffffff0f0f0f0fffffffff0f0f0f0,
    256'hffffffffeeeeeeeeffffffffeeeeeeeeffffffffccccccccffffffffcccccccc,
    256'hffffffffaaaaaaaaffffffffaaaaaaaaffffffff00000000ffffffff00000000,
    256'hfffffffefffffffefffffffefffffffefffffffcfffffffcfffffffcfffffffc,
    256'hfffffffafffffffafffffffafffffffafffffff0fffffff0fffffff0fffffff0,
    256'hffffffeeffffffeeffffffeeffffffeeffffffccffffffccffffffccffffffcc,
    256'hffffffaaffffffaaffffffaaffffffaaffffff00ffffff00ffffff00ffffff00,
    256'hfffffefefffffefefffffefefffffefefffffcfcfffffcfcfffffcfcfffffcfc,
    256'hfffffafafffffafafffffafafffffafafffff0f0fffff0f0fffff0f0fffff0f0,
    256'hffffeeeeffffeeeeffffeeeeffffeeeeffffccccffffccccffffccccffffcccc,
    256'hffffaaaaffffaaaaffffaaaaffffaaaaffff0000ffff0000ffff0000ffff0000,
    256'hfffefffefffefffefffefffefffefffefffcfffcfffcfffcfffcfffcfffcfffc,
    256'hfffafffafffafffafffafffafffafffafff0fff0fff0fff0fff0fff0fff0fff0,
    256'hffeeffeeffeeffeeffeeffeeffeeffeeffccffccffccffccffccffccffccffcc,
    256'hffaaffaaffaaffaaffaaffaaffaaffaaff00ff00ff00ff00ff00ff00ff00ff00,
    256'hfefefefefefefefefefefefefefefefefcfcfcfcfcfcfcfcfcfcfcfcfcfcfcfc,
    256'hfafafafafafafafafafafafafafafafaf0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0,
    256'heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccccccccccccccccc,
    256'haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa00000000000000000000000000000000
  };
  initial begin
    for (idx = 0; idx < 16384; idx = idx + 1) begin
      {SI_6_0, E_6_0} = idx[13:0];
      #1;
      checks = checks + 1;
      if (D !== GOLD7[idx]) begin
        errors = errors + 1;
        $display("FAIL idx=%0d: SI=%07b E=%07b got D=%b expected %b",
                 idx, SI_6_0, E_6_0, D, GOLD7[idx]);
      end
    end

    if (errors == 0 && checks == 16384)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 16384 checks)", errors, checks);
    $finish;
  end

endmodule
