/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_SWAP testbench                                                **
**                                                                       **
** Exhaustive verification of the swap register:                         **
**                                                                       **
**  1. Directed golden vectors (20, generated by the independent Python  **
**     model gen_alu_golden.py): walking-one plus corner patterns with   **
**     explicit expected constants.                                      **
**  2. Exhaustive sweep: all 65536 FIDBO values, each clocked in and     **
**     checked against the independently derived mapping                 **
**     SW = {FIDBO[7:0], FIDBO[15:8]} (byte swap). Derivation, read      **
**     pin-by-pin from the netlist: R81/R81_EN map QA..QH <- A..H;      **
**     SWAP_LO_REG A..H = FIDBO[15..8] -> QA..QH = SW[7..0], and         **
**     SWAP_HI_REG A..H = FIDBO[7..0]  -> QA..QH = SW[15..8].            **
**  3. Hold: with new data on FIDBO but no ALUCLK event, SW must keep    **
**     the last captured value.                                          **
**                                                                       **
** NOT pure combinational: two R81_EN registers clocked by ALUCLK        **
** (latch/CP mode) or sysclk+ALUCLK_EN (FPGA_FF_MODE). Compile once      **
** plain and once with -DFPGA_FF_MODE - the Makefile target runs both.   **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_SWAP_tb;

  reg         sysclk = 0;
  reg         ALUCLK_EN = 0;
  reg         ALUCLK = 0;
  reg  [15:0] FIDBO_15_0 = 0;
  wire [15:0] SW_15_0;

  integer errors = 0;
  integer checks = 0;
  integer idx;

  CGA_ALU_SWAP dut (
      .sysclk    (sysclk),
      .ALUCLK_EN (ALUCLK_EN),
      .ALUCLK    (ALUCLK),
      .FIDBO_15_0(FIDBO_15_0),
      .SW_15_0   (SW_15_0)
  );

  always #5 sysclk = ~sysclk;

  // One ALUCLK event, valid in BOTH build modes: the EN-mode register
  // captures at posedge sysclk while ALUCLK_EN=1; the CP-mode register
  // captures at the posedge of ALUCLK raised just after the same sysclk
  // edge (inputs stable).
  task pulse_aluclk;
    begin
      @(negedge sysclk);
      ALUCLK_EN = 1;
      @(posedge sysclk);
      #1 ALUCLK = 1;
      @(negedge sysclk);
      ALUCLK    = 0;
      ALUCLK_EN = 0;
    end
  endtask

  task run_vec(input [15:0] din, input [15:0] exp);
    begin
      FIDBO_15_0 = din;
      pulse_aluclk;
      checks = checks + 1;
      if (SW_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL vec: FIDBO=%04h got SW=%04h expected %04h",
                 din, SW_15_0, exp);
      end
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_ALU_SWAP_tb: FPGA_FF_MODE (sysclk+ALUCLK_EN capture)");
`else
    $display("CGA_ALU_SWAP_tb: latch/CP mode (posedge ALUCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_golden.py.
    // ------------------------------------------------------------------
      run_vec(16'h0001, 16'h0100);
      run_vec(16'h0002, 16'h0200);
      run_vec(16'h0004, 16'h0400);
      run_vec(16'h0008, 16'h0800);
      run_vec(16'h0010, 16'h1000);
      run_vec(16'h0020, 16'h2000);
      run_vec(16'h0040, 16'h4000);
      run_vec(16'h0080, 16'h8000);
      run_vec(16'h0100, 16'h0001);
      run_vec(16'h0200, 16'h0002);
      run_vec(16'h0400, 16'h0004);
      run_vec(16'h0800, 16'h0008);
      run_vec(16'h1000, 16'h0010);
      run_vec(16'h2000, 16'h0020);
      run_vec(16'h4000, 16'h0040);
      run_vec(16'h8000, 16'h0080);
      run_vec(16'h0000, 16'h0000);
      run_vec(16'hFFFF, 16'hFFFF);
      run_vec(16'hAA55, 16'h55AA);
      run_vec(16'h1234, 16'h3412);

    // ------------------------------------------------------------------
    // 2. Exhaustive sweep of the full 16-bit input space.
    // ------------------------------------------------------------------
    for (idx = 0; idx < 65536; idx = idx + 1) begin
      run_vec(idx[15:0], {idx[7:0], idx[15:8]});
    end

    // ------------------------------------------------------------------
    // 3. Hold without a clock event: change FIDBO, wait, SW unchanged.
    //    (Last captured value was FFFF -> SW = FFFF.)
    // ------------------------------------------------------------------
    FIDBO_15_0 = 16'h5A5A;
    #40;
    checks = checks + 1;
    if (SW_15_0 !== 16'hFFFF) begin
      errors = errors + 1;
      $display("FAIL hold: got SW=%04h expected FFFF (no clock event)",
               SW_15_0);
    end
    FIDBO_15_0 = 16'hC3C3;
    #40;
    checks = checks + 1;
    if (SW_15_0 !== 16'hFFFF) begin
      errors = errors + 1;
      $display("FAIL hold2: got SW=%04h expected FFFF (no clock event)",
               SW_15_0);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 20 directed + 65536 sweep + 2 hold = 65558.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 65558)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 65558 checks)",
               errors, checks);
    $finish;
  end

endmodule
