/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_RALU_LOGOP testbench                                          **
**                                                                       **
** Verification of the 16-bit logic-operation function generator. Full   **
** input space is 2^34 (A,S,ALU14,FSEL) - too large to sweep, so the     **
** coverage is split (per-slice exhaustive + fixed-seed LFSR):           **
**                                                                       **
**  1. Directed golden vectors (10, generated by the independent Python  **
**     model gen_alu_tier1_golden.py) with explicit expected constants.  **
**  2. Per-slice exhaustive: 16 identical MUX41P slices sharing only     **
**     ALU14/FSEL. For each slice i, all 16 {ALU14,FSEL,A[i],S[i]}       **
**     combos on an all-zeros AND an all-ones background, checking the   **
**     FULL 16-bit output each time (proves slice equivalence, catches   **
**     cross-slice wiring swaps). 16 x 16 x 2 = 512 checks.              **
**  3. Full-width fixed-seed LFSR vectors: 4096 {A,S} pairs (32-bit      **
**     Fibonacci LFSR, taps 32/22/2/1, seed ACE10002, identical code in  **
**     gen_alu_tier1_golden.py) with ALU14/FSEL cycling all 4 combos,    **
**     checked against the independent model, PLUS one running-sum       **
**     checksum check against the Python constant 32'h05F2A6D0.          **
**                                                                       **
** Model derivation, read gate-by-gate: each bit is a MUX41P with        **
** sel = {B=S[i], A=A[i]} and data D0=GND D1=ALU14 D2=ALU14 D3=FSEL      **
** (Multiplexer_4: muxOut = muxIn[{B,A}], non-inverting), so             **
**   LF[i] = 0     when S[i]=0 A[i]=0                                    **
**         = ALU14 when S[i]^A[i]                                        **
**         = FSEL  when S[i]=1 A[i]=1                                    **
** i.e. LF = (S&A & {16{FSEL}}) | ((S^A) & {16{ALU14}}).                 **
**                                                                       **
** Pure combinational module (MUX41P/Multiplexer_4 has no FF/latch       **
** primitives) - a single build mode covers it.                          **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_RALU_LOGOP_tb;

  reg         ALU14 = 0;
  reg  [15:0] A_15_0 = 0;
  reg         FSEL = 0;
  reg  [15:0] S_15_0 = 0;
  wire [15:0] LF_15_0;

  integer errors = 0;
  integer checks = 0;
  integer i, c, k;
  reg [31:0] lfsr;
  reg [31:0] cksum;
  reg        fb;
  reg [15:0] exp;

  CGA_ALU_RALU_LOGOP dut (
      .ALU14  (ALU14),
      .A_15_0 (A_15_0),
      .FSEL   (FSEL),
      .S_15_0 (S_15_0),
      .LF_15_0(LF_15_0)
  );

  // Independent model (see header derivation).
  function [15:0] model(input alu14_in, input [15:0] a_in,
                        input fsel_in, input [15:0] s_in);
    begin
      model = ((s_in & a_in) & {16{fsel_in}}) |
              ((s_in ^ a_in) & {16{alu14_in}});
    end
  endfunction

  task check(input [255:0] name);
    begin
      #1;
      checks = checks + 1;
      exp = model(ALU14, A_15_0, FSEL, S_15_0);
      if (LF_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: ALU14=%b FSEL=%b A=%04h S=%04h got LF=%04h expected %04h",
                 name, ALU14, FSEL, A_15_0, S_15_0, LF_15_0, exp);
      end
    end
  endtask

  task dir_vec(input alu14_in, input [15:0] a_in, input fsel_in,
               input [15:0] s_in, input [15:0] e_in);
    begin
      ALU14 = alu14_in; A_15_0 = a_in; FSEL = fsel_in; S_15_0 = s_in;
      #1;
      checks = checks + 1;
      if (LF_15_0 !== e_in) begin
        errors = errors + 1;
        $display("FAIL dir: ALU14=%b FSEL=%b A=%04h S=%04h got LF=%04h expected %04h",
                 alu14_in, fsel_in, a_in, s_in, LF_15_0, e_in);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_tier1_golden.py.
    // ------------------------------------------------------------------
      dir_vec(1'b0, 16'h0000, 1'b0, 16'h0000, 16'h0000);
      dir_vec(1'b0, 16'hFFFF, 1'b0, 16'hFFFF, 16'h0000);
      dir_vec(1'b1, 16'hFFFF, 1'b0, 16'hFFFF, 16'h0000);
      dir_vec(1'b0, 16'hFFFF, 1'b1, 16'hFFFF, 16'hFFFF);
      dir_vec(1'b1, 16'hFFFF, 1'b0, 16'h0000, 16'hFFFF);
      dir_vec(1'b1, 16'h0000, 1'b0, 16'hFFFF, 16'hFFFF);
      dir_vec(1'b0, 16'hFFFF, 1'b0, 16'h0000, 16'h0000);
      dir_vec(1'b1, 16'hA5C3, 1'b0, 16'h1234, 16'hB7F7);
      dir_vec(1'b0, 16'hA5C3, 1'b1, 16'h1234, 16'h0000);
      dir_vec(1'b1, 16'hF0F0, 1'b1, 16'h0FF0, 16'hFFF0);

    // ------------------------------------------------------------------
    // 2. Per-slice exhaustive, both backgrounds, full-width check.
    //    c[3]=ALU14 c[2]=FSEL c[1]=A[i] c[0]=S[i].
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      for (c = 0; c < 16; c = c + 1) begin
        // background all zeros
        ALU14 = c[3]; FSEL = c[2];
        A_15_0 = {15'h0000, c[1]} << i;
        S_15_0 = {15'h0000, c[0]} << i;
        check("slice-bg0");
        // background all ones
        ALU14 = c[3]; FSEL = c[2];
        A_15_0 = ~(({15'h0000, ~c[1]}) << i);
        S_15_0 = ~(({15'h0000, ~c[0]}) << i);
        check("slice-bg1");
      end
    end

    // ------------------------------------------------------------------
    // 3. 4096 fixed-seed LFSR full-width vectors + Python checksum.
    // ------------------------------------------------------------------
    lfsr  = 32'hACE10002;
    cksum = 32'h0;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      A_15_0 = lfsr[31:16];
      S_15_0 = lfsr[15:0];
      ALU14  = k[0];
      FSEL   = k[1];
      check("lfsr");
      cksum = cksum + {16'h0000, LF_15_0};
    end
    checks = checks + 1;
    if (cksum !== 32'h05F2A6D0) begin
      errors = errors + 1;
      $display("FAIL cksum: got %08h expected 05F2A6D0", cksum);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 10 directed + 512 slice + 4096 LFSR + 1 = 4619.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4619)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4619 checks)",
               errors, checks);
    $finish;
  end

endmodule
