/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_QREG testbench                                                **
**                                                                       **
** Exhaustive verification of the Q register (page 43). Full input       **
** space is 16-bit state x 19 stimulus bits per clock - too large to     **
** sweep, so the coverage is split:                                      **
**                                                                       **
**  1. Directed golden vectors (26, expected constants generated by the  **
**     independent Python model gen_tier3_alu_golden.py, kept outside    **
**     the repo). Includes a dedicated MUXQ15 battery hitting EVERY      **
**     muxIn of the bit-15 mux with both data values, with Q[0]         **
**     deliberately DIFFERENT from F[0] on the shift-right steps so the  **
**     historical MPY bug (D3 wired to Q[0] instead of F[0], leaving     **
**     every MPY product's low word 0) is provably caught and cannot     **
**     return silently.                                                  **
**  2. Walking-one flush loops: each one-hot value loaded then shifted   **
**     17 steps left (QLI=0, F noise) and, separately, 17 steps right    **
**     (F[0]=0, upper F bits + QLI noise) - proves per-bit shift wiring  **
**     and that bits fall off the ends. 2 x 16 x 18 = 576 checks.        **
**  3. Serial streams: 16-bit patterns streamed in through QLI (shift    **
**     left) and through F[0] (shift right, MPY-style, with noise on     **
**     F[15:1]) - 36 checks.                                             **
**  4. Fixed-seed LFSR (32-bit Fibonacci, taps 32/22/2/1, seed          **
**     51524547): 4096 random {QSEL,F,QLI} steps vs the inline model.    **
**  5. Running checksum acc = acc*31 + Q over every clocked step vs the  **
**     Python constant - proves the inline model and the whole sequence  **
**     bit-exact against the independent model.                          **
**                                                                       **
** Model, read pin-by-pin from the netlist (MUX41P sel={QSEL1,QSEL0}):   **
**   QSEL=00 hold (D0=Q[i]); QSEL=01 load F (D1=F[i]);                   **
**   QSEL=10 shift LEFT, Q[i]<=Q[i-1], Q[0]<=QLI (D2);                   **
**   QSEL=11 shift RIGHT, Q[i]<=Q[i+1], Q[15]<=F[0] (D3, the MPY         **
**   serial input from the R-side shifter).                              **
**                                                                       **
** Registered module (2x R81_EN; no L4/L8/LATCH primitives, so           **
** USE_TRANSPARENT_LATCHES is not applicable). Two build modes:          **
** default (posedge ALUCLK) and -DFPGA_FF_MODE (sysclk+ALUCLK_EN).       **
** The Makefile target runs both.                                        **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_QREG_tb;

  reg         sysclk = 0;
  reg         ALUCLK_EN = 0;
  reg         ALUCLK = 0;
  reg  [15:0] F_15_0 = 0;
  reg         QLI = 0;
  reg  [ 1:0] QSEL_1_0 = 0;
  wire [15:0] Q_15_0;

  integer errors = 0;
  integer checks = 0;
  integer i, k;
  reg [31:0] acc = 0;
  reg [31:0] lfsr;
  reg        fb;
  reg [15:0] mq;  // model state for the loop phases
  reg [15:0] fv;

  CGA_ALU_QREG dut (
      .sysclk   (sysclk),
      .ALUCLK_EN(ALUCLK_EN),
      .ALUCLK   (ALUCLK),
      .F_15_0   (F_15_0),
      .QLI      (QLI),
      .QSEL_1_0 (QSEL_1_0),
      .Q_15_0   (Q_15_0)
  );

  always #5 sysclk = ~sysclk;

  // One ALUCLK event, valid in BOTH build modes (see CGA_ALU_SWAP_tb.v).
  task pulse_aluclk;
    begin
      @(negedge sysclk);
      ALUCLK_EN = 1;
      @(posedge sysclk);
      #1 ALUCLK = 1;
      @(negedge sysclk);
      ALUCLK    = 0;
      ALUCLK_EN = 0;
    end
  endtask

  // Independent next-state model (derivation in the header).
  function [15:0] qnext(input [1:0] qsel, input [15:0] q, input [15:0] f,
                        input qli);
    begin
      case (qsel)
        2'b00:   qnext = q;
        2'b01:   qnext = f;
        2'b10:   qnext = {q[14:0], qli};
        default: qnext = {f[0], q[15:1]};
      endcase
    end
  endfunction

  task step(input [1:0] qsel, input [15:0] f, input qli,
            input [15:0] exp);
    begin
      QSEL_1_0 = qsel;
      F_15_0   = f;
      QLI      = qli;
      pulse_aluclk;
      checks = checks + 1;
      acc    = (acc << 5) - acc + {16'h0000, Q_15_0};
      if (Q_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL step: QSEL=%b F=%04h QLI=%b got Q=%04h expected %04h",
                 qsel, f, qli, Q_15_0, exp);
      end
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_ALU_QREG_tb: FPGA_FF_MODE (sysclk+ALUCLK_EN capture)");
`else
    $display("CGA_ALU_QREG_tb: latch/CP mode (posedge ALUCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Directed vectors incl. the MUXQ15 battery, constants from
    //    gen_tier3_alu_golden.py. Note the shift-right steps where
    //    F[0] != Q[0]: the historical rotate bug (D3=Q[0]) would give
    //    Q15=0/1 exactly opposite to the expected constants here.
    // ------------------------------------------------------------------
      step(2'd1, 16'h0000, 1'b0, 16'h0000);
      step(2'd3, 16'h0001, 1'b0, 16'h8000);  // F0=1,Q0=0: bug gives 0000
      step(2'd0, 16'h7FFF, 1'b1, 16'h8000);  // hold, Q15=1
      step(2'd3, 16'hFFFE, 1'b1, 16'h4000);  // F0=0, Q15 moves to Q14
      step(2'd1, 16'h8001, 1'b0, 16'h8001);
      step(2'd3, 16'h0000, 1'b0, 16'h4000);  // F0=0,Q0=1: bug gives C000
      step(2'd1, 16'h8001, 1'b0, 16'h8001);
      step(2'd3, 16'h0001, 1'b1, 16'hC000);  // F0=1,Q0=1
      step(2'd1, 16'h0000, 1'b0, 16'h0000);
      step(2'd2, 16'hFFFF, 1'b1, 16'h0001);  // SL serial-in 1, F noise
      step(2'd2, 16'hFFFF, 1'b0, 16'h0002);  // SL serial-in 0, F noise
      step(2'd1, 16'h4000, 1'b0, 16'h4000);
      step(2'd2, 16'h0000, 1'b0, 16'h8000);  // SL: Q14 -> Q15
      step(2'd2, 16'h0000, 1'b0, 16'h0000);  // SL: Q15 falls off
      step(2'd1, 16'hFFFF, 1'b0, 16'hFFFF);
      step(2'd0, 16'h0000, 1'b0, 16'hFFFF);  // hold vs all-zero F
      step(2'd3, 16'hFFFE, 1'b0, 16'h7FFF);  // SR: F0=0 into Q15
      step(2'd3, 16'h0001, 1'b0, 16'hBFFF);  // SR: F0=1 into Q15
      step(2'd1, 16'hAAAA, 1'b1, 16'hAAAA);
      step(2'd0, 16'h5555, 1'b0, 16'hAAAA);
      step(2'd2, 16'hAAAA, 1'b1, 16'h5555);
      step(2'd3, 16'hAAAB, 1'b1, 16'hAAAA);
      step(2'd1, 16'h5A5A, 1'b0, 16'h5A5A);
      step(2'd3, 16'h0000, 1'b1, 16'h2D2D);
      step(2'd2, 16'h0000, 1'b1, 16'h5A5B);
      step(2'd0, 16'hFFFF, 1'b1, 16'h5A5B);
    mq = 16'h5A5B;

    // ------------------------------------------------------------------
    // 2a. Walking-one, shift-left flush (F is pure noise, QLI=0).
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      mq = qnext(2'd1, mq, 16'h0001 << i, 1'b0);
      step(2'd1, 16'h0001 << i, 1'b0, mq);
      for (k = 0; k < 17; k = k + 1) begin
        mq = qnext(2'd2, mq, 16'hDEAD, 1'b0);
        step(2'd2, 16'hDEAD, 1'b0, mq);
      end
    end

    // ------------------------------------------------------------------
    // 2b. Walking-one, shift-right flush (F[0]=0, F[15:1]+QLI noise).
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      mq = qnext(2'd1, mq, 16'h0001 << i, 1'b1);
      step(2'd1, 16'h0001 << i, 1'b1, mq);
      for (k = 0; k < 17; k = k + 1) begin
        mq = qnext(2'd3, mq, 16'hFFFE, 1'b1);
        step(2'd3, 16'hFFFE, 1'b1, mq);
      end
    end

    // ------------------------------------------------------------------
    // 3. Serial streams: 9C35 through QLI (left), C7A2 through F[0]
    //    (right, MPY-style, F[15:1] noise).
    // ------------------------------------------------------------------
    mq = qnext(2'd1, mq, 16'h0000, 1'b0);
    step(2'd1, 16'h0000, 1'b0, mq);
    for (k = 0; k < 16; k = k + 1) begin
      mq = qnext(2'd2, mq, 16'h8181, (16'h9C35 >> k) & 1'b1);
      step(2'd2, 16'h8181, (16'h9C35 >> k) & 1'b1, mq);
    end
    mq = qnext(2'd1, mq, 16'h0000, 1'b0);
    step(2'd1, 16'h0000, 1'b0, mq);
    for (k = 0; k < 16; k = k + 1) begin
      fv = ((k[15:0] * 16'h0101 + 16'h0202) & 16'hFFFE)
           | ((16'hC7A2 >> k) & 16'h0001);
      mq = qnext(2'd3, mq, fv, 1'b1);
      step(2'd3, fv, 1'b1, mq);
    end

    // ------------------------------------------------------------------
    // 4. 4096 fixed-seed LFSR steps (random QSEL/F/QLI) vs the model.
    // ------------------------------------------------------------------
    lfsr = 32'h51524547;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      mq   = qnext(lfsr[17:16], mq, lfsr[15:0], lfsr[18]);
      step(lfsr[17:16], lfsr[15:0], lfsr[18], mq);
    end

    // ------------------------------------------------------------------
    // 5. Hold without a clock event: change inputs, wait, Q unchanged.
    //    (Python-computed final state: 9BF2.)
    // ------------------------------------------------------------------
    QSEL_1_0 = 2'd1;
    F_15_0   = 16'h1234;
    QLI      = 1'b1;
    #40;
    checks = checks + 1;
    if (Q_15_0 !== 16'h9BF2) begin
      errors = errors + 1;
      $display("FAIL hold: got Q=%04h expected 9BF2 (no clock event)",
               Q_15_0);
    end
    QSEL_1_0 = 2'd3;
    F_15_0   = 16'hFFFF;
    #40;
    checks = checks + 1;
    if (Q_15_0 !== 16'h9BF2) begin
      errors = errors + 1;
      $display("FAIL hold2: got Q=%04h expected 9BF2 (no clock event)",
               Q_15_0);
    end

    // ------------------------------------------------------------------
    // 6. Whole-sequence checksum vs the independent Python model.
    // ------------------------------------------------------------------
    checks = checks + 1;
    if (acc !== 32'h54EDB973) begin
      errors = errors + 1;
      $display("FAIL checksum: got %08h expected 54EDB973", acc);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 26 + 576 + 34 + 4096 steps + 2 hold + 1 cks
    //          = 4735.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4735)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4735 checks)",
               errors, checks);
    $finish;
  end

endmodule
