/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_DBR testbench                                                 **
**                                                                       **
** Exhaustive verification of the Data Bus Register (page 52):           **
**                                                                       **
**  1. Directed golden vectors (24, expected constants generated by the  **
**     independent Python model gen_tier3_alu_golden.py, kept outside    **
**     the repo): load/hold interleave, walking-one loads, corners.      **
**  2. Exhaustive load sweep: all 65536 CD values clocked in with        **
**     LDDBRN=0, each checked (DBR must equal CD).                       **
**  3. Hold sweep: 256 clock events with LDDBRN=1 and wiggling CD -      **
**     DBR must keep the last loaded value (FFFF).                       **
**  4. Hold without any clock event: CD changed, LDDBRN=0, no pulse -    **
**     DBR unchanged (2 checks).                                         **
**  5. Running checksum acc = acc*31 + DBR over every clocked step,      **
**     compared against the Python-computed constant - proves the whole  **
**     sequence bit-exact against the independent model.                 **
**                                                                       **
** Model, read pin-by-pin from the netlist: 16x SCAN_FF_EN with          **
** D=Q (hold feedback), TE=~LDDBRN, TI=CD[i]; so a clock event loads CD  **
** when LDDBRN=0 and holds otherwise.                                    **
**                                                                       **
** Registered module (SCAN_FF_EN only; no L4/L8/LATCH primitives, so     **
** USE_TRANSPARENT_LATCHES is not applicable). Two build modes:          **
** default (posedge ALUCLK) and -DFPGA_FF_MODE (sysclk+ALUCLK_EN).       **
** The Makefile target runs both.                                        **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_DBR_tb;

  reg         sysclk = 0;
  reg         ALUCLK_EN = 0;
  reg         ALUCLK = 0;
  reg  [15:0] CD_15_0 = 0;
  reg         LDDBRN = 1;
  wire [15:0] DBR_15_0;

  integer errors = 0;
  integer checks = 0;
  integer idx, k;
  reg [31:0] acc = 0;

  CGA_ALU_DBR dut (
      .sysclk   (sysclk),
      .ALUCLK_EN(ALUCLK_EN),
      .ALUCLK   (ALUCLK),
      .CD_15_0  (CD_15_0),
      .LDDBRN   (LDDBRN),
      .DBR_15_0 (DBR_15_0)
  );

  always #5 sysclk = ~sysclk;

  // One ALUCLK event, valid in BOTH build modes: the EN-mode register
  // captures at posedge sysclk while ALUCLK_EN=1; the CP-mode register
  // captures at the posedge of ALUCLK raised just after the same sysclk
  // edge (inputs stable).
  task pulse_aluclk;
    begin
      @(negedge sysclk);
      ALUCLK_EN = 1;
      @(posedge sysclk);
      #1 ALUCLK = 1;
      @(negedge sysclk);
      ALUCLK    = 0;
      ALUCLK_EN = 0;
    end
  endtask

  task step(input ld_n, input [15:0] cd, input [15:0] exp);
    begin
      LDDBRN  = ld_n;
      CD_15_0 = cd;
      pulse_aluclk;
      checks = checks + 1;
      acc    = (acc << 5) - acc + {16'h0000, DBR_15_0};
      if (DBR_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL step: LDDBRN=%b CD=%04h got DBR=%04h expected %04h",
                 ld_n, cd, DBR_15_0, exp);
      end
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_ALU_DBR_tb: FPGA_FF_MODE (sysclk+ALUCLK_EN capture)");
`else
    $display("CGA_ALU_DBR_tb: latch/CP mode (posedge ALUCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Directed vectors, constants from gen_tier3_alu_golden.py.
    // ------------------------------------------------------------------
      step(1'b0, 16'hAA55, 16'hAA55);
      step(1'b1, 16'h55AA, 16'hAA55);
      step(1'b1, 16'h0000, 16'hAA55);
      step(1'b0, 16'h0000, 16'h0000);
      step(1'b0, 16'hFFFF, 16'hFFFF);
      step(1'b1, 16'h1234, 16'hFFFF);
      step(1'b0, 16'h0001, 16'h0001);
      step(1'b0, 16'h0002, 16'h0002);
      step(1'b0, 16'h0004, 16'h0004);
      step(1'b0, 16'h0008, 16'h0008);
      step(1'b0, 16'h0010, 16'h0010);
      step(1'b0, 16'h0020, 16'h0020);
      step(1'b0, 16'h0040, 16'h0040);
      step(1'b0, 16'h0080, 16'h0080);
      step(1'b0, 16'h0100, 16'h0100);
      step(1'b0, 16'h0200, 16'h0200);
      step(1'b0, 16'h0400, 16'h0400);
      step(1'b0, 16'h0800, 16'h0800);
      step(1'b0, 16'h1000, 16'h1000);
      step(1'b0, 16'h2000, 16'h2000);
      step(1'b0, 16'h4000, 16'h4000);
      step(1'b0, 16'h8000, 16'h8000);
      step(1'b0, 16'h5A5A, 16'h5A5A);
      step(1'b1, 16'hA5A5, 16'h5A5A);

    // ------------------------------------------------------------------
    // 2. Exhaustive load sweep of the full 16-bit CD space.
    // ------------------------------------------------------------------
    for (idx = 0; idx < 65536; idx = idx + 1) begin
      step(1'b0, idx[15:0], idx[15:0]);
    end

    // ------------------------------------------------------------------
    // 3. 256 hold events with wiggling CD - DBR keeps FFFF.
    // ------------------------------------------------------------------
    for (k = 0; k < 256; k = k + 1) begin
      step(1'b1, (k[15:0] * 16'h0101) ^ 16'h00FF, 16'hFFFF);
    end

    // ------------------------------------------------------------------
    // 4. Hold without any clock event (LDDBRN asserted low, no pulse).
    // ------------------------------------------------------------------
    LDDBRN  = 1'b0;
    CD_15_0 = 16'h5A5A;
    #40;
    checks = checks + 1;
    if (DBR_15_0 !== 16'hFFFF) begin
      errors = errors + 1;
      $display("FAIL hold: got DBR=%04h expected FFFF (no clock event)",
               DBR_15_0);
    end
    CD_15_0 = 16'hC3C3;
    #40;
    checks = checks + 1;
    if (DBR_15_0 !== 16'hFFFF) begin
      errors = errors + 1;
      $display("FAIL hold2: got DBR=%04h expected FFFF (no clock event)",
               DBR_15_0);
    end

    // ------------------------------------------------------------------
    // 5. Whole-sequence checksum vs the independent Python model.
    // ------------------------------------------------------------------
    checks = checks + 1;
    if (acc !== 32'hEF1B2180) begin
      errors = errors + 1;
      $display("FAIL checksum: got %08h expected EF1B2180", acc);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 24 + 65536 + 256 + 2 + 1 = 65819.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 65819)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 65819 checks)",
               errors, checks);
    $finish;
  end

endmodule
