/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_SMUX testbench                                                **
**                                                                       **
** Verification of the 16-bit S-operand source mux. Full input space is  **
** 2^50 (A,B,Q,SA,SB) - too large to sweep, so the coverage is split     **
** (per-slice exhaustive + fixed-seed LFSR):                             **
**                                                                       **
**  1. Directed golden vectors (12, generated by the independent Python  **
**     model gen_alu_tier1_golden.py) with explicit expected constants.  **
**  2. Per-slice exhaustive: 16 identical MUX41P slices sharing only     **
**     SA/SB. For each slice i, all 32 {SB,SA,A[i],B[i],Q[i]} combos on  **
**     an all-zeros AND an all-ones background, checking the FULL        **
**     16-bit output each time (proves slice equivalence, catches        **
**     cross-slice wiring swaps). 16 x 32 x 2 = 1024 checks.             **
**  3. Full-width fixed-seed LFSR vectors: 4096 {A,B,Q} triples (32-bit  **
**     Fibonacci LFSR, taps 32/22/2/1, seed ACE10003, stepped TWICE per  **
**     vector: step1 -> A=lfsr[31:16] B=lfsr[15:0], step2 ->             **
**     Q=lfsr[31:16]; identical code in gen_alu_tier1_golden.py) with    **
**     SA/SB cycling all 4 combos, checked against the independent       **
**     model, PLUS one running-sum checksum check against the Python     **
**     constant 32'h060958DC.                                            **
**                                                                       **
** Model derivation, read gate-by-gate: each bit is a MUX41P with        **
** sel = {B=SB, A=SA} and data D0=Q[i] D1=B[i] D2=GND D3=A[i]            **
** (Multiplexer_4: muxOut = muxIn[{B,A}], non-inverting), so             **
**   S[i] = Q[i] (SB=0,SA=0) | B[i] (SB=0,SA=1)                          **
**        | 0    (SB=1,SA=0) | A[i] (SB=1,SA=1)                          **
**                                                                       **
** Pure combinational module (MUX41P/Multiplexer_4 has no FF/latch       **
** primitives) - a single build mode covers it.                          **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_SMUX_tb;

  reg  [15:0] A_15_0 = 0;
  reg  [15:0] B_15_0 = 0;
  reg  [15:0] Q_15_0 = 0;
  reg         SA = 0;
  reg         SB = 0;
  wire [15:0] S_15_0;

  integer errors = 0;
  integer checks = 0;
  integer i, c, k;
  reg [31:0] lfsr;
  reg [31:0] cksum;
  reg        fb;
  reg [15:0] exp;

  CGA_ALU_SMUX dut (
      .A_15_0(A_15_0),
      .B_15_0(B_15_0),
      .Q_15_0(Q_15_0),
      .SA    (SA),
      .SB    (SB),
      .S_15_0(S_15_0)
  );

  // Independent model (see header derivation).
  function [15:0] model(input [15:0] a_in, input [15:0] b_in,
                        input [15:0] q_in, input sa_in, input sb_in);
    begin
      case ({sb_in, sa_in})
        2'b00: model = q_in;
        2'b01: model = b_in;
        2'b10: model = 16'h0000;
        2'b11: model = a_in;
      endcase
    end
  endfunction

  task check(input [255:0] name);
    begin
      #1;
      checks = checks + 1;
      exp = model(A_15_0, B_15_0, Q_15_0, SA, SB);
      if (S_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: SB=%b SA=%b A=%04h B=%04h Q=%04h got S=%04h expected %04h",
                 name, SB, SA, A_15_0, B_15_0, Q_15_0, S_15_0, exp);
      end
    end
  endtask

  task dir_vec(input [15:0] a_in, input [15:0] b_in, input [15:0] q_in,
               input sa_in, input sb_in, input [15:0] e_in);
    begin
      A_15_0 = a_in; B_15_0 = b_in; Q_15_0 = q_in; SA = sa_in; SB = sb_in;
      #1;
      checks = checks + 1;
      if (S_15_0 !== e_in) begin
        errors = errors + 1;
        $display("FAIL dir: SB=%b SA=%b A=%04h B=%04h Q=%04h got S=%04h expected %04h",
                 sb_in, sa_in, a_in, b_in, q_in, S_15_0, e_in);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_tier1_golden.py.
    // ------------------------------------------------------------------
      dir_vec(16'h1111, 16'h2222, 16'h3333, 1'b0, 1'b0, 16'h3333);
      dir_vec(16'h1111, 16'h2222, 16'h3333, 1'b1, 1'b0, 16'h2222);
      dir_vec(16'h1111, 16'h2222, 16'h3333, 1'b0, 1'b1, 16'h0000);
      dir_vec(16'h1111, 16'h2222, 16'h3333, 1'b1, 1'b1, 16'h1111);
      dir_vec(16'hFFFF, 16'hFFFF, 16'hFFFF, 1'b0, 1'b1, 16'h0000);
      dir_vec(16'h0000, 16'h0000, 16'hFFFF, 1'b0, 1'b0, 16'hFFFF);
      dir_vec(16'hA5C3, 16'h5A3C, 16'hC3A5, 1'b0, 1'b0, 16'hC3A5);
      dir_vec(16'hA5C3, 16'h5A3C, 16'hC3A5, 1'b1, 1'b0, 16'h5A3C);
      dir_vec(16'hA5C3, 16'h5A3C, 16'hC3A5, 1'b1, 1'b1, 16'hA5C3);
      dir_vec(16'h8000, 16'h0001, 16'h4002, 1'b1, 1'b0, 16'h0001);
      dir_vec(16'hFFFF, 16'h0000, 16'h0000, 1'b1, 1'b1, 16'hFFFF);
      dir_vec(16'h0000, 16'hFFFF, 16'h0000, 1'b1, 1'b0, 16'hFFFF);

    // ------------------------------------------------------------------
    // 2. Per-slice exhaustive, both backgrounds, full-width check.
    //    c[4]=SB c[3]=SA c[2]=A[i] c[1]=B[i] c[0]=Q[i].
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      for (c = 0; c < 32; c = c + 1) begin
        // background all zeros
        SB = c[4]; SA = c[3];
        A_15_0 = {15'h0000, c[2]} << i;
        B_15_0 = {15'h0000, c[1]} << i;
        Q_15_0 = {15'h0000, c[0]} << i;
        check("slice-bg0");
        // background all ones
        SB = c[4]; SA = c[3];
        A_15_0 = ~(({15'h0000, ~c[2]}) << i);
        B_15_0 = ~(({15'h0000, ~c[1]}) << i);
        Q_15_0 = ~(({15'h0000, ~c[0]}) << i);
        check("slice-bg1");
      end
    end

    // ------------------------------------------------------------------
    // 3. 4096 fixed-seed LFSR full-width vectors + Python checksum.
    //    LFSR stepped twice per vector (48 data bits needed).
    // ------------------------------------------------------------------
    lfsr  = 32'hACE10003;
    cksum = 32'h0;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      A_15_0 = lfsr[31:16];
      B_15_0 = lfsr[15:0];
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      Q_15_0 = lfsr[31:16];
      SA     = k[0];
      SB     = k[1];
      check("lfsr");
      cksum = cksum + {16'h0000, S_15_0};
    end
    checks = checks + 1;
    if (cksum !== 32'h060958DC) begin
      errors = errors + 1;
      $display("FAIL cksum: got %08h expected 060958DC", cksum);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 12 directed + 1024 slice + 4096 LFSR + 1 = 5133.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 5133)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 5133 checks)",
               errors, checks);
    $finish;
  end

endmodule
