/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_STS testbench                                                 **
**                                                                       **
** Exhaustive verification of the STS status register (page 51). Full    **
** input space is 16-bit state x 21 stimulus bits per clock - too large  **
** to sweep, so the coverage is split:                                   **
**                                                                       **
**  1. Directed golden vectors (22, expected constants generated by the  **
**     independent Python model gen_tier3_alu_golden.py, kept outside    **
**     the repo): every CSTS mode against all-zero and all-one           **
**     backgrounds, both values of each flag, sticky-overflow (bit 5)    **
**     set/keep/clear cases, byte-split loads (LDPILN vs CSTS=11), and   **
**     simultaneous LDPILN=0 + CSTS=01.                                  **
**  2. Fixed-seed LFSR (32-bit Fibonacci, taps 32/22/2/1, seed          **
**     53545321): 4096 random {FIDBO,CSTS,LDPILN,MI,OVF,CRY} steps vs    **
**     the inline model.                                                 **
**  3. Hold without any clock event (2 checks).                          **
**  4. Running checksum acc = acc*31 + STS over every clocked step vs    **
**     the Python constant.                                              **
**                                                                       **
** Model, read pin-by-pin from the netlist (all outputs go through a     **
** double inversion: mux ZN / _n register tap, then the ~s_sts_*_n       **
** output stage, so STS is true-polarity):                               **
**   bits 15-8: SCAN_FF TE=LDPILN, TI=STS (hold), D=FIDBO ->             **
**              load FIDBO[15:8] when LDPILN=0, else hold.               **
**   bits  3-0: SCAN_FF TE=GATES_2=~(CSTS1&CSTS0) ->                     **
**              load FIDBO[3:0] when CSTS=11, else hold.                 **
**   bits  7-4: MUX41P/MUX31LP sel={~CSTS0,~CSTS1} into R41P:            **
**     CSTS=11 -> FIDBO[7:4];                                            **
**     CSTS=01 -> b7 hold, b6<=CRY, b5<=OVF|b5 (GATES_1 sticky OVF),     **
**                b4<=OVF;                                               **
**     CSTS=10 -> b7<=MI, b6..b4 hold;                                   **
**     CSTS=00 -> hold (MUX31LP maps D2 to sel 2 AND 3).                 **
**                                                                       **
** Registered module (SCAN_FF_EN + R41P_EN; no L4/L8/LATCH primitives,   **
** so USE_TRANSPARENT_LATCHES is not applicable). Two build modes:       **
** default (posedge ALUCLK) and -DFPGA_FF_MODE (sysclk+ALUCLK_EN).       **
** The Makefile target runs both.                                        **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_STS_tb;

  reg         sysclk = 0;
  reg         ALUCLK_EN = 0;
  reg         ALUCLK = 0;
  reg         CRY = 0;
  reg  [ 1:0] CSTS_1_0 = 0;
  reg  [15:0] FIDBO_15_0 = 0;
  reg         LDPILN = 1;
  reg         MI = 0;
  reg         OVF = 0;
  wire [15:0] STS_15_0;

  integer errors = 0;
  integer checks = 0;
  integer k;
  reg [31:0] acc = 0;
  reg [31:0] lfsr;
  reg        fb;
  reg [15:0] ms;  // model state for the LFSR phase

  CGA_ALU_STS dut (
      .sysclk    (sysclk),
      .ALUCLK_EN (ALUCLK_EN),
      .ALUCLK    (ALUCLK),
      .CRY       (CRY),
      .CSTS_1_0  (CSTS_1_0),
      .FIDBO_15_0(FIDBO_15_0),
      .LDPILN    (LDPILN),
      .MI        (MI),
      .OVF       (OVF),
      .STS_15_0  (STS_15_0)
  );

  always #5 sysclk = ~sysclk;

  // One ALUCLK event, valid in BOTH build modes (see CGA_ALU_SWAP_tb.v).
  task pulse_aluclk;
    begin
      @(negedge sysclk);
      ALUCLK_EN = 1;
      @(posedge sysclk);
      #1 ALUCLK = 1;
      @(negedge sysclk);
      ALUCLK    = 0;
      ALUCLK_EN = 0;
    end
  endtask

  // Independent next-state model (derivation in the header).
  function [15:0] snext(input [15:0] q, input [15:0] fidbo,
                        input [1:0] csts, input ldpiln,
                        input mi, input ovf, input cry);
    reg [15:0] nx;
    begin
      nx = q;
      if (!ldpiln) nx[15:8] = fidbo[15:8];
      case (csts)
        2'b11: nx[3:0] = fidbo[3:0];
        2'b01: begin
          nx[6] = cry;
          nx[5] = ovf | q[5];
          nx[4] = ovf;
        end
        2'b10: nx[7] = mi;
        default: ;
      endcase
      if (csts == 2'b11) nx[7:4] = fidbo[7:4];
      snext = nx;
    end
  endfunction

  task step(input [15:0] fidbo, input [1:0] csts, input ldpiln,
            input mi, input ovf, input cry, input [15:0] exp);
    begin
      FIDBO_15_0 = fidbo;
      CSTS_1_0   = csts;
      LDPILN     = ldpiln;
      MI         = mi;
      OVF        = ovf;
      CRY        = cry;
      pulse_aluclk;
      checks = checks + 1;
      acc    = (acc << 5) - acc + {16'h0000, STS_15_0};
      if (STS_15_0 !== exp) begin
        errors = errors + 1;
        $display(
            "FAIL step: FIDBO=%04h CSTS=%b LDPILN=%b MI=%b OVF=%b CRY=%b got STS=%04h expected %04h",
            fidbo, csts, ldpiln, mi, ovf, cry, STS_15_0, exp);
      end
    end
  endtask

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_ALU_STS_tb: FPGA_FF_MODE (sysclk+ALUCLK_EN capture)");
`else
    $display("CGA_ALU_STS_tb: latch/CP mode (posedge ALUCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Directed vectors, constants from gen_tier3_alu_golden.py.
    // ------------------------------------------------------------------
      step(16'h0000, 2'd3, 1'b0, 1'b0, 1'b0, 1'b0, 16'h0000);
      step(16'h00FF, 2'd1, 1'b1, 1'b0, 1'b0, 1'b0, 16'h0000);
      step(16'h0000, 2'd1, 1'b1, 1'b0, 1'b0, 1'b1, 16'h0040);
      step(16'h0000, 2'd1, 1'b1, 1'b0, 1'b1, 1'b0, 16'h0030);
      step(16'h0000, 2'd1, 1'b1, 1'b0, 1'b0, 1'b0, 16'h0020);
      step(16'h0000, 2'd0, 1'b1, 1'b1, 1'b1, 1'b1, 16'h0020);
      step(16'h0000, 2'd2, 1'b1, 1'b1, 1'b0, 1'b0, 16'h00A0);
      step(16'h0000, 2'd2, 1'b1, 1'b0, 1'b0, 1'b0, 16'h0020);
      step(16'hFFFF, 2'd3, 1'b0, 1'b0, 1'b0, 1'b0, 16'hFFFF);
      step(16'hFFFF, 2'd1, 1'b1, 1'b0, 1'b0, 1'b0, 16'hFFAF);
      step(16'hFFFF, 2'd2, 1'b1, 1'b0, 1'b1, 1'b1, 16'hFF2F);
      step(16'hFFFF, 2'd0, 1'b1, 1'b0, 1'b0, 1'b0, 16'hFF2F);
      step(16'hA5C3, 2'd3, 1'b1, 1'b0, 1'b0, 1'b0, 16'hFFC3);
      step(16'h3C5A, 2'd0, 1'b0, 1'b1, 1'b1, 1'b1, 16'h3CC3);
      step(16'h0000, 2'd3, 1'b0, 1'b0, 1'b0, 1'b0, 16'h0000);
      step(16'hFFFF, 2'd3, 1'b1, 1'b1, 1'b1, 1'b1, 16'h00FF);
      step(16'h0F0F, 2'd0, 1'b0, 1'b0, 1'b0, 1'b0, 16'h0FFF);
      step(16'h0020, 2'd3, 1'b0, 1'b0, 1'b0, 1'b0, 16'h0020);
      step(16'h0000, 2'd1, 1'b1, 1'b0, 1'b0, 1'b0, 16'h0020);
      step(16'h0000, 2'd3, 1'b0, 1'b0, 1'b0, 1'b0, 16'h0000);
      step(16'h0000, 2'd1, 1'b1, 1'b1, 1'b0, 1'b0, 16'h0000);
      step(16'hFFFF, 2'd1, 1'b0, 1'b1, 1'b1, 1'b1, 16'hFF70);
    ms = 16'hFF70;

    // ------------------------------------------------------------------
    // 2. 4096 fixed-seed LFSR steps (all inputs random) vs the model.
    // ------------------------------------------------------------------
    lfsr = 32'h53545321;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      ms   = snext(ms, lfsr[15:0], lfsr[17:16], lfsr[18], lfsr[19],
                   lfsr[20], lfsr[21]);
      step(lfsr[15:0], lfsr[17:16], lfsr[18], lfsr[19], lfsr[20],
           lfsr[21], ms);
    end

    // ------------------------------------------------------------------
    // 3. Hold without a clock event: change inputs, wait, STS unchanged.
    //    (Python-computed final state: F777.)
    // ------------------------------------------------------------------
    FIDBO_15_0 = 16'h1234;
    CSTS_1_0   = 2'd3;
    LDPILN     = 1'b0;
    MI         = 1'b1;
    OVF        = 1'b1;
    CRY        = 1'b1;
    #40;
    checks = checks + 1;
    if (STS_15_0 !== 16'hF777) begin
      errors = errors + 1;
      $display("FAIL hold: got STS=%04h expected F777 (no clock event)",
               STS_15_0);
    end
    FIDBO_15_0 = 16'hEDCB;
    CSTS_1_0   = 2'd1;
    #40;
    checks = checks + 1;
    if (STS_15_0 !== 16'hF777) begin
      errors = errors + 1;
      $display("FAIL hold2: got STS=%04h expected F777 (no clock event)",
               STS_15_0);
    end

    // ------------------------------------------------------------------
    // 4. Whole-sequence checksum vs the independent Python model.
    // ------------------------------------------------------------------
    checks = checks + 1;
    if (acc !== 32'h3BF3DDBB) begin
      errors = errors + 1;
      $display("FAIL checksum: got %08h expected 3BF3DDBB", acc);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 22 + 4096 steps + 2 hold + 1 cks = 4121.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4121)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4121 checks)",
               errors, checks);
    $finish;
  end

endmodule
