/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_ALU_SHIFT testbench                                               **
**                                                                       **
** EXHAUSTIVE verification of the 16-bit shift network. The full input   **
** space is exactly 2^20 (ALUI7, ALUI8N, RLI, RRI, F[15:0]) - small      **
** enough to sweep completely, so NO LFSR split is needed:               **
**                                                                       **
**  1. Directed golden vectors (12, generated by the independent Python  **
**     model gen_alu_tier1_golden.py) with explicit expected constants.  **
**  2. Exhaustive sweep: all 1048576 input combinations, i.e. every      **
**     select value {ALUI8N,ALUI7} x every serial-input combination      **
**     {RLI,RRI} x all 65536 F values, checked against the independent   **
**     model. (The SHIFT path had a real historical bug - CGA_CPU_ALU_   **
**     CONTR fed it wrong SSEL values - and the serial inputs ROT/ZIN/   **
**     LIN arrive here as RLI/RRI, so every select x serial combo is     **
**     covered by construction.)                                         **
**                                                                       **
** Model derivation, read gate-by-gate: each bit is a MUX31LP with       **
** sel = {B=ALUI8N, A=ALUI7}, D3 tied to D2 inside MUX31LP, and          **
** ZN = ~mux; the module re-inverts (RB[i] = ~ZN), so RB[i] = mux:       **
**   sel=00 (ALUI8N=0,ALUI7=0): D0 -> RIGHT shift: RB[i]=F[i+1],         **
**                                     RB[15]=RRI                        **
**   sel=01 (ALUI8N=0,ALUI7=1): D1 -> LEFT shift:  RB[i]=F[i-1],         **
**                                     RB[0]=RLI                         **
**   sel=1x (ALUI8N=1)        : D2 -> pass-through: RB=F                 **
**                                                                       **
** Pure combinational module (MUX31LP/Multiplexer_4 has no FF/latch      **
** primitives) - a single build mode covers it.                          **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_ALU_SHIFT_tb;

  reg         ALUI7 = 0;
  reg         ALUI8N = 0;
  reg  [15:0] F_15_0 = 0;
  reg         RLI = 0;
  reg         RRI = 0;
  wire [15:0] RB_15_0;

  integer errors = 0;
  integer checks = 0;
  integer idx;
  reg [15:0] exp;

  CGA_ALU_SHIFT dut (
      .ALUI7  (ALUI7),
      .ALUI8N (ALUI8N),
      .F_15_0 (F_15_0),
      .RLI    (RLI),
      .RRI    (RRI),
      .RB_15_0(RB_15_0)
  );

  // Independent model (see header derivation).
  function [15:0] model(input alui7_in, input alui8n_in,
                        input [15:0] f_in, input rli_in, input rri_in);
    begin
      if (alui8n_in)
        model = f_in;                       // pass-through
      else if (alui7_in)
        model = {f_in[14:0], rli_in};       // left shift, RLI into bit 0
      else
        model = {rri_in, f_in[15:1]};       // right shift, RRI into bit 15
    end
  endfunction

  task check(input [255:0] name);
    begin
      #1;
      checks = checks + 1;
      exp = model(ALUI7, ALUI8N, F_15_0, RLI, RRI);
      if (RB_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: ALUI7=%b ALUI8N=%b RLI=%b RRI=%b F=%04h got RB=%04h expected %04h",
                 name, ALUI7, ALUI8N, RLI, RRI, F_15_0, RB_15_0, exp);
      end
    end
  endtask

  task dir_vec(input alui7_in, input alui8n_in, input [15:0] f_in,
               input rli_in, input rri_in, input [15:0] e_in);
    begin
      ALUI7 = alui7_in; ALUI8N = alui8n_in; F_15_0 = f_in;
      RLI = rli_in; RRI = rri_in;
      #1;
      checks = checks + 1;
      if (RB_15_0 !== e_in) begin
        errors = errors + 1;
        $display("FAIL dir: ALUI7=%b ALUI8N=%b RLI=%b RRI=%b F=%04h got RB=%04h expected %04h",
                 alui7_in, alui8n_in, rli_in, rri_in, f_in, RB_15_0, e_in);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_tier1_golden.py.
    // ------------------------------------------------------------------
      dir_vec(1'b0, 1'b1, 16'hA5C3, 1'b0, 1'b0, 16'hA5C3);
      dir_vec(1'b1, 1'b1, 16'hA5C3, 1'b1, 1'b1, 16'hA5C3);
      dir_vec(1'b0, 1'b0, 16'h0001, 1'b0, 1'b0, 16'h0000);
      dir_vec(1'b0, 1'b0, 16'h0001, 1'b0, 1'b1, 16'h8000);
      dir_vec(1'b0, 1'b0, 16'hFFFF, 1'b0, 1'b0, 16'h7FFF);
      dir_vec(1'b0, 1'b0, 16'h8000, 1'b0, 1'b1, 16'hC000);
      dir_vec(1'b1, 1'b0, 16'h8000, 1'b0, 1'b0, 16'h0000);
      dir_vec(1'b1, 1'b0, 16'h8000, 1'b1, 1'b0, 16'h0001);
      dir_vec(1'b1, 1'b0, 16'hFFFF, 1'b0, 1'b0, 16'hFFFE);
      dir_vec(1'b1, 1'b0, 16'h0001, 1'b1, 1'b1, 16'h0003);
      dir_vec(1'b0, 1'b0, 16'hA5C3, 1'b1, 1'b1, 16'hD2E1);
      dir_vec(1'b1, 1'b0, 16'hA5C3, 1'b1, 1'b1, 16'h4B87);

    // ------------------------------------------------------------------
    // 2. Exhaustive sweep of the entire 2^20 input space:
    //    idx[19]=ALUI8N idx[18]=ALUI7 idx[17]=RLI idx[16]=RRI
    //    idx[15:0]=F. Covers every select x serial-input combination
    //    with every F value.
    // ------------------------------------------------------------------
    for (idx = 0; idx < 1048576; idx = idx + 1) begin
      ALUI8N = idx[19];
      ALUI7  = idx[18];
      RLI    = idx[17];
      RRI    = idx[16];
      F_15_0 = idx[15:0];
      check("sweep");
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 12 directed + 1048576 sweep = 1048588.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 1048588)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 1048588 checks)",
               errors, checks);
    $finish;
  end

endmodule
