/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_CPU_ALU_RMUX testbench                                            **
**                                                                       **
** Verification of the 16-bit register mux (inverting AND-OR select).    **
** Full input space is 2^34 (A,D,RA,RD) - too large to sweep, so the     **
** coverage is split (per-slice exhaustive + fixed-seed LFSR):           **
**                                                                       **
**  1. Directed golden vectors (10, generated by the independent Python  **
**     model gen_alu_tier1_golden.py) with explicit expected constants.  **
**  2. Per-slice exhaustive: 16 identical RMUX_Gates slices sharing only **
**     RA/RD. For each slice i, all 16 {RA,RD,A[i],D[i]} combos on an    **
**     all-zeros AND an all-ones background, checking the FULL 16-bit    **
**     output each time (proves slice equivalence, catches cross-slice   **
**     wiring swaps). 16 x 16 x 2 = 512 checks.                          **
**  3. Full-width fixed-seed LFSR vectors: 4096 {A,D} pairs (32-bit      **
**     Fibonacci LFSR, taps 32/22/2/1, seed ACE10001, identical code in  **
**     gen_alu_tier1_golden.py) with RA/RD cycling all 4 combos, checked **
**     against the independent model, PLUS one running-sum checksum      **
**     check against the Python-computed constant 32'h0910BFE2.          **
**                                                                       **
** Model derivation, read gate-by-gate from RMUX_Gates.v (all            **
** BubblesMask=2'b00, no inversions on gate inputs):                     **
**   GATES_1 = A&RA, GATES_2 = D&RD, RN = NOR(GATES_1,GATES_2)           **
**   -> RN[i] = ~((A[i]&RA) | (D[i]&RD))   (output is INVERTED)          **
**                                                                       **
** Pure combinational module (AND_GATE/NOR_GATE are assign-only, no      **
** FF/latch primitives) - a single build mode covers it.                 **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_CPU_ALU_RMUX_tb;

  reg  [15:0] A_15_0 = 0;
  reg  [15:0] D_15_0 = 0;
  reg         RA = 0;
  reg         RD = 0;
  wire [15:0] RN_15_0;

  integer errors = 0;
  integer checks = 0;
  integer i, c, k;
  reg [31:0] lfsr;
  reg [31:0] cksum;
  reg        fb;
  reg [15:0] exp;

  CGA_CPU_ALU_RMUX dut (
      .A_15_0 (A_15_0),
      .D_15_0 (D_15_0),
      .RA     (RA),
      .RD     (RD),
      .RN_15_0(RN_15_0)
  );

  // Independent model: RN = ~((A & {16{RA}}) | (D & {16{RD}})).
  function [15:0] model(input [15:0] a_in, input [15:0] d_in,
                        input ra_in, input rd_in);
    begin
      model = ~((a_in & {16{ra_in}}) | (d_in & {16{rd_in}}));
    end
  endfunction

  task check(input [255:0] name);
    begin
      #1;
      checks = checks + 1;
      exp = model(A_15_0, D_15_0, RA, RD);
      if (RN_15_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: A=%04h D=%04h RA=%b RD=%b got RN=%04h expected %04h",
                 name, A_15_0, D_15_0, RA, RD, RN_15_0, exp);
      end
    end
  endtask

  task dir_vec(input [15:0] a_in, input [15:0] d_in, input ra_in,
               input rd_in, input [15:0] e_in);
    begin
      A_15_0 = a_in; D_15_0 = d_in; RA = ra_in; RD = rd_in;
      #1;
      checks = checks + 1;
      if (RN_15_0 !== e_in) begin
        errors = errors + 1;
        $display("FAIL dir: A=%04h D=%04h RA=%b RD=%b got RN=%04h expected %04h",
                 a_in, d_in, ra_in, rd_in, RN_15_0, e_in);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_alu_tier1_golden.py.
    // ------------------------------------------------------------------
      dir_vec(16'h0000, 16'h0000, 1'b0, 1'b0, 16'hFFFF);
      dir_vec(16'hFFFF, 16'hFFFF, 1'b0, 1'b0, 16'hFFFF);
      dir_vec(16'hFFFF, 16'h0000, 1'b1, 1'b0, 16'h0000);
      dir_vec(16'h0000, 16'hFFFF, 1'b0, 1'b1, 16'h0000);
      dir_vec(16'hAA55, 16'h0000, 1'b1, 1'b0, 16'h55AA);
      dir_vec(16'h0000, 16'h5AA5, 1'b0, 1'b1, 16'hA55A);
      dir_vec(16'h1234, 16'h4321, 1'b1, 1'b1, 16'hACCA);
      dir_vec(16'hF0F0, 16'h0F0F, 1'b1, 1'b1, 16'h0000);
      dir_vec(16'h8001, 16'h7FFE, 1'b1, 1'b0, 16'h7FFE);
      dir_vec(16'h8001, 16'h7FFE, 1'b0, 1'b1, 16'h8001);

    // ------------------------------------------------------------------
    // 2. Per-slice exhaustive, both backgrounds, full-width check.
    //    c[3]=RA c[2]=RD c[1]=A[i] c[0]=D[i].
    // ------------------------------------------------------------------
    for (i = 0; i < 16; i = i + 1) begin
      for (c = 0; c < 16; c = c + 1) begin
        // background all zeros
        RA = c[3]; RD = c[2];
        A_15_0 = {15'h0000, c[1]} << i;
        D_15_0 = {15'h0000, c[0]} << i;
        check("slice-bg0");
        // background all ones
        RA = c[3]; RD = c[2];
        A_15_0 = ~(({15'h0000, ~c[1]}) << i);
        D_15_0 = ~(({15'h0000, ~c[0]}) << i);
        check("slice-bg1");
      end
    end

    // ------------------------------------------------------------------
    // 3. 4096 fixed-seed LFSR full-width vectors + Python checksum.
    // ------------------------------------------------------------------
    lfsr  = 32'hACE10001;
    cksum = 32'h0;
    for (k = 0; k < 4096; k = k + 1) begin
      fb   = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0];
      lfsr = {lfsr[30:0], fb};
      A_15_0 = lfsr[31:16];
      D_15_0 = lfsr[15:0];
      RA     = k[0];
      RD     = k[1];
      check("lfsr");
      cksum = cksum + {16'h0000, RN_15_0};
    end
    checks = checks + 1;
    if (cksum !== 32'h0910BFE2) begin
      errors = errors + 1;
      $display("FAIL cksum: got %08h expected 0910BFE2", cksum);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 10 directed + 512 slice + 4096 LFSR + 1 = 4619.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4619)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4619 checks)",
               errors, checks);
    $finish;
  end

endmodule
