/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_INTR_CNTLR_CLR_CLRBIT testbench                                   **
**                                                                       **
** Exhaustive verification of the per-bit clear-decode cell (page 82):  **
** all 64 input combinations {DATA,DCDJ,DCDK,X0,X1,X2} checked against a **
** golden table generated by an independent gate-by-gate model           **
** (scratchpad gen_tier1_golden.py; the gate reading                     **
**   BIT = (DCDJ & DCDK) | (DCDJ & DATA) | (DCDK & X0 & X1 & X2)         **
** - three NANDs with BubblesMask 0 into an OR3 with BubblesMask 111 -   **
** matched the behavioral form on all 64 combinations).                  **
**                                                                       **
** Pure combinational (logisim gates only, no FF/latch primitives): a    **
** single build mode covers it - run via the generic iv-% rule:          **
**   make iv-CGA_INTR_CNTLR_CLR_CLRBIT                                   **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_INTR_CNTLR_CLR_CLRBIT_tb;

  reg DATA = 0;
  reg DCDJ = 0;
  reg DCDK = 0;
  reg X0 = 0;
  reg X1 = 0;
  reg X2 = 0;

  wire BIT;

  integer errors = 0;
  integer checks = 0;
  integer idx;
  reg expected;

  // Golden table, bit index = {DATA,DCDJ,DCDK,X0,X1,X2}
  // (generated by gen_tier1_golden.py, independent of the DUT netlist)
  localparam [63:0] GOLDEN = 64'hFFFF8000FF008000;

  CGA_INTR_CNTLR_CLR_CLRBIT dut (
      .DATA(DATA),
      .DCDJ(DCDJ),
      .DCDK(DCDK),
      .X0(X0),
      .X1(X1),
      .X2(X2),
      .BIT(BIT)
  );

  initial begin
    for (idx = 0; idx < 64; idx = idx + 1) begin
      {DATA, DCDJ, DCDK, X0, X1, X2} = idx[5:0];
      #2;
      expected = GOLDEN[idx];
      checks = checks + 1;
      if (BIT !== expected) begin
        errors = errors + 1;
        $display("FAIL idx=%02o: BIT=%b expected %b (DATA=%b DCDJ=%b DCDK=%b X0=%b X1=%b X2=%b)",
                 idx[5:0], BIT, expected, DATA, DCDJ, DCDK, X0, X1, X2);
      end
    end

    if (errors == 0 && checks == 64)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 64 checks)", errors, checks);
    $finish;
  end

endmodule
