# ND120 Tang Nano 20K - build wrapper (Windows PowerShell) - Gowin EDA flow
# (BACKUP toolchain; the primary flow is the OSS suite via `make` in this
#  dir - see docs/tang20k-build-flows.md)
#
#   cd E:\Dev\Repos\Ronny\nd-120\Verilog\fpga\tang-nano-20k
#   .\gowin_build.ps1 [-Variant slow|crawl|full] [-Gao] [-PfCapture] [-PcHistory] [-JplCapture] [-PanelClock]
#
# -Variant selects the clocking (default slow, same as always):
#   slow  = CPU 6.75 MHz / SDRAM 13.5 MHz
#   crawl = CPU 3.375 MHz / SDRAM 6.75 MHz
#   mid   = CPU 13.5 MHz / SDRAM 27 MHz
#   full  = CPU 27 MHz / SDRAM 54 MHz  (BREAKS: s3 hangs, 1667 setup violations)
# It is applied by generating build\tang20k_variant.v (a TANG_VARIANT_*
# pre-define consumed by src/tang20k_defines.v) which gowin_build.tcl adds
# as the FIRST project file - the same mechanism the OSS Makefile uses via
# -D flags, so both toolchains share one source of truth.
#
# Copies the WCS preload images (SKIP_WCS_LOAD - the $readmemh files must be
# reachable from the synthesis working dir), then runs gw_sh on
# gowin_build.tcl.
# Bitstream: build\nd120_tang20k_build\impl\pnr\nd120_tang20k_build.fs

# -PfCapture builds in the FIRST PAGE-FAULT FREEZE REGISTER (TANG_PF_CAPTURE).
#   It captures the trap-logic inputs at the TCLK edge that latched a page-fault
#   vector, then LOCKS, and streams the frozen word out through XMIC_DBG as four
#   14-bit slices. Use it to answer whether the page fault that halts SINTRAN is
#   real - see PLAN-pagefault-root-cause.md in this directory.
#   WARNING: while it is set, XMIC_DBG carries the capture readout and NOT the
#   microsequencer address-advance probe, so the other TANG_*_CAPTURE decodes do
#   not apply to that word.

param(
    [ValidateSet("slow", "crawl", "mid", "full", "fast20")]
    [string]$Variant = "slow",
    [switch]$Gao,
    [switch]$PfCapture,
    [switch]$PcHistory,
    [switch]$JplCapture,
    [switch]$PtwrCapture,
    [switch]$DiscsUncached,
    [switch]$NoStorageCache,
    [switch]$PfPath,
    [switch]$PtOrder,
    [switch]$PfLog,
    [switch]$PgWrite,
    [switch]$StageTimer,
    [switch]$PanelClock
)

$ErrorActionPreference = "Stop"

$gwsh = "C:\Utils\Gowin\Gowin_V1.9.10.02_x64\IDE\bin\gw_sh.exe"
if (-not (Test-Path $gwsh)) {
    Write-Error "gw_sh.exe not found at $gwsh - adjust the path in this script."
}

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$wcs  = Join-Path $here "..\..\..\Code\Microcode\wcs"
if (-not (Test-Path (Join-Path $wcs "wcs_16C.hex"))) {
    Write-Error "WCS preload images not found in $wcs - run Code/Microcode/gen_wcs_image.py first."
}

# $readmemh path resolution differs between tool versions: put the hex files
# in every plausible working directory.
$buildDir = Join-Path $here "build"
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null
foreach ($dest in @($here, $buildDir)) {
    Copy-Item (Join-Path $wcs "wcs_*.hex") -Destination $dest -Force
}
Write-Host "WCS preload images copied (32 files)."

# Variant selection file - ALWAYS (re)written so builds are stateless.
# gowin_build.tcl adds it as the first project file.
$variantFile = Join-Path $buildDir "tang20k_variant.v"
switch ($Variant) {
    "full"  { $variantContent = "// generated by gowin_build.ps1 - do not edit`n``define TANG_VARIANT_FULL`n" }
    "crawl" { $variantContent = "// generated by gowin_build.ps1 - do not edit`n``define TANG_VARIANT_CRAWL`n" }
    "mid"   { $variantContent = "// generated by gowin_build.ps1 - do not edit`n``define TANG_VARIANT_MID`n" }
    "fast20" { $variantContent = "// generated by gowin_build.ps1 - do not edit`n``define TANG_VARIANT_FAST20`n" }
    default { $variantContent = "// generated by gowin_build.ps1 - do not edit`n// slow bring-up (default): no variant define`n" }
}
# Diagnostic defines ride in the same generated file, so a build is stateless:
# not passing the switch REMOVES the define rather than leaving it latched on.
if ($PfCapture) {
    $variantContent += "``define TANG_PF_CAPTURE`n"
    Write-Host "PF CAPTURE: ENABLED - XMIC_DBG carries the page-fault freeze readout"
}
if ($PcHistory) {
    if ($PfCapture) {
        Write-Error "-PcHistory and -PfCapture are MUTUALLY EXCLUSIVE. There is one 16-bit debug port out of the CGA and both probes drive it; defining both gives two drivers and gw_sh stops with EX2000 'constantly driven from multiple places'."
        exit 1
    }
    $variantContent += "``define TANG_PC_HISTORY`n"
    Write-Host "PC HISTORY: ENABLED - XMIC_DBG carries the P register; the ring records {PIL,P}"
    Write-Host "            and freezes on an access to the ND-500 window page (raw PNUMB 0o1360)."
    Write-Host "            Decode the dump with pc_history_decode.py"
}
if ($JplCapture) {
    if ($PfCapture -or $PcHistory) {
        Write-Error "-JplCapture is MUTUALLY EXCLUSIVE with -PfCapture and -PcHistory. There is one 16-bit debug port out of the CGA and one capture ring; defining more than one gives two drivers and gw_sh stops with EX2000 'constantly driven from multiple places'."
        exit 1
    }
    $variantContent += "``define TANG_JPL_CAPTURE`n"
    Write-Host "JPL CAPTURE: ENABLED - the ring records the address bus, FIDBO and the"
    Write-Host "             program counter across the two JPL I 111 instructions at"
    Write-Host "             064544/064545. Decode with jpl_capture_decode.py"
}
if ($PtwrCapture) {
    if ($PfCapture -or $PcHistory -or $JplCapture) {
        Write-Error "-PtwrCapture is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring."
        exit 1
    }
    $variantContent += "``define TANG_PTWR_CAPTURE`n"
    Write-Host "PTWR CAPTURE: ENABLED - the ring records the last ~256 page-table WRITES"
    Write-Host "              (raw index + entry data, two words each) before the ERRFATAL"
    Write-Host "              trigger. Source = DBG_PTW from CPU_MMU_24. Decode with"
    Write-Host "              ptwr_capture_decode.py"
}
if ($PfPath) {
    if ($PfCapture -or $PcHistory -or $JplCapture -or $PtwrCapture) {
        Write-Error "-PfPath is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring, one debug port."
        exit 1
    }
    $variantContent += "``define TANG_PFPATH_CAPTURE`n"
    Write-Host "PFPATH CAPTURE: ENABLED - {PIL,P} ring of the page-fault handler path after the"
    Write-Host "               first no-permit access to raw page 0o1032; freezes on the return to"
    Write-Host "               level 1. Decode with pc_history_decode.py (same {PIL,P} word format)."
}
if ($PtOrder) {
    if ($PfCapture -or $PcHistory -or $JplCapture -or $PtwrCapture -or $PfPath) {
        Write-Error "-PtOrder is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring, one debug port."
        exit 1
    }
    $variantContent += "``define TANG_PTORD_CAPTURE`n"
    Write-Host "PTORD CAPTURE: ENABLED - one ring, in time order: page-table writes at raw"
    Write-Host "               index 0o1032 (tag B) interleaved with no-permit-access markers"
    Write-Host "               (tag C) and fault markers (tag D) at that same page. Answers"
    Write-Host "               whether a no-permit access happens AFTER the granting write."
}
if ($PfLog) {
    if ($PfCapture -or $PcHistory -or $JplCapture -or $PtwrCapture -or $PfPath -or $PtOrder) {
        Write-Error "-PfLog is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring, one debug port."
        exit 1
    }
    $variantContent += "``define TANG_PFLOG_CAPTURE`n"
    Write-Host "PFLOG CAPTURE: ENABLED - one record per page fault at ANY address"
    Write-Host "               (page index + page-table entry), frozen by the ERRFATAL"
    Write-Host "               printer. The LAST records are the fault that halts."
    Write-Host "               Decode with pflog_capture_decode.py"
}
if ($PgWrite) {
    if ($PfCapture -or $PcHistory -or $JplCapture -or $PtwrCapture -or $PfPath -or $PtOrder -or $PfLog) {
        Write-Error "-PgWrite is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring, one debug port."
        exit 1
    }
    $variantContent += "``define TANG_PGW_CAPTURE`n"
    Write-Host "PGW CAPTURE: ENABLED - every SDRAM-bridge access to physical rows"
    Write-Host "             1016..1023 (both banks), i.e. the page the CPU fetches"
    Write-Host "             zeros from. Answers whether ANY write ever reached it."
    Write-Host "             Decode with pgw_capture_decode.py"
}
if ($StageTimer) {
    if ($PfCapture -or $PcHistory -or $JplCapture -or $PtwrCapture -or $PfPath -or $PtOrder -or $PfLog -or $PgWrite) {
        Write-Error "-StageTimer is MUTUALLY EXCLUSIVE with the other capture switches - one capture ring."
        exit 1
    }
    $variantContent += "``define TANG_STAGE_TIMER`n"
    Write-Host "STAGE TIMER: ENABLED - accumulates ticks per disc-operation stage"
    Write-Host "             (Winchester active, DMA, SD read, cache lookup) and"
    Write-Host "             dumps the totals. Answers where a disc operation's"
    Write-Host "             ~1 s actually goes. Decode with stage_timer_decode.py"
}
if ($DiscsUncached) {
    # ND_STORAGE_DISCS_UNCACHED (nd_storage_devices.v, 09-AUG diagnostic
    # lever): every disc client DIRECT - each request goes through the shared
    # staging line, no cache reuse. Functionality + performance experiment:
    # does the boot failure change, and how much slower is the boot?
    $variantContent += "``define ND_STORAGE_DISCS_UNCACHED`n"
    Write-Host "STORAGE CACHE: OFF (ND_STORAGE_DISCS_UNCACHED) - all disc clients DIRECT"
}
if ($NoStorageCache) {
    # Stronger variant: the cache directory is NOT SYNTHESIZED (nd_storage.v
    # ND_STORAGE_NO_CACHE). Requires every client DIRECT - a cached client
    # would wait forever on lookup_done - so this switch FORCES the mask off.
    if (-not $DiscsUncached) {
        $variantContent += "``define ND_STORAGE_DISCS_UNCACHED`n"
        Write-Host "STORAGE CACHE: mask forced OFF (required by -NoStorageCache)"
    }
    $variantContent += "``define ND_STORAGE_NO_CACHE`n"
    Write-Host "STORAGE CACHE: NOT SYNTHESIZED (ND_STORAGE_NO_CACHE)"
}
if ($PanelClock) {
    # ND120_PANEL_CLOCK (IO_PANCAL_40.v -> PANCAL_68705_CLOCK.v): emulate the
    # MC68705 panel processor's CLOCK path so SINTRAN can set and read the
    # hardware clock through TRR PANC / TRA PANS (PFUNC 4-7, half-days +
    # seconds since 1979). OPT-IN: a few hundred extra flops on a device that
    # is nearly full - check the utilisation and timing report after enabling.
    $variantContent += "``define ND120_PANEL_CLOCK`n"
    Write-Host "PANEL CLOCK: ENABLED (ND120_PANEL_CLOCK) - 68705/MM58274 clock path emulated"
}
Set-Content -Path $variantFile -Value $variantContent -Encoding Ascii
# In a PowerShell double-quoted string the backtick is the ESCAPE character, so
# "`define" silently emits "define" and the generated file is INVALID Verilog -
# gw_sh then fails ten minutes later with a confusing "Expecting endmodule".
# A literal backtick needs TWO. Verify rather than trust.
$vc = Get-Content -Path $variantFile -Raw
if ($vc -match '(?m)^\s*define\s') {
    Write-Error "build\tang20k_variant.v contains 'define' without a backtick - the PowerShell escape ate it. Use `` `` in the string."
    exit 1
}
Write-Host "Variant: $Variant (build\tang20k_variant.v)"

# GAO (on-chip logic analyzer) - opt-in, stateless like the variant file:
# -Gao writes build\gao_enable.flag, which makes gowin_build.tcl add
# src\nd120_tang20k_gao.rao (RTL-mode AO core, CGA_INTR grant chain).
# Without -Gao the flag is REMOVED, so a plain build is always GAO-free.
# Capture workflow: see GAO-HOWTO.md in this directory.
$gaoFlag = Join-Path $buildDir "gao_enable.flag"
if ($Gao) {
    Set-Content -Path $gaoFlag -Value "enabled" -Encoding Ascii
    Write-Host "GAO: ENABLED (src\nd120_tang20k_gao.rao will be inserted)"
} else {
    Remove-Item $gaoFlag -ErrorAction SilentlyContinue
}

& $gwsh (Join-Path $here "gowin_build.tcl")
if ($LASTEXITCODE -ne 0) {
    Write-Error "gw_sh failed with exit code $LASTEXITCODE"
}

# A build with an empty WCS is a dead CPU - fail loudly if the preload
# images were not found during synthesis (EX3988).
$synLog = Join-Path $here "build\nd120_tang20k_build\impl\gwsynthesis\nd120_tang20k_build.log"
if (Test-Path $synLog) {
    $miss = Select-String -Path $synLog -Pattern "EX3988" | Measure-Object
    if ($miss.Count -gt 0) {
        Write-Error "WCS preload FAILED: $($miss.Count) 'Cannot open file' (EX3988) warnings in the synthesis log - the control store is EMPTY. Do not flash this bitstream."
    } else {
        Write-Host "WCS preload OK (no EX3988 in synthesis log)."
    }
}

$fs = Join-Path $here "build\nd120_tang20k_build\impl\pnr\nd120_tang20k_build.fs"
if (Test-Path $fs) {
    Write-Host "Bitstream: $fs"
    Write-Host "Program (volatile SRAM):  openFPGALoader -b tangnano20k <fs>   (WSL, usbipd)"
    Write-Host "  or use the Gowin Programmer GUI on Windows."
} else {
    Write-Warning "Bitstream not found - check the synthesis/PnR logs under build\"
}
