# ND120 Tang Nano 20K - Gowin gw_sh build script
#
# Run on the Windows host (like the Vivado flow):
#   gw_sh.exe gowin_build.tcl        (or use gowin_build.ps1, which also
#                                     copies the WCS preload hex files)
#
# Creates a throwaway project under build/ from the SAME file list as the
# GUI project (nd120_tang20k.gprj is parsed, so there is one source of
# truth), then runs synthesis + place&route.
# Bitstream: build/impl/pnr/nd120_tang20k_build.fs

set proj_dir [file dirname [file normalize [info script]]]

create_project -name nd120_tang20k_build -dir $proj_dir/build \
    -pn GW2AR-LV18QN88C8/I7 -device_version C -force

# Clock-variant pre-defines (generated by gowin_build.ps1 -Variant ...):
# must be the FIRST file so its `defines reach the whole compilation unit
# (src/tang20k_defines.v keys its TANG_SLOW/CRAWL selection off them).
# Absent file = slow bring-up default, same as always.
if {[file exists "$proj_dir/build/tang20k_variant.v"]} {
    add_file [file normalize "$proj_dir/build/tang20k_variant.v"]
    puts "Variant define file added (build/tang20k_variant.v)"
}

# One source of truth: pull the file list out of the GUI project file
set fp [open "$proj_dir/nd120_tang20k.gprj" r]
set xml [read $fp]
close $fp

set nfiles 0
foreach {full path} [regexp -all -inline {<File path="([^"]+)"[^>]*enable="1"/>} $xml] {
    add_file [file normalize "$proj_dir/$path"]
    incr nfiles
}
puts "Added $nfiles files from nd120_tang20k.gprj"

set_option -top_module ND120_TANG20K_TOP
set_option -verilog_std v2001
# Congestion relief for the TANG_SMD build: the default placer left 9 nets
# unrouted at CLS 90%. place_option/route_option 1 select Gowin's alternate
# (congestion-driven) placement and routing algorithms.
set_option -place_option 1
set_option -route_option 1

# GAO (Gowin Analyzer Oscilloscope) - opt-in on-chip logic analyzer.
# gowin_build.ps1 -Gao writes build/gao_enable.flag; when present, the
# RTL-mode GAO config src/nd120_tang20k_gao.rao is added and the AO core
# is inserted during synthesis+PnR (taps the CGA_INTR grant chain in the
# clk_cpu domain). Costs ~2 BSRAM + some LUTs. See GAO-HOWTO.md in this
# directory for the capture workflow on the Windows host.
if {[file exists "$proj_dir/build/gao_enable.flag"]} {
    add_file -type gao [file normalize "$proj_dir/src/nd120_tang20k_gao.rao"]
    puts "GAO ENABLED: src/nd120_tang20k_gao.rao (AO debug core will be inserted)"
} else {
    puts "GAO disabled (run gowin_build.ps1 -Gao to enable)"
}

# WCS preload images (SKIP_WCS_LOAD): GowinSynthesis resolves the relative
# $readmemh("wcs_*.hex") paths against its own working directories, NOT the
# script directory - first build failed with EX3988 "Cannot open file" and
# produced an EMPTY control store (dead CPU). Copy the images into every
# directory the tool may use.
set wcs_src [file normalize "$proj_dir/../../../Code/Microcode/wcs"]
set wcs_files [glob -nocomplain "$wcs_src/wcs_*.hex"]
if {[llength $wcs_files] != 33} {
    puts "WARNING: expected 33 wcs hex files in $wcs_src, found [llength $wcs_files]"
}
set dests [list [pwd] \
                $proj_dir \
                $proj_dir/build \
                $proj_dir/build/nd120_tang20k_build \
                $proj_dir/build/nd120_tang20k_build/impl \
                $proj_dir/build/nd120_tang20k_build/impl/gwsynthesis]
foreach d $dests {
    file mkdir $d
    foreach f $wcs_files {
        file copy -force $f $d
    }
}
puts "WCS preload images copied to [llength $dests] candidate directories"

# Print a text timing report for the WNS check
set_option -gen_text_timing_rpt 1

run all
