/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MIC_IPOS testbench                                                **
**                                                                       **
** Verification of the microcode-address source selector (43 input      **
** bits - too wide for an exhaustive sweep; split stated per campaign    **
** convention):                                                          **
**                                                                       **
**  1. 16 directed vectors with expected constants generated by the      **
**     independent Python model gen_mic_golden.py, which implements the  **
**     GATE equations read from the netlist (GATES_1..5 select trees +   **
**     the 13 Multiplexer_4 slices, incl. the separate bit-12 selector   **
**     mux_selector_12).                                                 **
**  2. Exhaustive over the 3-bit control cone {TRAPN,MAPN,EWCAN} (all 8  **
**     combinations) x 44 directed data patterns each: walking-one over  **
**     W (13), WCA (13), CD[15:6] (10), TVEC (4) plus 4 corner           **
**     patterns = 352 vectors.                                           **
**  3. 4096 fixed-seed LFSR full-width random vectors.                   **
**     All checked against the in-tb PRIORITY model, re-derived          **
**     independently by case analysis of the select gates:               **
**       TRAPN=0            -> MA = {9'b0, TVEC}       (trap vector)     **
**       else MAPN=0        -> MA = {3'b011, CD[15:6]} (MAP dispatch)    **
**       else EWCAN=0       -> MA = WCA                (WCS address)     **
**       else               -> MA = W                  (next microPC)    **
**     The Python run proved gate-model == priority-model on 200000      **
**     random vectors (0 mismatches).                                    **
**                                                                       **
** Pure combinational (logisim gates + Multiplexer_4 only, no FF or      **
** latch primitives): a single build mode covers it.                     **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MIC_IPOS_tb;

  reg  [15:0] CD_15_0 = 0;
  reg         EWCAN = 1;
  reg         MAPN = 1;
  reg         TRAPN = 1;
  reg  [ 3:0] TVEC_3_0 = 0;
  reg  [12:0] WCA_12_0 = 0;
  reg  [12:0] W_12_0 = 0;
  wire [12:0] MA_12_0;

  integer errors = 0;
  integer checks = 0;
  integer ctl, k, n;
  reg [31:0] lfsr;

  CGA_MIC_IPOS dut (
      .CD_15_0 (CD_15_0),
      .EWCAN   (EWCAN),
      .MAPN    (MAPN),
      .TRAPN   (TRAPN),
      .TVEC_3_0(TVEC_3_0),
      .WCA_12_0(WCA_12_0),
      .W_12_0  (W_12_0),
      .MA_12_0 (MA_12_0)
  );

  // Independent priority model (see header).
  function [12:0] ipos_gold(input trapn, input mapn, input ewcan,
                            input [3:0] tvec, input [12:0] wca,
                            input [12:0] w, input [15:0] cd);
    begin
      if (!trapn) ipos_gold = {9'b0, tvec};
      else if (!mapn) ipos_gold = {3'b011, cd[15:6]};
      else if (!ewcan) ipos_gold = wca;
      else ipos_gold = w;
    end
  endfunction

  task check_now(input [127:0] name);
    begin
      #2;
      checks = checks + 1;
      if (MA_12_0 !== ipos_gold(TRAPN, MAPN, EWCAN, TVEC_3_0,
                                WCA_12_0, W_12_0, CD_15_0)) begin
        errors = errors + 1;
        $display("FAIL %0s: T/M/E=%b%b%b TVEC=%h WCA=%05o W=%05o CD=%06o got MA=%05o expected %05o",
                 name, TRAPN, MAPN, EWCAN, TVEC_3_0, WCA_12_0, W_12_0,
                 CD_15_0, MA_12_0,
                 ipos_gold(TRAPN, MAPN, EWCAN, TVEC_3_0, WCA_12_0,
                           W_12_0, CD_15_0));
      end
    end
  endtask

  task ipos_vec(input trapn, input mapn, input ewcan, input [3:0] tvec,
                input [12:0] wca, input [12:0] w, input [15:0] cd,
                input [12:0] exp);
    begin
      TRAPN    = trapn;
      MAPN     = mapn;
      EWCAN    = ewcan;
      TVEC_3_0 = tvec;
      WCA_12_0 = wca;
      W_12_0   = w;
      CD_15_0  = cd;
      #2;
      checks = checks + 1;
      if (MA_12_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL directed: T/M/E=%b%b%b got MA=%05o expected %05o",
                 trapn, mapn, ewcan, MA_12_0, exp);
      end
    end
  endtask

  // Galois-style 32-bit LFSR, taps 32,22,2,1 (maximal), fixed seed.
  function [31:0] lfsr_next(input [31:0] x);
    begin
      lfsr_next = {x[30:0], x[31] ^ x[21] ^ x[1] ^ x[0]};
    end
  endfunction

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_mic_golden.py
    //    (gate-equation model - independent of the in-tb priority model).
    // ------------------------------------------------------------------
    ipos_vec(1'b1, 1'b0, 1'b0, 4'h0, 13'o06042, 13'o04674, 16'o161600, 13'o07616);
    ipos_vec(1'b0, 1'b0, 1'b0, 4'hD, 13'o06565, 13'o05463, 16'o027323, 13'o00015);
    ipos_vec(1'b0, 1'b1, 1'b1, 4'h2, 13'o11763, 13'o12210, 16'o101201, 13'o00002);
    ipos_vec(1'b0, 1'b0, 1'b1, 4'h0, 13'o07661, 13'o01005, 16'o040772, 13'o00000);
    ipos_vec(1'b0, 1'b0, 1'b1, 4'h2, 13'o01401, 13'o16727, 16'o012244, 13'o00002);
    ipos_vec(1'b1, 1'b1, 1'b0, 4'hD, 13'o01640, 13'o07142, 16'o122217, 13'o01640);
    ipos_vec(1'b1, 1'b0, 1'b1, 4'hC, 13'o07201, 13'o06241, 16'o001743, 13'o06017);
    ipos_vec(1'b1, 1'b1, 1'b0, 4'hB, 13'o03531, 13'o15144, 16'o006505, 13'o03531);
    ipos_vec(1'b1, 1'b0, 1'b0, 4'h7, 13'o10161, 13'o13504, 16'o030635, 13'o06306);
    ipos_vec(1'b0, 1'b0, 1'b0, 4'h1, 13'o04311, 13'o03263, 16'o002054, 13'o00001);
    ipos_vec(1'b1, 1'b0, 1'b0, 4'h8, 13'o15106, 13'o16337, 16'o022146, 13'o06221);
    ipos_vec(1'b1, 1'b1, 1'b0, 4'h3, 13'o17233, 13'o07543, 16'o047257, 13'o17233);
    ipos_vec(1'b0, 1'b0, 1'b0, 4'hA, 13'o10630, 13'o07103, 16'o043122, 13'o00012);
    ipos_vec(1'b0, 1'b1, 1'b1, 4'h0, 13'o12523, 13'o10350, 16'o107251, 13'o00000);
    ipos_vec(1'b1, 1'b1, 1'b1, 4'hE, 13'o15413, 13'o07440, 16'o071473, 13'o07440);
    ipos_vec(1'b1, 1'b1, 1'b1, 4'h0, 13'o06762, 13'o06631, 16'o124447, 13'o06631);

    // ------------------------------------------------------------------
    // 2. Exhaustive control cone x directed data patterns.
    // ------------------------------------------------------------------
    for (ctl = 0; ctl < 8; ctl = ctl + 1) begin
      TRAPN = ctl[2];
      MAPN  = ctl[1];
      EWCAN = ctl[0];

      // Walking one over W
      WCA_12_0 = 13'o12525;
      CD_15_0  = 16'o052525;
      TVEC_3_0 = 4'hA;
      for (k = 0; k < 13; k = k + 1) begin
        W_12_0 = 13'b1 << k;
        check_now("walk-W");
      end

      // Walking one over WCA
      W_12_0   = 13'o05252;
      CD_15_0  = 16'o125252;
      TVEC_3_0 = 4'h5;
      for (k = 0; k < 13; k = k + 1) begin
        WCA_12_0 = 13'b1 << k;
        check_now("walk-WCA");
      end

      // Walking one over CD[15:6]
      W_12_0   = 13'o17777;
      WCA_12_0 = 13'o00000;
      TVEC_3_0 = 4'h0;
      for (k = 6; k < 16; k = k + 1) begin
        CD_15_0 = 16'b1 << k;
        check_now("walk-CD");
      end

      // Walking one over TVEC
      W_12_0   = 13'o12345;
      WCA_12_0 = 13'o01234;
      CD_15_0  = 16'o054321;
      for (k = 0; k < 4; k = k + 1) begin
        TVEC_3_0 = 4'b1 << k;
        check_now("walk-TVEC");
      end

      // Corner patterns
      W_12_0 = 13'o00000; WCA_12_0 = 13'o00000;
      CD_15_0 = 16'o000000; TVEC_3_0 = 4'h0;
      check_now("corner-0");
      W_12_0 = 13'o17777; WCA_12_0 = 13'o17777;
      CD_15_0 = 16'o177777; TVEC_3_0 = 4'hF;
      check_now("corner-1");
      W_12_0 = 13'o12525; WCA_12_0 = 13'o05252;
      CD_15_0 = 16'o125252; TVEC_3_0 = 4'hA;
      check_now("corner-A");
      W_12_0 = 13'o05252; WCA_12_0 = 13'o12525;
      CD_15_0 = 16'o052525; TVEC_3_0 = 4'h5;
      check_now("corner-5");
    end

    // ------------------------------------------------------------------
    // 3. 4096 fixed-seed LFSR full-width random vectors.
    // ------------------------------------------------------------------
    lfsr = 32'hACE1_2026;
    for (n = 0; n < 4096; n = n + 1) begin
      lfsr = lfsr_next(lfsr);
      {TRAPN, MAPN, EWCAN} = lfsr[2:0];
      TVEC_3_0 = lfsr[6:3];
      WCA_12_0 = lfsr[19:7];
      lfsr = lfsr_next(lfsr);
      W_12_0  = lfsr[12:0];
      CD_15_0 = lfsr[28:13];
      check_now("lfsr");
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 16 directed + 352 pattern + 4096 LFSR = 4464.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 4464)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 4464 checks)",
               errors, checks);
    $finish;
  end

endmodule
