/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MIC_IINC testbench                                                **
**                                                                       **
** Exhaustive verification of the instruction-increment adder:           **
**                                                                       **
**  1. 8 directed vectors with expected constants generated by the       **
**     independent Python model gen_mic_golden.py.                       **
**  2. Exhaustive sweep: all 16384 {CIN, IW[12:0]} combinations. The     **
**     golden model embedded below is NOT the DUT's active               **
**     `IW + CIN` assign - it is the GATE-LEVEL carry-skip adder         **
**     re-derived from the _OLD_WAY_ netlist (the schematic              **
**     transcription): ripple adders for bits 0-4 with dataB(bit0)=CIN   **
**     and the bit-4 carry dropped, lookahead g1n = AND(IW[4:0],CIN)     **
**     injected as dataB of bit 5, bit-9 carry dropped, lookahead        **
**     g2n = AND(IW[9:5],g1n) injected as dataB of bit 10. The Python    **
**     model proved gate-model == (IW+CIN) mod 8192 on all 16384         **
**     combinations (0 mismatches), so the active assign matches the     **
**     schematic gates.                                                  **
**                                                                       **
** Pure combinational (single assign / adder tree, no FF or latch        **
** primitives): a single build mode covers it.                           **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MIC_IINC_tb;

  reg         CIN = 0;
  reg  [12:0] IW_12_0 = 0;
  wire [12:0] NEXT_12_0;

  integer errors = 0;
  integer checks = 0;
  integer idx;

  CGA_MIC_IINC dut (
      .CIN      (CIN),
      .IW_12_0  (IW_12_0),
      .NEXT_12_0(NEXT_12_0)
  );

  // Independent gate-level golden model (see header).
  function [12:0] iinc_gold(input cin, input [12:0] iw);
    reg c, g1n, g2n;
    begin
      iinc_gold = 13'b0;
      {c, iinc_gold[0]} = iw[0] + cin;
      {c, iinc_gold[1]} = iw[1] + c;
      {c, iinc_gold[2]} = iw[2] + c;
      {c, iinc_gold[3]} = iw[3] + c;
      iinc_gold[4] = iw[4] ^ c;  // ARITH_3 carryOut dropped
      g1n = (&iw[4:0]) & cin;
      {c, iinc_gold[5]} = iw[5] + g1n;
      {c, iinc_gold[6]} = iw[6] + c;
      {c, iinc_gold[7]} = iw[7] + c;
      {c, iinc_gold[8]} = iw[8] + c;
      iinc_gold[9] = iw[9] ^ c;  // ARITH_8 carryOut dropped
      g2n = (&iw[9:5]) & g1n;
      {c, iinc_gold[10]} = iw[10] + g2n;
      {c, iinc_gold[11]} = iw[11] + c;
      iinc_gold[12] = iw[12] ^ c;  // ARITH_11 carryOut dropped
    end
  endfunction

  task iinc_vec(input cin, input [12:0] iw, input [12:0] exp);
    begin
      CIN     = cin;
      IW_12_0 = iw;
      #2;
      checks = checks + 1;
      if (NEXT_12_0 !== exp) begin
        errors = errors + 1;
        $display("FAIL directed: CIN=%b IW=%05o got NEXT=%05o expected %05o",
                 cin, iw, NEXT_12_0, exp);
      end
    end
  endtask

  initial begin
    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_mic_golden.py.
    // ------------------------------------------------------------------
    iinc_vec(1'b1, 13'o00414, 13'o00415);
    iinc_vec(1'b0, 13'o04355, 13'o04355);
    iinc_vec(1'b1, 13'o01511, 13'o01512);
    iinc_vec(1'b0, 13'o07215, 13'o07215);
    iinc_vec(1'b1, 13'o15216, 13'o15217);
    iinc_vec(1'b0, 13'o15215, 13'o15215);
    iinc_vec(1'b0, 13'o07436, 13'o07436);
    iinc_vec(1'b0, 13'o02645, 13'o02645);

    // ------------------------------------------------------------------
    // 2. Exhaustive sweep of all 16384 {CIN, IW} combinations vs the
    //    independent gate-level model.
    // ------------------------------------------------------------------
    for (idx = 0; idx < 16384; idx = idx + 1) begin
      CIN     = idx[13];
      IW_12_0 = idx[12:0];
      #2;
      checks = checks + 1;
      if (NEXT_12_0 !== iinc_gold(idx[13], idx[12:0])) begin
        errors = errors + 1;
        $display("FAIL sweep: CIN=%b IW=%05o got NEXT=%05o expected %05o",
                 idx[13], idx[12:0], NEXT_12_0, iinc_gold(idx[13], idx[12:0]));
      end
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 8 directed + 16384 sweep = 16392.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 16392)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 16392 checks)",
               errors, checks);
    $finish;
  end

endmodule
