/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MIC_INCOUNT testbench                                             **
**                                                                       **
** Exhaustive verification of the 2-bit INCOUNT counter/loader:          **
**                                                                       **
**  1. Async preset: a falling MRN edge forces CSWAN1:0 = 11 with no     **
**     clock event, and dominates a simultaneous clocked load.           **
**  2. Load path (LWCAN=0): the load is INVERTING - next CSWANx = ~CDx   **
**     (read pin-by-pin: PLEXERS_4/5 in0 = CDx, FF d = ~mux out). All 4  **
**     CD combinations checked.                                          **
**  3. Exhaustive transition table: every {state, LWCAN, EC, CD1, CD0}   **
**     combination (4 x 16 = 64 transitions, each from a freshly loaded  **
**     and verified state) against the golden table generated by the     **
**     independent Python model gen_mic_golden.py (gate equations        **
**     re-derived from the netlist: count mode is a DOWN counter on      **
**     {CSWAN1,CSWAN0} when EC=1 - Q0 toggles every clock, Q1 toggles    **
**     when Q0==0).                                                      **
**  4. Wrap sequence: 8 consecutive EC counts 00->11->10->01->00->...    **
**  5. Hold without a clock event, and preset from a non-11 state        **
**     followed by a count.                                              **
**                                                                       **
** NOT pure combinational: two D_FLIPFLOP_EN registers clocked by MCLK   **
** (latch/CP mode) or sysclk+MCLK_EN (FPGA_FF_MODE), async preset from   **
** ~MRN. Compile once plain and once with -DFPGA_FF_MODE - the Makefile  **
** target test-mic-incount runs both.                                    **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MIC_INCOUNT_tb;

  reg  sysclk = 0;
  reg  MCLK_EN = 0;
  reg  MCLK = 0;
  reg  CD0 = 0;
  reg  CD1 = 0;
  reg  EC = 0;
  reg  LWCAN = 1;
  reg  MRN = 1;
  wire CSWAN0;
  wire CSWAN1;

  wire [1:0] state = {CSWAN1, CSWAN0};

  integer errors = 0;
  integer checks = 0;
  integer s, v;

  CGA_MIC_INCOUNT dut (
      .sysclk (sysclk),
      .MCLK_EN(MCLK_EN),
      .CD0    (CD0),
      .CD1    (CD1),
      .EC     (EC),
      .LWCAN  (LWCAN),
      .MCLK   (MCLK),
      .MRN    (MRN),
      .CSWAN0 (CSWAN0),
      .CSWAN1 (CSWAN1)
  );

  always #5 sysclk = ~sysclk;

  // One MCLK event, valid in BOTH build modes: the EN-mode register
  // captures at posedge sysclk while MCLK_EN=1; the CP-mode register
  // captures at the posedge of MCLK raised just after the same sysclk
  // edge (inputs stable).
  task pulse_mclk;
    begin
      @(negedge sysclk);
      MCLK_EN = 1;
      @(posedge sysclk);
      #1 MCLK = 1;
      @(negedge sysclk);
      MCLK    = 0;
      MCLK_EN = 0;
    end
  endtask

  task check_state(input [1:0] exp, input [127:0] name);
    begin
      checks = checks + 1;
      if (state !== exp) begin
        errors = errors + 1;
        $display("FAIL %0s: state=%b expected %b (LWCAN=%b EC=%b CD=%b%b)",
                 name, state, exp, LWCAN, EC, CD1, CD0);
      end
    end
  endtask

  // Load state s (inverting load: CD = ~s).
  task load_state(input [1:0] s_in);
    begin
      LWCAN = 0;
      EC    = 0;
      CD0   = ~s_in[0];
      CD1   = ~s_in[1];
      pulse_mclk;
    end
  endtask

  // Golden next-state table from gen_mic_golden.py,
  // key = {Q1,Q0,LWCAN,EC,CD1,CD0}.
  function [1:0] incount_gold(input [5:0] k);
    begin
      case (k)
      6'b000000: incount_gold = 2'b11;
      6'b000001: incount_gold = 2'b10;
      6'b000010: incount_gold = 2'b01;
      6'b000011: incount_gold = 2'b00;
      6'b000100: incount_gold = 2'b11;
      6'b000101: incount_gold = 2'b10;
      6'b000110: incount_gold = 2'b01;
      6'b000111: incount_gold = 2'b00;
      6'b001000: incount_gold = 2'b00;
      6'b001001: incount_gold = 2'b00;
      6'b001010: incount_gold = 2'b00;
      6'b001011: incount_gold = 2'b00;
      6'b001100: incount_gold = 2'b11;
      6'b001101: incount_gold = 2'b11;
      6'b001110: incount_gold = 2'b11;
      6'b001111: incount_gold = 2'b11;
      6'b010000: incount_gold = 2'b11;
      6'b010001: incount_gold = 2'b10;
      6'b010010: incount_gold = 2'b01;
      6'b010011: incount_gold = 2'b00;
      6'b010100: incount_gold = 2'b11;
      6'b010101: incount_gold = 2'b10;
      6'b010110: incount_gold = 2'b01;
      6'b010111: incount_gold = 2'b00;
      6'b011000: incount_gold = 2'b01;
      6'b011001: incount_gold = 2'b01;
      6'b011010: incount_gold = 2'b01;
      6'b011011: incount_gold = 2'b01;
      6'b011100: incount_gold = 2'b00;
      6'b011101: incount_gold = 2'b00;
      6'b011110: incount_gold = 2'b00;
      6'b011111: incount_gold = 2'b00;
      6'b100000: incount_gold = 2'b11;
      6'b100001: incount_gold = 2'b10;
      6'b100010: incount_gold = 2'b01;
      6'b100011: incount_gold = 2'b00;
      6'b100100: incount_gold = 2'b11;
      6'b100101: incount_gold = 2'b10;
      6'b100110: incount_gold = 2'b01;
      6'b100111: incount_gold = 2'b00;
      6'b101000: incount_gold = 2'b10;
      6'b101001: incount_gold = 2'b10;
      6'b101010: incount_gold = 2'b10;
      6'b101011: incount_gold = 2'b10;
      6'b101100: incount_gold = 2'b01;
      6'b101101: incount_gold = 2'b01;
      6'b101110: incount_gold = 2'b01;
      6'b101111: incount_gold = 2'b01;
      6'b110000: incount_gold = 2'b11;
      6'b110001: incount_gold = 2'b10;
      6'b110010: incount_gold = 2'b01;
      6'b110011: incount_gold = 2'b00;
      6'b110100: incount_gold = 2'b11;
      6'b110101: incount_gold = 2'b10;
      6'b110110: incount_gold = 2'b01;
      6'b110111: incount_gold = 2'b00;
      6'b111000: incount_gold = 2'b11;
      6'b111001: incount_gold = 2'b11;
      6'b111010: incount_gold = 2'b11;
      6'b111011: incount_gold = 2'b11;
      6'b111100: incount_gold = 2'b10;
      6'b111101: incount_gold = 2'b10;
      6'b111110: incount_gold = 2'b10;
      6'b111111: incount_gold = 2'b10;
      endcase
    end
  endfunction

  initial begin
`ifdef FPGA_FF_MODE
    $display("CGA_MIC_INCOUNT_tb: FPGA_FF_MODE (sysclk+MCLK_EN capture)");
`else
    $display("CGA_MIC_INCOUNT_tb: latch/CP mode (posedge MCLK capture)");
`endif

    // ------------------------------------------------------------------
    // 1. Async preset: falling MRN forces 11 with no clock event, and
    //    dominates a simultaneous clocked load of 00.
    // ------------------------------------------------------------------
    #12;
    MRN = 0;  // real falling edge -> posedge on internal s_mr
    #3;
    check_state(2'b11, "preset-async");
    LWCAN = 0;
    CD0   = 1;  // load would give 00
    CD1   = 1;
    pulse_mclk;
    check_state(2'b11, "preset-dominates-load");
    MRN = 1;
    #3;

    // ------------------------------------------------------------------
    // 2. Inverting load: all 4 CD combinations.
    // ------------------------------------------------------------------
    for (v = 0; v < 4; v = v + 1) begin
      LWCAN = 0;
      EC    = 0;
      CD0   = v[0];
      CD1   = v[1];
      pulse_mclk;
      check_state(~v[1:0], "load");
    end

    // ------------------------------------------------------------------
    // 3. Exhaustive transition table: 4 states x 16 input combos.
    // ------------------------------------------------------------------
    for (s = 0; s < 4; s = s + 1) begin
      for (v = 0; v < 16; v = v + 1) begin
        load_state(s[1:0]);
        check_state(s[1:0], "reload");
        LWCAN = v[3];
        EC    = v[2];
        CD1   = v[1];
        CD0   = v[0];
        pulse_mclk;
        check_state(incount_gold({s[1:0], v[3:0]}), "transition");
      end
    end

    // ------------------------------------------------------------------
    // 4. Wrap sequence: down-count 00->11->10->01->00->11->10->01->00.
    // ------------------------------------------------------------------
    load_state(2'b00);
    check_state(2'b00, "wrap-load");
    LWCAN = 1;
    EC    = 1;
    pulse_mclk; check_state(2'b11, "wrap1");
    pulse_mclk; check_state(2'b10, "wrap2");
    pulse_mclk; check_state(2'b01, "wrap3");
    pulse_mclk; check_state(2'b00, "wrap4");
    pulse_mclk; check_state(2'b11, "wrap5");
    pulse_mclk; check_state(2'b10, "wrap6");
    pulse_mclk; check_state(2'b01, "wrap7");
    pulse_mclk; check_state(2'b00, "wrap8");

    // ------------------------------------------------------------------
    // 5. Hold without a clock event (state is 00 here).
    // ------------------------------------------------------------------
    LWCAN = 0;
    CD0   = 0;  // a load would give 11
    CD1   = 0;
    #40;
    check_state(2'b00, "hold-no-clock-load-inputs");
    LWCAN = 1;
    EC    = 1;  // a count would give 11
    #40;
    check_state(2'b00, "hold-no-clock-count-inputs");

    // ------------------------------------------------------------------
    // 6. Preset from state 00, then one count 11 -> 10.
    // ------------------------------------------------------------------
    MRN = 0;
    #3;
    check_state(2'b11, "preset-from-00");
    MRN   = 1;
    LWCAN = 1;
    EC    = 1;
    pulse_mclk;
    check_state(2'b10, "count-after-preset");

    // ------------------------------------------------------------------
    // Verdict. Expected: 2 preset + 4 load + 128 exhaustive + 9 wrap +
    // 2 hold + 2 preset/count = 147.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 147)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 147 checks)",
               errors, checks);
    $finish;
  end

endmodule
