/**************************************************************************
** ND120 CGA (CPU Gate Array / DELILAH)                                  **
** CGA_MIC_CSEL testbench                                                **
**                                                                       **
** Exhaustive verification of the condition-select mux tree:             **
**                                                                       **
**  1. 32 directed vectors with expected constants generated by the      **
**     independent Python model gen_mic_golden.py (mux tree re-derived   **
**     pin-by-pin from the netlist: PLEXERS_1 in0..7 = DZD,LCZ,IRQ,      **
**     RESTR,CFETCH,OOD,SPARE,COND; PLEXERS_2 in0..7 = 0,0,OVF,CRY,      **
**     F11,F15,ZF,STP; PLEXERS_3 sel = TSEL[3]; CONDN = ~mux out).       **
**  2. Exhaustive sweep of the full 18-bit input space (16 condition     **
**     inputs x 4 TSEL bits = 262144 combinations) with ALUCLK=0         **
**     (CSEL_LATCH transparent), each checked against the independent    **
**     in-tb model above.                                                **
**  3. Latch hold: with ALUCLK=1 (ENABLE=~ALUCLK low) CONDN must hold    **
**     the last value through input changes, and become transparent      **
**     again when ALUCLK drops.                                          **
**                                                                       **
** NOT pure combinational: CONDN goes through the ndlib LATCH            **
** (transparent while ALUCLK=0). The LATCH primitive is switched by      **
** USE_TRANSPARENT_LATCHES (true 74xx latch) vs default (sysclk mux+FF   **
** approximation) - FPGA_FF_MODE does not affect it. The Makefile        **
** target test-mic-csel therefore runs BOTH: plain and                   **
** -DUSE_TRANSPARENT_LATCHES.                                            **
**                                                                       **
** Self-checking: prints TB_RESULT: PASS / FAIL (never silent).          **
**                                                                       **
** 31-JUL-2026                                                           **
** Ronny Hansen                                                          **
***************************************************************************/
`timescale 1ns / 1ps

module CGA_MIC_CSEL_tb;

  reg        sysclk = 0;
  reg        ALUCLK = 0;
  reg        CFETCH = 0;
  reg        COND = 0;
  reg        CRY = 0;
  reg        DZD = 0;
  reg        F11 = 0;
  reg        F15 = 0;
  reg        IRQ = 0;
  reg        LCZ = 0;
  reg        OOD = 0;
  reg        OVF = 0;
  reg        RESTR = 0;
  reg        SPARE = 0;
  reg        STP = 0;
  reg  [3:0] TSEL_3_0 = 0;
  reg        ZF = 0;
  wire       CONDN;

  integer errors = 0;
  integer checks = 0;
  integer idx;

  CGA_MIC_CSEL dut (
      .sysclk  (sysclk),
      .ALUCLK  (ALUCLK),
      .CFETCH  (CFETCH),
      .COND    (COND),
      .CRY     (CRY),
      .DZD     (DZD),
      .F11     (F11),
      .F15     (F15),
      .IRQ     (IRQ),
      .LCZ     (LCZ),
      .OOD     (OOD),
      .OVF     (OVF),
      .RESTR   (RESTR),
      .SPARE   (SPARE),
      .STP     (STP),
      .TSEL_3_0(TSEL_3_0),
      .ZF      (ZF),
      .CONDN   (CONDN)
  );

  always #5 sysclk = ~sysclk;

  // Input packing, identical to gen_mic_golden.py:
  // i[17:14]=TSEL, i[13]=DZD i[12]=LCZ i[11]=IRQ i[10]=RESTR i[9]=CFETCH
  // i[8]=OOD i[7]=SPARE i[6]=COND i[5]=OVF i[4]=CRY i[3]=F11 i[2]=F15
  // i[1]=ZF i[0]=STP
  task apply_idx(input [17:0] i);
    begin
      STP      = i[0];
      ZF       = i[1];
      F15      = i[2];
      F11      = i[3];
      CRY      = i[4];
      OVF      = i[5];
      COND     = i[6];
      SPARE    = i[7];
      OOD      = i[8];
      CFETCH   = i[9];
      RESTR    = i[10];
      IRQ      = i[11];
      LCZ      = i[12];
      DZD      = i[13];
      TSEL_3_0 = i[17:14];
    end
  endtask

  // Independent golden model (re-derived from the netlist, see header).
  function golden_condn(input [17:0] i);
    reg p1, p2, v;
    begin
      case (i[16:14])
        3'd0: p1 = i[13];  // DZD
        3'd1: p1 = i[12];  // LCZ
        3'd2: p1 = i[11];  // IRQ
        3'd3: p1 = i[10];  // RESTR
        3'd4: p1 = i[9];   // CFETCH
        3'd5: p1 = i[8];   // OOD
        3'd6: p1 = i[7];   // SPARE
        3'd7: p1 = i[6];   // COND
      endcase
      case (i[16:14])
        3'd0: p2 = 1'b0;   // GND
        3'd1: p2 = 1'b0;   // GND
        3'd2: p2 = i[5];   // OVF
        3'd3: p2 = i[4];   // CRY
        3'd4: p2 = i[3];   // F11
        3'd5: p2 = i[2];   // F15
        3'd6: p2 = i[1];   // ZF
        3'd7: p2 = i[0];   // STP
      endcase
      v = i[17] ? p2 : p1;
      golden_condn = ~v;
    end
  endfunction

  task csel_vec(input [17:0] i, input exp);
    begin
      apply_idx(i);
      #2;
      checks = checks + 1;
      if (CONDN !== exp) begin
        errors = errors + 1;
        $display("FAIL directed: idx=%06o got CONDN=%b expected %b",
                 i, CONDN, exp);
      end
    end
  endtask

  initial begin
`ifdef USE_TRANSPARENT_LATCHES
    $display("CGA_MIC_CSEL_tb: USE_TRANSPARENT_LATCHES (true latch)");
`else
    $display("CGA_MIC_CSEL_tb: default LATCH (sysclk mux+FF approximation)");
`endif

    // ------------------------------------------------------------------
    // 1. Directed vectors, expected constants from gen_mic_golden.py.
    // ------------------------------------------------------------------
    csel_vec(18'o660443, 1'b1);
    csel_vec(18'o414017, 1'b1);
    csel_vec(18'o723567, 1'b0);
    csel_vec(18'o130662, 1'b1);
    csel_vec(18'o730007, 1'b0);
    csel_vec(18'o726244, 1'b1);
    csel_vec(18'o255304, 1'b1);
    csel_vec(18'o055417, 1'b0);
    csel_vec(18'o236051, 1'b1);
    csel_vec(18'o771311, 1'b0);
    csel_vec(18'o701025, 1'b1);
    csel_vec(18'o544543, 1'b1);
    csel_vec(18'o305455, 1'b1);
    csel_vec(18'o651001, 1'b1);
    csel_vec(18'o234110, 1'b1);
    csel_vec(18'o427362, 1'b1);
    csel_vec(18'o511732, 1'b1);
    csel_vec(18'o127414, 1'b0);
    csel_vec(18'o474162, 1'b1);
    csel_vec(18'o713477, 1'b0);
    csel_vec(18'o347566, 1'b0);
    csel_vec(18'o126012, 1'b0);
    csel_vec(18'o641232, 1'b1);
    csel_vec(18'o070521, 1'b0);
    csel_vec(18'o002532, 1'b1);
    csel_vec(18'o366364, 1'b0);
    csel_vec(18'o333475, 1'b1);
    csel_vec(18'o437750, 1'b1);
    csel_vec(18'o143112, 1'b0);
    csel_vec(18'o165446, 1'b1);
    csel_vec(18'o254754, 1'b0);
    csel_vec(18'o474417, 1'b1);

    // ------------------------------------------------------------------
    // 2. Exhaustive sweep of all 262144 input combinations (ALUCLK=0,
    //    latch transparent).
    // ------------------------------------------------------------------
    for (idx = 0; idx < 262144; idx = idx + 1) begin
      apply_idx(idx[17:0]);
      #2;
      checks = checks + 1;
      if (CONDN !== golden_condn(idx[17:0])) begin
        errors = errors + 1;
        $display("FAIL sweep: idx=%06o got CONDN=%b expected %b",
                 idx[17:0], CONDN, golden_condn(idx[17:0]));
      end
    end

    // ------------------------------------------------------------------
    // 3. Latch hold: raise ALUCLK, change inputs, CONDN must hold; drop
    //    ALUCLK, CONDN transparent again.
    // ------------------------------------------------------------------
    apply_idx(18'o000000);
    DZD = 1;  // TSEL=0 selects DZD -> v=1 -> CONDN=0
    @(posedge sysclk);
    #1;
    checks = checks + 1;
    if (CONDN !== 1'b0) begin
      errors = errors + 1;
      $display("FAIL hold-setup: got CONDN=%b expected 0", CONDN);
    end
    ALUCLK = 1;
    #1;
    DZD = 0;  // would give CONDN=1 if transparent
    #38;
    checks = checks + 1;
    if (CONDN !== 1'b0) begin
      errors = errors + 1;
      $display("FAIL hold: got CONDN=%b expected 0 (held)", CONDN);
    end
    ALUCLK = 0;
    #2;
    checks = checks + 1;
    if (CONDN !== 1'b1) begin
      errors = errors + 1;
      $display("FAIL transparent-again: got CONDN=%b expected 1", CONDN);
    end
    @(posedge sysclk);
    #1;
    ALUCLK = 1;
    #1;
    DZD = 1;  // would give CONDN=0 if transparent
    #38;
    checks = checks + 1;
    if (CONDN !== 1'b1) begin
      errors = errors + 1;
      $display("FAIL hold2: got CONDN=%b expected 1 (held)", CONDN);
    end

    // ------------------------------------------------------------------
    // Verdict. Expected: 32 directed + 262144 sweep + 4 hold = 262180.
    // ------------------------------------------------------------------
    if (errors == 0 && checks == 262180)
      $display("TB_RESULT: PASS (%0d checks)", checks);
    else
      $display("TB_RESULT: FAIL (%0d errors, %0d of 262180 checks)",
               errors, checks);
    $finish;
  end

endmodule
